### ISSUE TITLE
Best practices for securing Flux Standalone

### ISSUE THREAD

**Issue by TheJaySmith** [fluxcd/flux#1244]
Hello,

I am working on integrating Flux Standalone with Kubeflow. My main problem was getting the cluster to communicate with the "fluxctl" CLI tool. My current workaround was to create a LoadBalancer service in front of the flux service. This works but also raises a valid concern regarding security. What are the best practices to expose the Flux service to the world so the fluxctl can communicate with it but still keep it secure?

**Comment by squaremo** [comment]
I would recommend using a port forward, since being able to do that demonstrates you have credentials to connect to the Kubernetes API server. PR #1212 added an automatic port-forward to `fluxctl`, which will appear in the next release, soon.

If you are not able or willing to put credentials in the same place as you're using `fluxctl`, you could use an ingress and require a client certificate.

**Comment by dholbach** [comment]
Should this be documented somewhere? Maybe in the FAQ?

**Comment by kingdonb** [comment]
The treatment of notifications and communication with the outside world has gotten a whole new treatment in Flux v2.

https://github.com/fluxcd/notification-controller

https://toolkit.fluxcd.io/guides/notifications/

https://toolkit.fluxcd.io/guides/webhook-receivers/

💯
