### ISSUE TITLE
Setting --registry-rps=0 appears to disable rate limiting rather than stop requests

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#1317]
According to https://godoc.org/golang.org/x/time/rate#Limiter, giving a rate limiter a zero limit means Wait will block forever or until the supplied context's deadline is reached. We give each image registry its own rate limiter, with a limit value given by the command-line argument `--registry-rps`.

Given that, you would expect that supplying `--registry-rps=0` would effectively disable the image fetching. However, it appears that it doesn't -- in fact it looks more like it isn't rate limited, or at least gets the default (and fairly generous) value of 200/s.

**Comment by squaremo** [comment]
Hrm: https://github.com/golang/go/issues/18763

**Comment by kingdonb** [comment]
If I read that issue thread correctly, you can create a zero Limiter, but not by using NewLimiter

Maybe this can be fixed by going around NewLimiter in case that `--registry-rps=0`

https://github.com/golang/time/blob/1f47c861a9ac5a6e7645609f91b895398ff31642/rate/rate.go#L40-L41

This issue is still open (two separate issues) in the upstream golang tracking

**Comment by pjbgf** [comment]
This project is in Migration and security support only, so unfortunately this issue won't be fixed. I am therefore tagging and closing it.

More information about the Flux 2 transition timetable can be found at: https://fluxcd.io/docs/migration/timetable/.
