### ISSUE TITLE
Feedback on invalid manifests

### ISSUE THREAD

**Issue by brantb** [fluxcd/flux#1340]
If I commit a change to a YAML manifest which will cause `kubectl apply` to fail (for example: changing the `type` field of a `Service`), this failure isn't communicated in a meaningful way unless I'm watching fluxd's logs for errors.

It would be nice if this experience were improved somehow, so that I can know whether or not the recent git commit has been successfully applied to the cluster.

**Comment by squaremo** [comment]
For sure. We do keep track of errors encountered when syncing resources, and these are included in the notifications sent upstream (to Weave Cloud). But, this is not as useful if you are using Flux by itself.

There's a few ways this info could be exposed otherwise:

 - as a metric: `flux_sync_error_count` or something like that. This would mean you can base alerts on having a prolonged error state; but, you don't get the individual errors to troubleshoot.
 - in the response to `fluxctl list-controllers`. This will let you see if a controller change hasn't applied correctly, but not if a change to some other resource has problems.
 - as a new API and `fluxctl` subcommand giving sync information for all resources; possibly `list-controllers` could just be made a special case of that.

**Comment by jrryjcksn** [comment]
A user said today that he loves the flux model but that this is a deal-breaker for his company...

**Comment by squaremo** [comment]
> this is a deal-breaker for his company...

@jrryjcksn There's quite a broad design space here -- did the person say more specifically what it was they couldn't do without? (or what form they would prefer the remedy to take)

**Comment by 2opremio** [comment]
Here is the full conversation with the user
https://weave-community.slack.com/archives/C4U5ATZ9S/p1554405139389400

**Comment by primeroz** [comment]
This is quite a deal breaker for use because we do need to know if what's in GIT has applied properly.

We perform schema validation before merging so we are not worried about typos , but there are cases where a perfectly valid schema will actually fail to apply ( change of an immutable field for example ) and other cases where schema validation is not available ( CRDs ) 

At the moment the only way for us to know that something is failing to apply in flux is through logs , we can alert on that through Elasticsearch + elastalert but a prometheus metric would be so much easier to manage.

Is this something planned or is there any issue to implement this ?

**Comment by 2opremio** [comment]
CC @yradsmikham

**Comment by nabadger** [comment]
Would be great if this could be achieved via a push to web-hooks.

Some standard web-hooks that could be implemented are;

- Prometheus Push Gateway
- PagerDuty
- OpsGenie

---

For now we can do something via elastalert and monitor the flux logs, but this isn't ideal and very fragile, since it relies on parsing the log-output which could change

**Comment by adusumillipraveen** [comment]
Any plans to implement this ? Not having alerting on flux being broken is a bit worrying us.

**Comment by primeroz** [comment]
Same for us.

We ended up using [ElastAlert](https://github.com/Yelp/elastalert) since all our logs are in elasticsearch but is not an ideal solution, mostly because , even after filtering , the "err=.*" match is way too wide and tend to trigger and generate noise.

**Comment by bmcstdio** [comment]
I second this as well. If we could agree on a design, I could probably have a go at implementing it. 🙂

**Comment by bmcstdio** [comment]
I went ahead and implemented the metrics-based approach over at #2534. Please let me know what you think. A Docker image containing a build of the PR is available at `bmcstdio/flux:pr-2534` if anyone's interested in taking it for a spin.

**Comment by smurfralf** [comment]
Nothing has been done to address this issue - the above MR was not merged. Logs remain as the only means of finding errors. Flux should improve the visibility of manifest deploy errors.

**Comment by primeroz** [comment]
@smurfralf we have been using the prometheus metrics to detect this , for example `flux_daemon_sync_manifests{job="flux",success="false"}  > 0` to tell us if there is _any_ error in syncing manifests, that will include invalid manifests and invalid changes.

**Comment by kingdonb** [comment]
Flux v2 has done quite a lot of work/improvement in the area of validation and error reporting, you can now easily guarantee that a commit either applies all the way or not at all with `validation: client` or `validation: server`.

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
