### ISSUE TITLE
Dedicated fixtures in tests

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux#1783]
From https://github.com/weaveworks/flux/pull/1394#discussion_r257237496

The fixtures in `cluster/kubernetes/testfiles` are reused throughout the code base. We should write dedicated fixtures for each package that 'borrows' these so they become self-contained.

**Comment by yiannistri** [comment]
@hiddeco @2opremio I'd be willing to get a PR/discussion going on this and get feedback if you like (or agree that the current approach is good enough 😄) So from my understanding the challenges are: 

- Test fixtures are buried in one package that many other packages are using
- Keep test code close to the package
- Avoid having (almost) identical test fixtures in many places

Is there anything else I should take into account?

**Comment by 2opremio** [comment]
I think it would also be good to have varied fixtures and incorporate fixtures employing `.flux.yaml` files. But maybe that's out of scope.

**Comment by yiannistri** [comment]
By varied fixtures do you mean the ability to build different test data according to the needs of each test? Like fluent test data builders?

**Comment by 2opremio** [comment]
Yes.

**Comment by yiannistri** [comment]
After having a closer look at the specific tests, they seem to be targeting mainly the code in the `cluster/kubernetes/resource` and`git` modules. So most of the effort to split them will be about creating specific fixtures that live alongside these modules. Any shared test code between them would live in a shared package or even under the top level `/test` directory. How does that sound?

Regarding test data builders, I've made an attempt to implement one [here](https://github.com/yiannistri/flux/commit/9a56c6e2e77795c80c199be08283e6e5ccc49730) for 3 test cases using the `unstructured` object from apimachinery. I went down this route because it was the simplest approach but I was thinking maybe code generation could be used instead. Thoughts?

Please, let me know what you think 🤓

**Comment by yiannistri** [comment]
I have moved the (non-encrypted) test fixtures to `/test` as they are shared. It seems to me that they serve two needs:

-  As test fixtures for when initialising a git repo to test git operations
-  As test fixtures for when they are read to ensure they are parsed correctly

Although they don't need to be shared, I can understand the convenience of having a single set of files. Do you think there's value in splitting them? 

I would also like some input before continuing with the test data builders as it can be subjective. I would use them for building complicated in-memory objects but in this case the simplicity of having the plain yaml there in each test may be preferred. If so, which tests would benefit more from using test data builders in your opinion?

@hiddeco @2opremio  thoughts?

**Comment by kingdonb** [comment]
The PR that goes with this report has been closed by the contributor.

I am closing this issue, as it appears to be outside the scope of maintenance mode in Flux v1. Thanks!
