### ISSUE TITLE
Deletion of resources not installed via helm release

### ISSUE THREAD

**Issue by benhartley** [fluxcd/flux#1911]
We bootstrap Flux via bootkube (namespace, secret, deployment, service account etc.) and then once Flux is up it redeploys itself via a helm release using the provided chart. We use the same service account for Flux and the Helm Operator.

At the moment, the initial helm release fails because the service account already exists. Tiller logs:

```
[tiller] 2019/04/08 15:25:45 warning: Release "flux" failed: serviceaccounts "flux" already exists
```

At this point, we have no helm release, however, Tiller then starts deleting the resources that were created via bootkube:

```
[tiller] 2019/04/08 15:25:45 uninstall: Deleting flux
...
[kube] 2019/04/08 15:25:45 Starting delete for "flux-secrets" ServiceAccount
```

Once this has run, we have no Flux, and the Helm Operator no longer works since the service account has disappeared, so we can't reconcile further.

This may not be a bug, although deleting resources that were not installed via helm does feel a little strange.

**Comment by hiddeco** [comment]
Can you confirm the removal also happens when you do a manual install of the chart  (not driven by the Helm operator)? Because if this is the case, (and I have the sense it is), it is Helm / Tiller doing things we do not have control over.

To work around it (and prevent Helm from trying to create a service account while it is already there), you could set the `serviceAccount.create` in your `values` to `false`.

**Comment by swade1987** [comment]
@hiddeco but doesn't that mean that if the SA was deleted for any reason, flux won't put it back again, that is far from ideal.

**Comment by hiddeco** [comment]
Flux will never be able to put it back because when the service account is removed Flux loses access to the cluster.

**Comment by benhartley** [comment]
A manual helm install in a "pristine" cluster results in the same release failure (i.e. helm can't install due to the service account already existing), but no deletion is triggered - the bootkube Flux resources are still running

**Comment by hiddeco** [comment]
Okay, the thing that is bugging you is the condition we have in the operator where it removes a failed release if it is the result of an initial roll-out (so it can be retried later).

Without making modifications to the operator (maybe a flag in the `HelmRelease` to tell it to deviate from this behavior) there is no remedy.

Nevertheless would your release still fail without the mentioned modification to your `values`.

**Comment by benhartley** [comment]
Setting `rbac.create` and `serviceAccount.create` to `false` and then managing those resources via Flux still, but as plain manifests seems to have done the trick

**Comment by squaremo** [comment]
Have I got this right: Tiller will remove resources it didn't create, if they look like the resources it would have created had it not failed because the resources already existed .. Ouch.

Do you think we can extract something from here to put in FAQ or troubleshooting?

**Comment by benhartley** [comment]
> Tiller will remove resources it didn't create, if they look like the resources it would have created had it not failed because the resources already existed

Correct, this is the current behaviour we're seeing

**Comment by kingdonb** [comment]
> it is Helm / Tiller doing things we do not have control over.

> Without making modifications to the operator (maybe a flag in the HelmRelease to tell it to deviate from this behavior) there is no remedy.

There might be something we could add to the FAQ, but I'm not sure what. In spite of the gravity of this issue I think due to points highlighted above, we will have to close it with no action.

I'd be more than happy to review an update to the FAQ or any other change if one can be suggested. Can be reopened if an active contributor is interested in working it.

As for now, this issue has gone stale, closing.
