### ISSUE TITLE
`--previous` flag for `fluxctl release`

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/flux#2221]
**Describe the feature**

A `--previous` flag for `fluxctl release`, which rolls back the given `--workload` to the image before the current image (with filters being applied if configured).

This is useful in more complex CI setups where for example an e2e smoke test can detect (and with this feature easily roll back) a faulty release.

**NB:** for automated resources we would probably need to lock it at the same time, as otherwise it will roll forward again (`--lock`?).

**What would the new user story look like?**

1. CI performs a release with `fluxctl release --workload <namespace>:<type>/<name>`
2. e2e smoke test detects abnormalities, CI now wants to perform a rollback
3. CI runs `fluxctl release --workload <namespace>:<type>/<name> --previous`
4. resource is now one version behind 'latest'

**Comment by luislhl** [comment]
Maybe this can be solved using `kubectl rollout undo`, or am I missing something?

**Comment by alwaysastudent** [comment]
Rollback should be atomic, and should be a revert to the previous git sha that was in sync.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
