### ISSUE TITLE
Attach "do not upgrade past this without ..." caveats to image

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#224]
Some images require config changes, or other interventions. For instance, if a new flag has been added to an executable. It'd be useful to be able to prevent people or automation from unwittingly breaking things by deploying such an image, perhaps by attaching a caveat to the image itself, or something associated with it (a PR, or the commit, or ..).

**Comment by SamMorrowDrums** [comment]
Interesting, I was just worrying about this the other way around, with Liveness probes.

Suppose my launch version of a service has no liveness probe, but then I add one. If I update the config before the image update, then the service will crashloop.

I guess this is because instead of pure CI, I want to promote changes from testing to staging to production and so having to remember "Oh so now that staging is updated, I need to add in the liveness probe" is not a graceful solution.

I would love it if the config task wasn't sometimes paired with the container update but it is often enough to be a real problem (without coordination).

Holding a configuration change, waiting for an image, or holding an image waiting for a configuration change, this problem could do with a better solution than do it by hand.

**Comment by sambooo** [comment]
Flux now supports locking resources with arbitrary messages and I believe this fits the use case here.

**Comment by squaremo** [comment]
> Flux now supports locking resources with arbitrary messages and I believe this fits the use case here.

Not quite, the idea here is that the image itself carries with it the requirement (as in the title).

Why is locking not enough? Because this isn't a "you cannot proceed", it's a "you cannot proceed past here without ...". To use locking you'd have to go and lock all the controllers that used an image, before merging the change (or pushing the image). That would stop anything else happening with those controllers.

A better though still hand-waving design would be to treat such images as gates, and check the preconditions before upgrading -- or at least, to alert a human that it needs to be done.

**Comment by sambooo** [comment]
Oh right I see my mistake here

**Comment by kingdonb** [comment]
I think this is still a need, but between Flagger and semver policy in Flux v2 I think it's safe to say the solution won't come in Flux v1 at this point.

IMHO you also have to trust semver at some point.

If you're dealing with software that adds features which break your API uses in a patch version, (1) that probably wasn't something the developers of said software considered as a public API (in other words, guess you shouldn't have done that), and (2) there's little that the software delivery mechanism can do to help you, that wouldn't have been solved by understanding the software author's contract semver contract (or their adhering to semver) a little more completely.

If breaking changes are allowed on major versions only, don't upgrade past MAJOR version in production without so much as at least a staging review. If the software allows breaking (configuration) changes at the MINOR version only, then don't allow automation to upgrade past a minor version.

What would be really handy, if we haven't already implemented it in Flux v2, is a prometheus gauge metric that indicates how many upgrades your automations are *preventing* (possibly even down to granularity of: how many are minor/major bumps?)
