### ISSUE TITLE
Flux agent goroutine count and memory usage grows to problematic levels.

### ISSUE THREAD

**Issue by bricef** [fluxcd/flux#2263]
### Describe the bug

Recently after careful increase of workloads in a cluster with the `weave-flux-agent` installed, we find that the weave agent (through the Weave Cloud Deploy dashboard) is timing out or takes longer time to load. During these period, we noticed that the number of go-routines on the flux agent go high and also cause the node on which Flux is running to run out of resources. Could we please help troubleshoot and understand the cause of this issue ?

![flux-leak](https://user-images.githubusercontent.com/250051/61317502-00967100-a7fb-11e9-9a9d-9e739c2e8af3.png)

### To Reproduce

1. Install the latest version of the flux K8s agent (through Weave Cloud in this case). 
2. Increase the number of workloads
3. Observe the flux agent golang Prometheus metrics on memory usage and goroutine count

### Expected behaviour

I would not expect the memory of the fklux agent to grow beyond a reasonable level.

**Comment by bricef** [comment]
(NB: Further information to be provided by original reporter)

**Comment by hiddeco** [comment]
Is this screenshot _before_ or _after_ +-08:45 UTC today?

**Comment by bricef** [comment]
@hiddeco before

**Comment by hiddeco** [comment]
@bricef Weave Cloud customers were upgraded to `1.13.2` today (new version range merged at 08:45 UTC).

The goroutines observed in this screenshot are probably due to the Kubernetes API rate-limiting requests, this will result in a pile of routines waiting for an answer and due to the deploy page making requests every `x` seconds, this pile will only grow. I implemented a timeout in #2171 (`>=1.13.1`) to prevent this from happening, so please check with the reporter if the issue is still relevant.

**Comment by bricef** [comment]
Thanks @hiddeco. Sounds like the changes worked and the customer is no longer experiencing these issues. I'll close this for now.
