### ISSUE TITLE
Changing namespace of HelmRelease causes duplication of kubernetes resources

### ISSUE THREAD

**Issue by jowparks** [fluxcd/flux#2269]
**Describe the bug**
If you change your `HelmRelease` `namespace` (ie `dataeng-test` to `dataeng`) flux-helm-operator creates a new helm release (one in each namespace) rather than deleting the old (`dataeng-test`) one and creating a new one in the new (`dataeng`) namespace. I guess this might be desired result in a way… Weird thing was that the helm release for the old namespace (`dataeng-test`) was getting picked up and released in helm, which was then getting used in the new namespace (`dataeng`) somehow even though the original `HelmRelease` definition was pointing to `dataeng-test`. Logs where not very helpful in figuring out what was going on.

In order to fix, I had to manually delete the kubernetes resource helmrelease for the old namespace

**To Reproduce**
Steps to reproduce the behaviour:
Create HelmRelease, allow release to process. PR and merge a change to the namespace only, and see both HelmReleases get created.

**Expected behavior**
If the namespace of a helm release is UPDATED, the old release should be updated rather than a new created and the old one left dangling. Alternatively, the old release could be deleted and a new one created for the new namespace.

**Comment by hiddeco** [comment]
If you change the namespace of any resource that Flux manages it will lead to one unmanaged resource (in the old namespace) and one managed (in the new namespace), this is expected behaviour and also what you are observing. If you want Flux to clean up resources that are no longer in git, there is a [garbage collection feature](https://github.com/fluxcd/flux/blob/master/site/garbagecollection.md).

**Comment by hiddeco** [comment]
I think this question has been answered by my above comment @jowparks, so I am closing this to get it of our radar. But please get in touch if things are still unclear. :tulip:
