### ISSUE TITLE
Add a possibility to install helm chart even if the status is not DEPLOYED, e.g. FAILED

### ISSUE THREAD

**Issue by ilya-spv** [fluxcd/flux#2294]
**Describe the feature**
If a release is in a failed state helm operator does not attempt to install on top. According to an issue [here](https://github.com/fluxcd/flux/issues/1854) this is because it only attempts to update in the case of a release in a status DEPLOYED.

Now a common workflow is to make a change in a config file and deploy, figure out that it was a failure for some reason, try to fix a config file and deploy again.

At this point helm operator won't do anything because the status is FAILED.

**What would the new user story look like?**
Nothing would change for a user directly

**Expected behavior**
Helm operator will attempt to deploy in at least FAILED state (perhaps some others may be considered as well)

P.S. Perhaps this feature is already implemented and I am just using an old version?

**Comment by stefanprodan** [comment]
Enabling [rollbacks](https://github.com/fluxcd/flux/blob/master/site/helm-integration.md#rollbacks) would solve this I think. If you make a change that breaks the release, Flux will roll it back allowing you to push a fix.

**Comment by ilya-spv** [comment]
It seems it might help indeed, but maybe it's better to deploy a new version even if there is a failure anyway? There seem to be possible problems with rollback, so while it should help, it's not exactly the same as allowing to install again regardless of state if there was a change.

**Comment by stefanprodan** [comment]
Helm does not supports upgrading a failed release, unless you do a rollback.

**Comment by ilya-spv** [comment]
Sounds bad, then there is no way this can be fixed?

**Comment by hiddeco** [comment]
There are as far as I know two ways to upgrade a `FAILED` Helm release:

1. rollback to a healthy state and redo the `helm release`
2. perform a `helm release --force`, which will remove all resources and replace them with new ones, likely resulting in downtime and/or loss of data

The former is possible since version `0.10.0` of the Helm operator, using the `--force` is also possible, but not for releases in a non-healthy state, it was implemented for the operator to be able to cope with backwards incompatible chart releases containing e.g. updates to immutable resource types.

Given the complexity this feature would add (as we would need to extend the state machine invented for rollbacks), while delivering something that potentially can do more harm than good (given that it removes and creates resources, which is a dangerous operation depending on the chart you are releasing), I would say that this is not something that we are going to implement _at the moment_, as Helm is not giving us enough tooling to make it a secure operation.

**Comment by ilya-spv** [comment]
Ok, I see, thanks for an extensive answer. I guess you can close the issue then, unless you want to keep it for future when helm allows a better control :)
