### ISSUE TITLE
Is Flux also a replacement for tools like Consul?

### ISSUE THREAD

**Issue by blancsys** [fluxcd/flux#2310]
Hi! This is not a bug report neither a feature request, this is an "architectural question". Maybe this is not the right place to do it.

I have used Flux (and its Helm operator) for months. I understand that it's basically a CD tool. I think that ([decoupling CI from CD](https://www.weave.works/blog/kubernetes-anti-patterns-let-s-do-gitops-not-ciops) is a great pattern.

I just want to confirm something: Am I wrong or Flux (and its Helm Operator) is also a replacement for Service Discovery (Configuration) using tools like Consul? The traditional approach is: you have a Consul server, you put the configuration there (in its Key/Value store), and then you attach an init container that runs envconsul or consul-template to pull the right config values, inject the required environment variables (or creating the required config files) and then start your application. This is really needed when you just launch deployments without configuration.

But, if we define Helm Charts for everything and define Helm Releases using Flux (which contains the configuration), it looks for me that it's a better (declarative) and simpler replacement for tools like Consul. It's true that Consul can also act as a DNS server for external services but you can also provide hostnames using your Helm Releases. It seems like using a tool that pulls configuration from a central server is also an antipattern if you are trying to handle your configuration in a declarative way and using a push/reconcile approach. It's less visible.

So, I just want to confirm my assumption, I'm interested in your thoughts. Many greenfields projects states as a requirement the deployment of a "service discovery" tool. I'm tempted to say "you don't need Consul if you use Weave Flux" but I want to confirm if I'm missing something.

Thanks in advance

**Comment by stealthybox** [comment]
:wave: Hey, cool question.
Flux isn't really the tool here that's replacing Consul here.

Kubernetes and its components are providing you with Service Discovery, DNS, and Load-Balancing.
Kubernetes is also providing you declarative config for everything.

Helm is giving you an abstraction to simplify all of your Kubernetes Objects into simpler config (values).

Many people stop here and do not use Flux or helm-operator, but they still don't need Consul, because Kubernetes and Helm are already serving all of these functions.
They organize, maintain, and apply their configuration using other tools.

Helm-operator does provide a nice kubernetes-native wrapper (CRD) around helm2, but helm2 does already store all of its state in the cluster as ConfigMaps or Secrets -- this is similar to Consul's key/value-store role as you described.
(Side-note: when helm3 is here, it will provide its own CRD's but we'll still need to support an operator.)

Flux's main role is to provide you with a secure, hands-off, cluster-specific way to apply manifests and enforce policies about which images, tags, and annotations are in use. It also makes sure that you're doing this with source control -- this is GitOps. :)

Lmk if that's helpful!

**Comment by blancsys** [comment]
@stealthybox Hi, thanks for your great answer! It's very useful. I understand that Consul provides other features not included in Flux (like acting as a DNS server) so Flux is not a drop-in replacement for Consul if you need to use such services (for example to resolve services that are located our of the cluster). I have been thinking about the configuration part, about how we store and configure our k8s deployments. If we use Flux, I don't see the point of using Consul (it's KV store) and then Consul-Template/EnvConsul. I think that your reply means that we don't need Consul for that purpose if we use Flux (and its Helm operator). Thanks!
