### ISSUE TITLE
Give feedback on incorrect annotations 

### ISSUE THREAD

**Issue by jowparks** [fluxcd/flux#2354]
**Describe the bug**
I had an incorrectly formatted annotation that threw no error in logs of either FluxHelmOperator or Flux pod, the helm release was just not being released or added at all.

**To Reproduce**
Add improperly formatted `tag.chart-image`
`flux.weave.works/tag.chart-image: regexp: development-.*`
fixed by changing to:
`flux.weave.works/tag.chart-image: regex:^development-.*`

**Expected behavior**
Some error in log upon inability to parse yaml/find image

**Logs**
None applicable 🤷‍♂ 

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.12.0
- Helm Operator version: 0.8.0
- Kubernetes version: v1.13.8-eks-a977ba"
- Git provider: bitbucket

**Comment by 2opremio** [comment]
The problem is that it's hard to know whether the annotation is missing or not.

I guess we could do two things:
1. Print a warning if any of the`fluxcd.org`-prefixed annotations doesn't exist (and take the opportunity to warn about `flux.weave.works` annotations being deprecated).
1.b) for extra points we could use something like https://github.com/sajari/fuzzy to suggest other names.
2. If there is an automation `annotated=true` make sure that the other annotations are correctly defined or otherwise emit a warning.

**Comment by kingdonb** [comment]
Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

If you have a use case for Flux that isn't covered well in the new Flux v2 (which is a total rewrite), we want to hear about it.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/
