### ISSUE TITLE
Kustomize and deleted resources

### ISSUE THREAD

**Issue by emas80** [fluxcd/flux#2428]
**Describe the bug**
I have a working setup of Flux using Kustomize, everything has been done following the documentation. I am very happy of the final result.

The problem is, I have removed some resources (deployments + related configmap hpa etc) by deleting the yaml from Git, and during the first iteration Flux gets completely stuck and logs

`
ts=2019-09-04T20:04:21.001530336Z caller=loop.go:111 component=sync-loop event=refreshed url=ssh://git@github.com/XXXX.git branch=master HEAD=a300161964a00f8d26072f7bf0600e41cdba71ed
ts=2019-09-04T20:04:24.083994965Z caller=loop.go:85 component=sync-loop err="loading resources from repo: cannot patch generated resources: missing resource (team-blue:deployment/Deployment) for patch"
ts=2019-09-04T20:04:39.688918792Z caller=images.go:17 component=sync-loop msg="polling images"
ts=2019-09-04T20:04:41.352761131Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: cannot patch generated resources: missing resource (team-blue:deployment/Deployment) for patch"
`

That is because, instead of first deleting the resources and then "fixing" the patch file, it first tries to apply the patch file and it complains because such resources do not exist anymore.
Nothing gets deleted from the cluster, please note that instead any change/new resource is correctly created and Git is synchonized in the case of any releases.

In order to unlock Flux, I have to remove the references from the patch file - patching the patch - and after that Flux picks the new file, and it is able to remove the resources from the cluster.

**To Reproduce**
Create some resources, apply a flux-patch.yaml - for example by pushing a new docker image that triggers the automatic release + git update.
Then delete the resource by removing the files from Git - everything except the content of the patch file.

**Expected behavior**
I would expect that the resources are deleted and the references removed from the patch file, because at the end of the day the patch file has been created by Flux automatically during a release.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.14.2

**Comment by jwenz723** [comment]
I experienced this issue today and had a difficult time figuring out what was happening because the error message is rather vague: `getting unlocked automated resources: cannot patch generated resources: missing resource (namespace:deployment/Deployment) for patch`

It would be helpful if the error message included the name of the deployment that it is trying to patch, or at least a reference to the file containing the patch that is failing.

**Comment by squaremo** [comment]
The patch file is supposed to be maintained automatically, and part of that would surely be garbage collecting patches that no longer correspond to a manifest.

But:

 -  when you rename a resource, you'd probably want its patch to "follow" it, rather than be removed altogether.
 - removing patches involves committing back to the repo -- what if fluxd doesn't have write access? It would have to ignore the patches instead.

This makes me think automation with patch files like this is fundamentally problematic. Kustomize itself is brittle in this way, but perhaps gets away with it because it's assumed a human is in charge (so any breakage is the human's fault!).

**Comment by squaremo** [comment]
I can think of a couple of changes that would mitigate this problem:

 1. warn about patches that don't apply to any resource in the logs, but otherwise ignore them, rather than failing entirely

This would mean things are still synced, and still garbage collected. There would still be problems:
 - obsolete patches would remain
 - renaming a resource loses its patch (so e.g., it would no longer be automated, or have an up-to-date image)

 2. provide safety checks that can be run in CI; for example, the ability to lint a configuration to make sure it is consistent (e.g., doesn't contain patches referring to missing resources)

I'm a little more wary of removing patches automatically; firstly because it's a pain to arrange in the code; and secondly, because it may not always give the expected outcome. As an example of the second case, what if you accidentally renamed a resource -- you might want the chance to go in and retarget the patch, at least.

**Comment by 2opremio** [comment]
> In order to unlock Flux, I have to remove the references from the patch file - patching the patch - and after that Flux picks the new file, and it is able to remove the resources from the cluster.

That's correct. Making Flux smarter than that is dangerous as @squaremo mentioned above.

The documentation mentions that you need to maintain the patch file along with the resources (e.g. when you rename them)

**Comment by szinck1** [comment]
I'm experiencing this issue now. In my scenario, the deployment exists - it's deployed on the cluster and the patch is still referencing the deployment.

@emas80  What did you do to "patch the patch"?  Thanks

**Comment by 2opremio** [comment]
Just remove the the deployment and all the references to the deployment in the patch

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
