### ISSUE TITLE
Parallel releases gives git conflicts

### ISSUE THREAD

**Issue by guzmo** [fluxcd/flux#2432]
**Describe the bug**
When we do parallel releases in different pipelines we see the error below quiet often. It seems that if another pipeline pushes a release while another release has started, the local git repository will be behind remote and flux doesn't re-pull the branch, but rather throws this exception.

```
fluxctl --k8s-fwd-ns=flux release  --workload=deployment/some-service     --watch     --timeout=5m0s     --update-image=ourimage:tag
Submitting release ...
Error: git push git@bitbucket.org:a-repository.git [dev refs/notes/flux]: failed to push some refs to 'git@bitbucket.org:a-repository.git', full output:
 To git@bitbucket.org:a-repository.git
   2b99c5ba..c8b828ae  dev -> dev
 ! [rejected]          refs/notes/flux -> refs/notes/flux (fetch first)
error: failed to push some refs to 'git@bitbucket.org:a-repository.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Run 'fluxctl release --help' for usage.
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**To Reproduce**
Steps to reproduce the behaviour:

0. Multi environment repository with overlays/<dev,stage,prod> with a shared base. Each environment in a separate branch.
1. Create two services that exists both in the same environment/branch
2. Start two fluxctl release.... at almost the same time
3. One of them fails with above error

**Expected behavior**
Fluxctl should pull if it sees this error and try to automerge, if not possible, sure throw this exception.

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.14.1
- Helm Operator version: 0.10.1 
- Kubernetes version: 1.13.7-gke.19
- Git provider: Bitbucket

**Comment by max-lobur** [comment]
We're having similar concern since we put couple apps/envs in a single gitops repo, and they race for it. 
Can we have git rebase & retry couple times before failing?

**Comment by max-lobur** [comment]
Looks like this function: https://github.com/fluxcd/flux/blob/aef27b00febc7a0ea4f501e0ff83b88fe6ee5eab/git/working.go#L142
I can make a pull request if core team like the idea

**Comment by avielb** [comment]
hey, any news on this?

**Comment by kingdonb** [comment]
Do I understand correctly that you have multiple flux instances on different clusters managing the same git repository?

This is not a supported use of Flux v1. However, Flux v2 has this configuration as supported.

Please check out the multi-cluster example from the Flux v2 [getting started guide](https://toolkit.fluxcd.io/get-started/) - this is listed at the bottom of the guide, (which you should read first if you are new to Flux v2) and it is available here: https://github.com/fluxcd/flux2-kustomize-helm-example

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
