### ISSUE TITLE
Sync fails on: Loading resources from repo: duplicate resource from .flux.yaml and .flux.yaml

### ISSUE THREAD

**Issue by shamsalmon** [fluxcd/flux#2452]
**Describe the bug**
Sync fails to run, citing log message below

**To Reproduce**
Unsure what caused this issue

**Expected behavior**
Proper sync and resource created

**Logs**
```
ts=2019-09-18T18:08:57.235181512Z caller=loop.go:100 component=sync-loop err="loading resources from repo: duplicate resource from .flux.yaml and .flux.yaml"
ts=2019-09-18T18:13:47.464387509Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2019-09-18T18:13:47.696567548Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: duplicate resource from .flux.yaml and .flux.yaml"
ts=2019-09-18T18:13:58.425800041Z caller=loop.go:100 component=sync-loop err="loading resources from repo: duplicate resource from .flux.yaml and .flux.yaml"
ts=2019-09-18T18:13:58.426939045Z caller=loop.go:126 component=sync-loop event=refreshed url=git@xetxdevops/demo/flux.git branch=master HEAD=52870f9e14613dcdc987c4e6beb97558cb3d979b
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: latest
- Helm Operator version: latest
- Kubernetes version: 1.12
- Git provider: gitlab
- Container registry provider:

**Comment by shamsalmon** [comment]
This happened when kustomize was using the same base in two different kustomize.yaml files. the error messages is a little obscure though. maybe something to fix. I have resolved the original problem by removing the duplicate base.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
