### ISSUE TITLE
Make `fluxctl sync` faster in repos with a large amount of manifests

### ISSUE THREAD

**Issue by ysaakpr** [fluxcd/flux#2487]
**Describe the feature**
I have more than 500 apps running through flux Gitops. Which is increasing day by day by couple of numbers. I have been used Fluxctl for a couple of months, I get a feel that flux sync is directly proportional to the number of files in the git.

I use Fluxctl as a delivery step as my last step of CI, and there can be parallel builds of apps are happening and at the end of each such app build, I will call `flux sync` on a common repository. I believe here, in this case, the flux sync is doing a sync of the entire release repo, not just the app that I am building. What is the best approach to achieve max speed of release in this kind of setup? I prefer to keep a checksum of last applied file in the git repo itself so that it would be easier to find if there was a change the file without much effort of doing a diff.

**What would the new user story look like?**
The suggested solution according to me would be adding an optional path/switch in `flux sync` which can consider a couple of files which have been changed in the last commit, the flux can do a diff on the changes and find out the changed files and only sync them unless asked to sync all(force).

User can use, to only sync the changed file
`fluxctl sync`

and to sync the whole repo 
`fluxctl sync --force`

**Expected behavior**
The sync operation should be predictable in execution time and quick,

**Comment by 2opremio** [comment]
Why call `fluxctl sync` explicitly instead of letting Flux do the sync periodically? If the sync period is too long you can decrease it with the appropiate flags.

**Comment by arjunsbabu** [comment]
@2opremio @hiddeco  we dont want to reduce the flux sync timing as we have lot of yamls to apply and frequent execution will consume lot of memory. Hence the sync interval configured in our infra is 1 hour. But in case a new change has been applied in git we need to apply a sync immediately as waiting for 1 hour for the change is not a perfect solution. 
Right now i feel like the documentation of flux sync command is misleading. i can see multiple people including me misinterpreted  it. i also feel like flux sync is not giving much value. 

`````
wdc07-test2@zenit:/opt/cronjob$ fluxctl sync -h
synchronize the cluster with the git repository, now

`````

If we have some commands or API  to fetch the changes and apply it will be a really useful feature and looking forward for the same in next release. Right now we are using 1.18.0


 Thanks to @hiddeco for clarifying.  https://weave-community.slack.com/archives/C4U5ATZ9S/p1583227739153700

**Comment by ysaakpr** [comment]
How do we address it, maybe figuring out diff between the last applied config and new changes will be help here. Instead of doing a full release diff release will be faster. The scheduled sync can be full sync, and while calling fluxctl sync should be just the diff

**Comment by kingdonb** [comment]
The new design of Flux v2 encourages breaking your repository up into more `Kustomization` CRs so that they can be sync'ed on whatever schedules make sense for them, independently and without interfering with each other, and for scalability as well as other important features like [dependency order](https://toolkit.fluxcd.io/components/kustomize/kustomization/#kustomization-dependencies).

Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
