### ISSUE TITLE
Fluxctl install flux using a private docker registry

### ISSUE THREAD

**Issue by kwontae** [fluxcd/flux#2541]
**Describe the feature**
A clear and concise description of the feature.
being able to set up a flag or an argument to use flux image living in the private docker registry in the fluxctl install command.
**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.

As an engineer, I would like to deploy and use flux in my k8s cluster living in a private network that cannot talk to the public docker registry. 
It would be fluxctl install --image-repository <your docker registry endpoint> --imagePullSecrets <secret name> ...

Feel free to add a diagram if that helps explaining things.

**Expected behavior**
A clear and concise description of what you expect to happen.
No changes in behavior. Just using the private docker registry to pull the fluxcd image.

**Comment by kwontae** [comment]
Any updates?

**Comment by kingdonb** [comment]
It looks like this idea was ultimately declined in Flux v1 as discussed here https://github.com/fluxcd/flux/pull/2843#issuecomment-591387557

The idea being that `fluxctl install` already has too many knobs, and all the knobs you need should have been provided in the Helm chart.

While this argument is perhaps a little thin, it is past its time for arguing, as now Flux v1 is in maintenance mode, not generally adding new features at this point, only providing bug-fixes and critical security updates if needed, so that development efforts can be focused on producing and polishing the rewritten version... and the good news is, Flux v2 / GitOps Toolkit actually supports this requested behavior already with `flux bootstrap --registry` setting, and `--image-pull-secret`!

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
