### ISSUE TITLE
"Act normal" .flux.yaml mode

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#2550]
In https://cloud-native.slack.com/archives/CLAJ40HV3/p1571794316152600, Eric describes a problem with .flux.yaml processing: if you have a .flux.yaml anywhere, but you want plain YAMLs in some places, there are constraints over how you can organise things.

Since the manifest generation will look in parent directories for a `.flux.yaml`, once you have one, no directory underneath can use just plain YAMLs -- unless you write a script to cat them all.

A nice solution to this might be to have a variety of `.flux.yaml` config that reverts to YAML-as-usual processing. Possibly this could be composed with other forms (in the same way you can supply several commands) -- it needs a bit of thinking about.

**Comment by squaremo** [comment]
@2opremio I'd appreciate your thoughts on this -- have I misdiagnosed what's going on?

**Comment by 2opremio** [comment]
The diagnosis is correct, but I am not sure whether that's the best solution though.

Generally, I would recommend using two different `--git-path` parameters (one for the raw repos and another one for the .flux.yaml-driven ones). This may not work in all cases, but I would like to understand why first.

**Comment by EricHorst** [comment]
@2opremio are you saying that two `--git-path` parameters are allowed on the same fluxd? Or are you saying to run two different flux instances with different `--git-path`? The latter seems like a non-starter. We already have administrative fluxd and tenant fluxd and doubling that number seems less than ideal.

Two paths can be emulated in one repo without the `--git-path` parameter with a structure like:
```
/kustom/.flux.yaml
/kustom/kustomize.yaml
/raw/plain.yaml
```
But in either case, using this structure, or specifying two paths with the fluxd parameter, the first level of directories is completely artificial and forces one to make unnatural organizational decisions. If we have a deployment that has both generated and raw manifests, the must be split them into two, possibly distant (depending on the depth of each tree), locations. Further, if the vast majority of the repo is generated, and only one or two exceptions are needed it makes the raw location an oddball and over-lookable. That is to say, the structure needs to make sense and be maintainable by my team without laying traps which lead to mistakes. Lastly our team provides infrastructure to dev team tenants and we have to explain/convince and support  engineers organizing their own flux repos so having a solution which doesn't impose a repo structure will fly with greater ease.

The artificial structure is cumbersome enough that I lean toward the `command: (for f in *.yaml; do cat $f; echo '---'; done)` generator solution. But it's messy to emulate a reliable and equivalent version of the flux default file generator in bash one liner and I feel dirty doing it.

As I mentioned in Slack, the ancestor search for .flux.yaml is spot on for simplicity of configuration so I appreciate that. It's just inflexible in this one way, that a child can't break away from their ancestry.

**Comment by 2opremio** [comment]
@EricHorst I would still appreciate a complete example indicating why using `.flux.yaml` as is (and using two parameters passed to `--git-path`, one for the raw  manifests and another one for the generates ones, without a common `.flux.yaml` file) would lead to to an unnatural layout.

**Comment by EricHorst** [comment]
Thanks @2opremio. Your example looks good. And it appears you're getting behind a special directive.

As background, what I've got a repo which manages the base features of a dozen or so clusters. At the root of the repo are directories cluster-1/, cluster-2/, cluster-3/, etc. Along with a cluster-common dir which contains bases for manifest generation.

Each k8s cluster is bootstrapped with flux, set to this repo with --git-path=cluster-X/. Under the cluster-X path are the tenant flux deployments, kube-prometheus, nginx-ingress, and a growing number of other things. It's like the fluxcd multi-tenant example but multi-cluster. Within this tree there are a few places where raw yaml is inserted by other processes. They are single directories.

Under the cluster-X/ directory is a somewhat broad and deep in places directory structure. I'd like to avoid pushing that structure down one level and making the first decision encounted by the human be "hmm, where is app Z...oh, nope, not in kustomized. I guess raw." Second, I don't want to end up with:

**Comment by EricHorst** [comment]
Thanks @2opremio. Your example looks good. And it appears you're getting behind a special directive?

As background for this issue I'll paste from Slack: what I've got a repo which manages the base features of a dozen or so clusters. At the root of the repo are directories cluster-1/, cluster-2/, cluster-3/, etc. Along with a cluster-common dir which contains bases for manifest generation.

Each k8s cluster is bootstrapped with flux, set to this repo with --git-path=cluster-X/. Under the cluster-X path are the tenant flux deployments, kube-prometheus, nginx-ingress, and a growing number of other things. It's like the fluxcd multi-tenant example but multi-cluster. Within this tree there are a few places where raw yaml is used as the primary deployment, and a few places where raw yaml is committed by other processes. They would be single leaf directories.

Under the cluster-X/ directory is a somewhat broad and deep in places directory structure. I'd like to avoid pushing that structure down one level and making the first decision encounted by the human be "hmm, where is app Z...oh, nope, not in kustomized. I guess raw." Second, I don't want to end up with:

**Comment by EricHorst** [comment]
Thanks @2opremio. Your example looks good. And it appears you're getting behind a special directive?

As background for readers of this issue I'll paste from Slack:
What I've got a repo which manages the base features of a dozen or so clusters. At the root of the repo are directories cluster-1/, cluster-2/, cluster-3/, etc. Along with a cluster-common dir which contains bases for manifest generation. Each k8s cluster is bootstrapped with flux, set to this repo with --git-path=cluster-X/. Under the cluster-X path are the tenant flux deployments, kube-prometheus, nginx-ingress, and a growing number of other things. It's like the fluxcd multi-tenant example but multi-cluster.

Okay, so within this tree there are a few places where raw yaml is used as the primary deployment, and a few places where raw yaml is committed by other processes. They would typically be single leaf directories. Under the cluster-X/ directory is a somewhat broad flat directory structure but there is depth in places.
I'd like to avoid pushing that structure down one level and making the first decision encountered by the human be "hmm, where is app Z...oh, nope, not in kustomized. I guess raw."
Second, I don't want to end up with the following where app2 is split:
```
cluster1/.flux.yaml
cluster1/app1/
cluster1/app2/vendor/
cluster1/app2/local/
cluster1/app3/
cluster1/raw/.flux.yaml
cluster1/raw/app2/local/dynamic/rawpart.yaml
cluster1/raw/app4/
```
I realize that the depth in cluster1/raw/app2 isn't necessary but it helps orient the human, making it more obvious where the raw part fits in the app.

What I was after is
```
cluster1/.flux.yaml (with manifest generation)
cluster1/app1/
cluster1/app2/vendor/
cluster1/app2/local/
cluster1/app2/local/dynamic/.flux.yaml (overrides root config for this dir and children)
cluster1/app2/local/dynamic/rawpart.yaml
cluster1/app3/
cluster1/app4/.flux.yaml (overrides root config for this dir and children)
cluster1/app4/raw-resources.yaml
```
In those deep nested .flux.yaml files would be a directive to flux to expect raw manifests as normal.

**Comment by EricHorst** [comment]
@2opremio One point of clarification now that I'm thinking about what the --git-path option and what you've said. In your example, what prevents the first subdir, --git-path=cluster1, from going into cluster1/raw? It seems like cluster1/raw would be done twice?
```
--git-path=cluster1,cluster1/raw
.flux.yaml
cluster1/kustomization.yaml
cluster1/raw/raw-resource.yaml
cluster1/raw/.flux.yaml
```

I would have expected this to be equivalent in function:
```
--git-path=cluster1
.flux.yaml
cluster1/kustomization.yaml
cluster1/raw/raw-resource.yaml
cluster1/raw/.flux.yaml
```
I've been assuming that flux works this way: flux recursively descends the tree and at each directory it first searches for .flux.yaml in that directory or any parent up to the root of the repo (even searching above the git-path) before taking action on the directory. The first .flux.yaml found on the ascending search is used. Then flux proceeds to the next directory and repeats the search logic. So in this example flux would use .flux.yaml for everything except the cluster1/raw directory.

If this is the logic then I'm confused why I would need two arguments to --git-path.

**Comment by 2opremio** [comment]
Sorry it took a while to answer.

> In your example, what prevents the first subdir, --git-path=cluster1, from going into cluster1/raw? It seems like cluster1/raw would be done twice?

because `cluster1` has an `.flux.yaml` file in its parent directory (the search for `.flux.yaml` files doesn't happen with subdirectories).

What exactly makes you think `cluster1/raw` would be _done_ twice? When going through `--git-path=cluster1,cluster1/raw` Flux will work as follows:

1. For `cluster1` it finds `/.flux.yaml` (its upper dir)
2. For `cluster1/raw/` it finds `/cluster1/raw/.flux.yaml`

Now, what `/cluster1/raw/.flux.yaml` and `/.flux.yaml` do depends on their contents. Note that for this example I was suggesting that `/cluster1/raw/.flux.yaml` contained something like:

```
version: 2
recursiveRawUpdated: true
```

indicating that the files should be processed recursively as if no `.flux.yaml` existed

> I've been assuming that flux works this way: flux recursively descends the tree and at each directory it first searches for .flux.yaml in that directory or any parent up to the root of the repo (even searching above the git-path) before taking action on the directory. The first .flux.yaml found on the ascending search is used. Then flux proceeds to the next directory and repeats the search logic. So in this example flux would use .flux.yaml for everything except the cluster1/raw directory.

That's correct.

**Comment by EricHorst** [comment]
@2opremio thanks for continuing the discussion. I clearly need to reset my preconceived notions and grind through the docs again. My understandings are clearly wrong. I appreciate your patience with somebody not intimately familiar with the implementation. Let me try to explain where I am coming from, I usually pride myself on careful comprehension of the docs.

In normal mode Flux doesn't care about directory layout in the repo, it will descend into subdirectories in search of YAMLs and apply them all. So without manifest-generation and a tree like this everything will be applied. (I hope I'm not wrong about this after a year of using Flux.)

cluster1/app1/app.yaml
cluster1/app1/backend/back.yaml
cluster1/app2/app.yaml
cluster1/app2/backend/db/deploy.yaml
cluster1/app2/backend/memcache/deploy.yaml

Now I read the docs about manifest factorization through .flux.yaml. It explains that "flux performs two types of actions on raw manifest files from the Git repository" and continues to say one of those actions is "read manifest files" which can be overridden by a generator, ie "the generators are meant as an alternative to Flux manifest reads." That leads me to conclude that Flux does the same thing in the hierarchy above, it visits every directory and instead of enumerating and reading the YAML files it runs the generator instead.

Following the docs I enable manifest generation by putting .flux.yaml at cluster1/.flux.yaml which says to use `kustomize build .` as the generator. I assumed Flux would visit every directory like before: cluster1/app1/, cluster1/app1/backend/, cluster1/app2/, cluster1/app2/backend/db/, clsuter1/app2/backend/memcache. In each directory it would look for .flux.yaml and not finding it would look in the parent, and not finding it would look in the parent, etc, until it found cluster1/.flux.yaml which says the generator is `kustomize build .` which would be the alternative for manifest reads in that directory. Repeat for next directory. The result would be for each of the five directories `kustomize build .` would be run. Now, as it was visiting directories, if it were to encounter cluster1/app2/backend/db/.flux.yaml that had a different generator specified it would use that rather than looking upward for a generator definition. Basically Flux works just like Flux but different manifest reading behaviour.

Based on what I just described, when you say to use `--git-path=cluster1/, cluster1/raw` I conclude that specifying cluster1/ will send it down that *entire* tree visiting every directory as described above, running the generator in every directory, which would include raw/. Since cluster1/raw is a subtree of the first, I assumed it would then visit that subtree a second time. That's how Flux would normally work, so I assumed that's how it would work with manifest generation.

However, it sounds like I've taken a wrong turn in understanding. It sounds like adding .flux.yaml fundamentally changes how Flux walks the tree which is a bit more involved than just defining an alternative to Flux manifest reads. I need to take what you said above and read the docs harder and construct some tests.

I hope this clarifies how I arrived where I'm at. I've been through the docs many times and I've constructed several tests and each time I think I understand I find it doesn't work like I expect. I'm starting to conclude that either something is very wrong with my comprehension or the docs aren't spelling out the behaviour changes very well. Its seeming more difficult than it should be.

The funny thing is that at the same time as I'm confused, we're also still talking about a feature enhancement and while it turns out I'm off in the weeds, I think the feature enhancement is probably a good idea.

Thanks again.

**Comment by EricHorst** [comment]
@2opremio stand down, I think I've got it now. 

When the manifest generation documentation says "For every flux target path, Flux will look for a .flux.yaml file in the target path and all its parent directories." That means for every path specified in --git-path Flux will look for a .flux.yaml. That does NOT mean Flux looks for .flux.yaml in every directory as it recurses through each directory in the tree under --git-path. So if I have a tree of YAML and I enable manifest generation, create .flux.yaml and provide a generator, then that generator assumes responsibility for generating the entire subtree under the specified git-path, not just the current directory.

Understanding how it works helps. I feel like the docs could have been clearer. I never considered that git-path could take multiple values and that manifest generation takes over per subtree and not per directory. The fact that Flux default behaviour is to apply all YAML in the specified tree and use of examples like "kustomize build ." mislead me as it seems like its going to be doing `kustomize build .` in all the directories of the tree.

With that said, I like the way I *thought* it worked better. The primary reason is that its easier to delegate control of Flux operations to my tenants if behaviour can be customized by the content of the directory tree. It is less convenient to have to add additional git-path arguments to implement something different for the tenant.

Here is also one very important and dangerous gotcha. Say one was using Flux the traditional way along with garbage collection to keep house. Now one wants to introduce manifest generation. As soon as .flux.yaml becomes visible Flux stops walking the tree for YAMLs and runs the generator instead. That makes all the previous YAMLs effectively disappear and the garbage collector springs to action, cleaning out the cluster. Pretty rough transition. The way I *thought* it worked seemed better for that as well, within one git-path the default recursion could still work but the behaviour in any subdirectory/sub-tree could be overridden at any point. That would allow for a mix of raw YAML, generated YAML, etc.

But while I came at it from a complete misunderstanding I think the recursiveRawUpdated option is still useful. I just need to adjust my solution.

**Comment by 2opremio** [comment]
@EricHorst Thanks for not giving up and going through the docs once again.

Yes, for each directory in `--git-path` Flux only looks for a single `.flux.yaml` file. If the file is found Flux doesn't go recursively into the directory, it uses that `.flux.yaml` file once.

As per your suggested behavior, it is more consistent with what Flux does with raw manifests, but I don't think it makes sense to evaluate the `.flux.yaml` file recursively for every subdirectory.

I am sorry the `.flux.yaml` documentation is not clearer. It has been mentioned before (by @stefanprodan no less, who has a deep understanding of Flux, so we do have a problem). I think the reason is that I extracted the documentation from a [design document](https://docs.google.com/document/d/1ebAjaZF84G3RINYvw8ii6dO4-_zO645j8Hb7mvrPKPY/) , which was aimed at being specific and not particularly friendly.

Would you be willing to contribute with a PR improving the documentation? 

(CC @dholbach )

**Comment by squaremo** [comment]
OK, so to summarise, I'm going to pick out some snippets.

> I never considered that git-path could take multiple values and that manifest generation takes over per subtree and not per directory.

I think the interaction of `.flux.yaml` and `--git-path` values  can be elaborated in the documentation. It is a coherent model, but has some subtleties to it that should be made explicit:

 - if a `.flux.yaml` is found for a `--git-path`, it takes over the processing
 - searching in parent directories for `.flux.yaml` means that supplying nested paths to `--git-path` will have no effect

I'll open an issue or PR to address that.

> Here is also one very important and dangerous gotcha. Say one was using Flux the traditional way along with garbage collection to keep house. Now one wants to introduce manifest generation. As soon as .flux.yaml becomes visible Flux stops walking the tree for YAMLs and runs the generator instead. That makes all the previous YAMLs effectively disappear and the garbage collector springs to action, cleaning out the cluster. Pretty rough transition.

It does feel like this is something of a trap; and, more generally, that the current scheme is overly constraining.

However, I cannot think of an effective and backward-compatible fix. In particular, the "Act normal" mode won't work as I implied -- it would need to recursively look for directories with the "carve out" configuration, and even then, I don't think it solves the transition problem above (if you know to exclude directories, you know enough to move them elsewhere). So that may have to be looked at over the longer term.

**Comment by squaremo** [comment]
> the "Act normal" mode won't work as I implied -- it would need to recursively look for directories with the "carve out" configuration, and even then, I don't think it solves the transition problem above (if you know to exclude directories, you know enough to move them elsewhere)

Nope, I've triple-bluffed myself. It _would_ work as described: you could have a top-level `.flux.yaml` providing the default behaviour, then supply a `.flux.yaml` for a path under that, with an "act normal" directive.

Would it solve the rough transition problem? It would still be possible to put a `.flux.yaml` at the top, and forget that it'll take over all processing of subdirectories -- or maybe someone is using just a subdirectory, and you don't know about it. But at least this gives a remedy -- if you want the plain YAMLs, there is a way to get them, that's not disruptive.

**Comment by EricHorst** [comment]
The improved docs in #2634 go a long way in helping to clarify manifest generation and this issue.

To restate and focus this issue, I agree with your assessment, it would be nice to have a top-level .flux.yaml with patch-updated behaviour and a lower level .flux.yaml which provides default recursive yaml file reads.

--manifest-generation --git-path=production/,production/raw/
```
├── base
│   ├── demo-ns.yaml
│   ├── kustomization.yaml
│   ├── podinfo-dep.yaml
│   ├── podinfo-hpa.yaml
│   └── podinfo-svc.yaml
├── .flux.yaml (generation)
├── production
│   ├── flux-patch.yaml
│   ├── kustomization.yaml
│   ├── replicas-patch.yaml
│   └── raw
|       ├── .flux.yaml (act normal)
|       ├── cronjobs.yaml
│       └── anotherthing.yaml
└── staging
    ├── flux-patch.yaml
    └── kustomization.yaml
```

**Comment by kingdonb** [comment]
Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical. There has been a total rewrite, and Flux v2 has a brand new `kustomize-controller` that obviates the boondoggle of `.flux.yaml` through the addition of a new `Kustomization` CRD. While much of this discussion could still apply, the new design is much more flexible and I think there is nothing left for Flux v1 to do here.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, I will go ahead and close out this issue for now.
