### ISSUE TITLE
Docs not completely clear on .flux.yaml policy annotations

### ISSUE THREAD

**Issue by robertgates55** [fluxcd/flux#2553]
I'd like to use .flux.yaml to update all my pods to add a certain annotation.

I've been reading https://docs.fluxcd.io/en/stable/references/fluxyaml-config-files.html#abstracting-out-file-access-generators-and-updaters and can't quite get my head around what I need to be doing.

I'm guessing I need to use a `commandUpdated` with a `policy` `updater`, but what `command` should I be running? Do I need a `generator` if all I'm doing is modifying the manifests that are checked in? Should I be using a `patchUpdated` instead?

I may just be being stupid, but having read that page a few times it's still not obvious to me how these work. Can anyone help?!

**Comment by 2opremio** [comment]
> I'd like to use .flux.yaml to update all my pods to add certain a certain annotation.

Can you please provide a simple, self-contained example with what you are trying to do exactly?

**Comment by robertgates55** [comment]
Sure. My gitops repo (that flux is synchronizing) would contain 2 files:

gitops_repo
> ns.yaml
> ns2.yaml
> .flux.yaml

`ns.yaml`:
```
apiVersion: v1
kind: Namespace
metadata:
  name: demo_namespace_1
```

`ns2.yaml`:
```
apiVersion: v1
kind: Namespace
metadata:
  name: demo_namespace_2
```

Ideally I'd like flux to add the annotation `field.cattle.io/projectId: c-rcrn8:p-4g9vd` to all manifests in the repo before they're applied to the cluster. I don't need this annotation checked back in to the repo though.

Eg `kubectl get ns demo_namespace_1 -o yaml` would give:
```
apiVersion: v1
kind: Namespace
metadata:
  name: demo_namespace_1
  annotations:
    field.cattle.io/projectId: c-rcrn8:p-4g9vd
...
etc
...
```

What `.flux.yaml` settings are required to achieve this?

**Comment by 2opremio** [comment]
Sorry it took a while to answer. I would add a `kustomization.yaml` file and a `.flux.yaml` file like the following:

`kustomization.yaml`
```
resources:
- ns.yaml
- ns2.yaml
commonAnnotations:
  field.cattle.io/projectId: c-rcrn8:p-4g9vd
```

`.flux.yaml`
```
version: 1
patchUpdated:
  generators:
    - command: kustomize build .
  patchFile: flux-patch.yaml
```

The `flux-patch.yaml` file will be automatically created and added to the repo when needed, to store patches added by flux (such as automatic image upgrades and annotation changes). If you are not interested in that functionality you can use the following alternative

`.flux.yaml`
```
version: 1
commandUpdated:
  generators:
    - command: kustomize build .
```

If your repo has a lot of manifests, `kustomize` may not be the best alternative (since you would need to add all of them explicitly in the `resources` section of the `kustomization.yaml` file). As an alternative you can stop using `kustomize` and employ a different command (such as `https://github.com/kislyuk/yq`, but you will need to include the command in the flux image yourself, with an `initContainer` for instance)

**Comment by 2opremio** [comment]
I am closing this since I think I addressed your question. However, please let me know if you need any clarifications
