### ISSUE TITLE
Exec RAW command

### ISSUE THREAD

**Issue by alexandrsemak** [fluxcd/flux#2631]
One of helm chart requiring secret from another namespaces.
is it possible to exec raw kubectl command with flux?
I know that is odd but i am trying automate as much as possible.
Thank you for advance.

**Comment by squaremo** [comment]
It is possible to execute `kubectl` as a command in a `.flux.yaml` file. But to do so, you have to be using a `.flux.yaml` file, which you might not want to do. It's probably better to use a kustomization, or just copy a YAML file over into the namespace where you need it -- re-encrypting it if necessary.

**Comment by squaremo** [comment]
(I'm closing this as answered, so it doesn't show up as new, but you can still comment here if you have further questions)

**Comment by catshout** [comment]
Hi @squaremo we do have a similar challenge. We're running Camel-K and the deployment based on flux. For the creation of yaml files kamel (the CLI of Camel-K) needs to be executed against a k8s cluster.

So far is it possible to run this command

```
kamel run <integrationName> -o yaml
```

inside flux or a kustomization?

**Comment by kingdonb** [comment]
@catshout The Flux project does not shell out to outside processes as a matter of posture for security reasons.

In Flux v1, there is this `.flux.yaml` feature – which we have been advising everyone not to use, as it has been deprecated in Flux v2. Be aware that Flux may run with cluster-admin access to the entire cluster, and one of the design goals of GitOps is for Git to be the single source of truth about what manifest runs in the cluster. So it is antithetical to have another process in the position of potentially gaining access to the cluster-admin, since that process will have free reign to place resources in the cluster regardless of whether they are present in Git.

(More importantly, this sort of unacceptably broadens the attack surface in a way that makes securing it basically intractable, for any CI/CD which potentially takes contributions from untrusted contributors.)

So yeah, you can do it with Flux v1, but we cannot support it: https://fluxcd.io/legacy/flux/references/fluxyaml-config-files/

If you are using Flux v2, the current and supported version, then the recommended approach now is to use CI to run any processes which do manifest generation, and use a credential or permitting system to provide it with write access back to the repository, so it can store the output there (where Flux can apply it as the SSOT, like every other manifest in the repo!)

Hope this helps :)
