### ISSUE TITLE
Have a single document that has a nice list of all annotations.

### ISSUE THREAD

**Issue by jdfalk** [fluxcd/flux#2671]
**Describe the feature**
Just like you want a clear and concise description of the feature, I want a single page where I can see ALL annotations. I don't want to have to grok them out from the examples. I want a place I can point the devs to and say "here's the list, use them appropriately." 

**What would the new user story look like?**
A single doc in the reference section that lists all the annotations. Look at the Istio one for an example of how to do it: https://istio.io/docs/reference/config/annotations 

**Expected behavior**
I can say to new dev on the team, "Hey go to https://docs.fluxcd.io/en/stable/references/annotations.html and that should answer your questions."

This was brought up before in ticket #1178 but wasn't completely fixed. I appreciate examples, but for those of us who need a quick reference sheet it's so much easier to have one page where everything is listed. I would also require that if new annotations are added, it be a pre-submit or some level of merge that they update the docs.

**Comment by 2opremio** [comment]
@jdfalk would you be willing to give it a go?

**Comment by jdfalk** [comment]
Sure. I won't be able to get to it until next week however.

**Comment by 2opremio** [comment]
Great! :tulip: There is no rush

**Comment by kingdonb** [comment]
This issue has gone stale, Flux v1 is now in maintenance mode, and will be superseded by Flux v2 soon... but this document might still be useful even now, especially if it was written in the form of a piece of transitionary documentation.

I can't promise this will get prioritized, but it would absolutely make a lot of sense to have a list of annotations, (maybe even including those that were once used but are already deprecated and removed, from before FluxCD org... as in the Istio example page linked in the issue report.) ... any annotation that serves a function in Flux v1, with a note about what replaces this functionality in Flux v2.

It will not be as straightforward as

| feature | Flux 1 annotation | Flux 2 annotation |
| image automation | `fluxcd.io/automated` | `YYY` |
| garbage collection | `fluxcd.io/garbage-collection` | `ZZZ` |

... as the right-hand column won't generally refer to an Annotation in Flux v2, all of the required functionality is implemented on CRDs in the new APIs, I think generally a new feature corresponds with a given field in the spec, and annotations on downstream manifests are not used anymore (except for kyaml setters / comments that drive image automation controller.)

**Comment by kingdonb** [comment]
I don't think we're aiming to have any more direct comparisons with Flux v1, or call additional attention to Flux v1 if we can avoid it, since the focus is now squarely on delivering Flux v2 to GA here at Flux HQ.

At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

We hope you've been able to upgrade to Flux v2, and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as it remains in maintenance, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
