### ISSUE TITLE
Post Synchronisation Hook

### ISSUE THREAD

**Issue by richardcase** [fluxcd/flux#2696]
**Describe the feature**
I would like the ability to create a post-synchronisation webhook that includes the list of changed resources or any errors (or errors could be a separate hook). 
https://github.com/fluxcd/flux/blob/master/pkg/daemon/sync.go#L80

This would allow me to integrate with external systems that are interested in when a change to a resource has been.  

**Expected behavior**
Configure a post synchronisation webhook to call an endpoint
Add or update resource yaml in a flux monitored repo
Flux synchronises and resources are created or updated with causes the configured post-synchronise webhook to be called with details of the resourses that have changed.

Relates to closed iissue #2465

**Comment by 2opremio** [comment]
The GitOps Engine will likely provide this feature.

**Comment by richardcase** [comment]
> The GitOps Engine will likely provide this feature.

Hopefully. But until that happens it would be good to add hooks

**Comment by boxcee** [comment]
See: https://github.com/fluxcd/flux/issues/3264

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
