### ISSUE TITLE
Automate deployment of helm chart on subchart update

### ISSUE THREAD

**Issue by MrBasset** [fluxcd/flux#2711]
**Describe the feature**
I'm not 100% sure if this is a bug or a feature request. I'm hoping I've just read the documentation wrong, but would be thrilled to learn that this is supported?

I've have a single umbrella chart and Helm Release for the discrete components of our application, with the dependencies being referenced by explicit version number and held in our private repo.  e.g.

```
\parent-chart
   - \chart-name
       - \templates
       - chart.yaml
       - requirements.yaml
       - requirements.lock
       - values.yaml
\release
  - helm-release.yaml
```

Each chart dependency is a custom project, packaged up by our CI as both a versioned helm chart and matching (for the version number) docker image.

The umbrella chart, held in the git repo, then describes the application (environment per branch) at a specific point in time.

For certain environments (dev/test) fluxcd has been configured so that it will automatically update the HR in the git repo if a new docker image is pushed into our container repo. This all works fine.

However, I don't seem to be able to do the same for an update to the helm chart.  I'd like to be able to have flux watch the helm chart repo in the same way the docker repo and trigger a new deployment based on an update to a dependant a subchart with flux updating the requirements.yaml.

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
0. Helm Operator is being used to deploy an umbrella chart
1. Flux has been configured to watch the helm repository for specific tags matching a glob
2. A new release is made to the helm repository of a component matching the annotation
3. Flux updates the requirements.yaml in the git repo
4. Helm Operator triggers a deployment and installs the new sub-chart

**Comment by 2opremio** [comment]
Flux doesn't currently support automatic updates based on Helm Chart versions (only container image versions). It's a feature requested often, but we are not there yet.

**Comment by MrBasset** [comment]
Hi, sorry for slowly getting back to this. Is there a ticket tracking this feature/design, or any detail of what might be required?

My go skills aren't that great, but this is something I may be able to take a look at in a few weeks if I can get my employer to agree (as it's needed on our project).

**Comment by hiddeco** [comment]
This is being tracked in https://github.com/fluxcd/helm-operator/issues/12, although what is being described there does not precisely match what you are describing here.

The state of things is that it is currently being blocked because we do not have a proper place to implement all of this, [more about this here](https://github.com/fluxcd/helm-operator/issues/12#issuecomment-573901600).

For the time being, have you looked into the `helm dependency update` feature the Helm operator does offer using [`--update-chart-deps=true`](https://docs.fluxcd.io/projects/helm-operator/en/latest/references/operator.html)? If you set a semver range in your `Charts.yaml` it should move things forward, [as documented here](https://helm.sh/docs/topics/chart_best_practices/dependencies/).
