### ISSUE TITLE
[FR] Include build number in semver

### ISSUE THREAD

**Issue by stefanfritsch** [fluxcd/flux#2718]
Hi,

for many docker images it is useful to set the version to the version of an upstream server and distinguish between images with build numbers.

E.g. gitlab `12.5.5` would end in an image with version `12.5.5.201` (whether or not the build number resets with each gitlab version depends on the CI config).

It would be really nice if the semver versioning could work with these versions and accept, e.g., `semver:~12`, `semver:~12.5.5` or similar. Right now it simply doesn't work because due to the build number it's not following strict semantic versioning.

Thanks,
Stefan

**Comment by 2opremio** [comment]
Maybe I am missing something, but if the semver is the same, isn't the containing software also the same? Why is the build number relevant for deploying?

This clashes with https://github.com/fluxcd/flux/issues/2729

**Comment by stefanfritsch** [comment]
Sorry this reply took so long.

The problem is that we're running security updates on the remaining software in the image and small changes like that. So R `3.6.2.20200120` might not be identical to `3.6.2.20200113` because e.g. the `libssl` changed.

#2729 asked for a different annotation, `strict-semver`, so it would not conflict with this. 

Another option would be to make semver version specs more explicit. E.g. `semver:*.*.*.*` 

1. This would solve the issue with git-commits containing only numbers in the short-hash being mistaken as a semver
2. The current syntax `semver:*` would then simply be shorthand for `semver:*.*.*`

**Comment by cstaud** [comment]
For me both solutions would do the job.
Just to mention: The [documentation](https://docs.fluxcd.io/en/latest/references/fluxctl.html#semver) is misleading, as this behavior does not align to https://semver.org. Maybe some clarification could save others time...

**Comment by 2opremio** [comment]
Sorry, but I remain unconvinced. I think that `semver` should be ... just semver.

I don't think we should abuse what semantic versioning is (and, to be clear, https://github.com/fluxcd/flux/issues/2729 is more a bug than anything else, the implementation we use should had followed the `semver` spec).

Maybe you don't see it the same way, but in my view if what's shipped in the container image changes, then the software's version should also change.

I understand my statement above may not help with your specific use case but all the other solutions  I can think of are just hacks (you also could use `glob` patterns and release based on image creation time, which I guess is not an option)

One hackish solution using `semver` you could possibly use (I haven't tested it) is including the build information in Semver's [build metadata](https://semver.org/#spec-item-10) and rely on Flux's `semver` lexicographical disambiguation:

https://github.com/fluxcd/flux/blob/d29c752180bbaf41820ff202a3eedb9bb50b0184/pkg/image/image.go#L427-L432


That is, when the Major Minor and Patch versions are the same, Flux will compare the tags lexicographically compare the version strings to see which one is newer (i.e. greater lexicographically)


For instance:

* `1.0.0+build9` will be considered newer than `1.0.0+build1` 
*  But `1.0.0+build9` will be considered newer than  `1.0.0+build10`
* Which can be fixed by adding a fixed number of characters for the build, making `1.0.0+build0010` newer than `1.0.0+build0009`
* But note that `1.0+build0001` will be considered newer than `1.0.0+build0002` so you should be careful about using canonical version tags for this to work

So, you stick to a strict `Major.Minor.Patch+FixedVersionSize` for tagnames this should work (but please double check since I haven't tested it).

**Comment by stefanfritsch** [comment]
I'm not dead set on it being called semver. I just think that there should be a way to apply increasing version numbers even if it's not strictly semver.

I'm also not dead set on the numbers being dot separated. I'd be just as happy with `major.minor.patch+build` or any other solution that allows me to be certain that `1.2.2+4` does not get "updated" by `1.2.1+5` because it's the newer build (due to a security patch) without being ridiculously limited like I'd be with the glob spec.

Let's say you've got an apache container. You're using apache version `2.4.41` and notice a bug in your container that requires a change in the Dockerfile. What would be the canonical solution with flux?

1. Use `glob:2.4.41.*` - that makes flux rather pointless
2. Use `semver:~2.4` and use something that you yourself admit is a hack prone to issues
3. Overwrite image version `2.4.41` for the updated image and lose the ability to fully version your images
4. Introduce `semver:2.4.*.*` (as mentioned I'd be just as happy with `semver:2.4.*+*` or `semver:2.4.*+build*` to stay semver compliant) as a way to slightly deviate from the semver spec without impacting spec conformity unless it's explicitly requested by the user

E.g. my linux kernel is version
```
5.3.0-26-generic
```
There would be no way to get something that replicates the version updates of my distro in flux.

Thanks,
Stefan

**Comment by cstaud** [comment]
> Sorry, but I remain unconvinced. I think that `semver` should be ... just Semver.
Same for me! But as some maintainers wont break anything, even if its actually broken ;-) I try to show ways which don't change an old behavior. 

In my opinion `semver` should do exactly _this_, as the actual implementation is a bug or at least technically incorrect documented.

**Comment by kingdonb** [comment]
This feedback has been taken into account in the rewrite, and Flux v2 has placed increased importance on image tag strings.

https://toolkit.fluxcd.io/guides/sortable-image-tags/ – in the new version of Flux, you can choose Semver and you can choose build number as a sorting methodology. You can use alphabetic or numeric sort for the "sortable part" regex capture group.

Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

If you have a use case for Flux that isn't covered well in the new Flux v2 (which is a total rewrite), we want to hear about it.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/
