### ISSUE TITLE
Rationalise usage messages between `fluxd` and `fluxctl`

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#2795]
`fluxd` has (mostly?) uncapitalised flag help messages, and `fluxctl` subcommands have mostly capitalised help messages. I pick capitalised!

/cc @2opremio

**Comment by kingdonb** [comment]
I was about to close this as I thought it was describing a behavior change, but I've just had a look in the help for fluxctl and I see what you mean. Mostly capitalized! That is a trigger for me and I will fix it (can't help myself now that you pointed it out.)

**Comment by kingdonb** [comment]
Greetings @squaremo ! Please add a review to #3445 at your leisure, if you are interested in this.

I have resolved this issue (#2795) for the next Flux v1 release, 1.22.0 😌 😅 

I have already merged this PR into the omnibus branch where I am tracking the release, [#3442 - the Omnibus PR for 1.22.0](/fluxcd/flux/pull/3442). I have done this so, I hope, we can get one sign-off from maintainers when preparing a release, since they will be small changes that do not contain any substantial behavior differences, it can be short.

Hope that's OK, I will volunteer to do the git surgery if any of the PRs that I've included there don't pass muster. 👍 

The release remains in Draft/WIP state, but it can be an RC soon and merge to master. I have reviewed everything that it has merged up to this point. Because I'm not in the MAINTAINERS, though, even with my newly acquired write access, I think my review will "not count." We can also discuss this at the meeting tomorrow (my morning / ) afternoon for you!

I may add more to the omnibus PR by the end of the week, so you're also welcome to wait longer. We should be able to go quickly through the reviews since they are all linked from via the PR notes in #3442. Thanks for your attention to this!
