### ISSUE TITLE
Leveled logging

### ISSUE THREAD

**Issue by prometherion** [fluxcd/flux#2806]
**Describe the feature**

Actually, filtering logs per level is quite tricky: users that want to get only `error` or `warning` messages have to parse output via _grep_ or any other viable solution, even worse if they want to get messages above a selected threshold (e.g.: just _warn_ and _err_).

Since `flux` is already using the dependency [go-kit](https://github.com/fluxcd/flux/blob/0810999e759bccb31f132bb1c2d3987e18581c39/go.mod#L44) also for [logging](https://github.com/fluxcd/flux/blob/0810999e759bccb31f132bb1c2d3987e18581c39/cmd/fluxd/main.go#L243), would be nice to implement this feature decorating the logger thanks to the `level` [package](https://godoc.org/github.com/go-kit/kit/log/level) of the same dependency.

`level` allows several logging levels according to the [code base](https://github.com/go-kit/kit/blob/master/log/level/level.go#L69-L97) and this feature wouldn't be breaking: further, no needs of test refactoring or a new test suite.

**What would the new user story look like?**

1. providing the new `--verbosity` flag with a default value for getting actual logging expectations in order to don't break backward compatibility or users expecting of getting a full and detailed log, as it is right now.
2. allowed values for `--verbosity` flag would be shadowed to `level` ones since they're reasonable and easy to understand at first glance, so:
   - `allow-debug` to get all the logs (actual situation)
   - `allow-info` to get _info_, _warn_ and _error_ messages
   - `allow-warn` to get _warn_ and _error_ messages
   - `allow-error` to get only _error_ messages
3. refactoring the codebase

**Expected behavior**

Get the ability to get log messages just for a given level without the need for various _grep_ or _jq_ piping in case of JSON format output.

**Comment by alexanderbuhler** [comment]
+1 on this one. We've just integrated with datadog and flux messages are being treated as errors by default. Some flux logs contain `info=` or `err=` so we can map them to a log level, others are missing any clue about level/verbosity, like this one:

```
ts=2020-02-11T12:00:49.890827678Z caller=warming.go:206 component=warmer updated=datadog/agent successful=0 attempted=2
```

**Comment by kingdonb** [comment]
Changes to the log output at this point are being considered as breaking changes, since automation and integration vendors have built many integrated solutions on top of Flux v1 many of which depend on the specific format of logs we have implemented in Flux, and as we are supporting this project in maintenance mode, breaking changes are impossible. Meanwhile, parallel development efforts continue to improve Flux as the new GitOps Toolkit, aka Flux v2, which has now reached the 100% feature parity milestone.

https://toolkit.fluxcd.io/get-started/

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
