### ISSUE TITLE
CD only (no git): patch resources by updating image that matches pattern

### ISSUE THREAD

**Issue by Morriz** [fluxcd/flux#2854]
It would be nice to use flux only for cd of new matching images.

**Comment by hiddeco** [comment]
Given the updates happen _through Git_ this is completely detached from how Flux currently operates.

**Comment by squaremo** [comment]
Driving changes through git is the essential ingredient of Flux, in its present incarnation. Maybe some future factoring of Flux will be able to work in the way you suggest @Morriz, but for now, that's the way it works.

I'm going to close this, but not because I think it's a bad idea -- it's just unlikely to receive attention, as things stand. You may have success with [Keel](https://github.com/keel-hq/keel), which I believe works the way you'd prefer.
