### ISSUE TITLE
Allow Flux specific option for appending custom CA certificates to the Flux container

### ISSUE THREAD

**Issue by zdzielinski** [fluxcd/flux#2873]
Currently I know of no Flux / Helm specific way to accomplish mounting a custom CA certificate into the Flux container. We should be able to provide an option in order to add our own CA certificates without having to go through ConfigMaps or manually editing any of the Flux Pod or Deployment configuration.

The use case for this is to allow secure trust for transactions involving private Docker registries that use TLS. I am currently leveraging the insecure TLS option for Flux, but not every customer will be able to do this.

It is theoretically possible to add an InitContainer or a ConfigMap to do this yourself, but I'd rather not have to manually edit my Flux manifests, there should be an option to do this when installing or upgrading the Flux manifests.

**Comment by 2opremio** [comment]
To clarify, the problem you are having is that Flux's registry scanning (and thus automatic updates) don't work with registries using TLS with a custom CA?

**Comment by Nold360** [comment]
Yea, faced the same issue today & i'm still looking for a way to inject a ca-certificate into flux. I guess  it could be the registry scan. I can supply logs when i'm back at work.

The flux container itself is alpine based, so it should be possible to `apk install ca-certificates`, copy the CA-Cert to `/usr/local/share/ca-certificates/` and run `update-ca-certificates`, right?!

I guess the best way would be to inject the CA-Cert using config(maps), the same way you do with ssh-(host)-keys.

**Comment by techgnosis** [comment]
I'm having this same issue. The registry scanning does not work when using a registry with a custom cert. It just throws x509 errors. 

We really need a way to specify a CA cert when installing so we can trust on-prem registries.

**Comment by kingdonb** [comment]
Custom CA certs are supported in (hopefully, by now?) all places where they can be expected to be used, between git source hosts, APIs for self-hosted and on-premises instances like GitHub and GitLab Enterprise, and image registries, as well as remote webhook providers for alerts and notifications.

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
