### ISSUE TITLE
fluxctl release during full sync

### ISSUE THREAD

**Issue by aackerman** [fluxcd/flux#2881]
**Describe the feature**

I would like `fluxctl release` to interrupt the normal sync loop and be committed and applied immediately instead of the possibly timing out while a full sync for every manifest is in progress.

**What would the new user story look like?**

1. Full sync of all manifests is in progress
2. Script runs a valid `fluxctl release` to update a deployment image
3. Full sync is paused while release happens
4. Release is committed to git repo and the new changes are applied to cluster
5. Full sync is unpaused and continues to completion

**Expected behavior**

When a script executes a valid `fluxctl release` and a full sync of every manifest is in progress the release would take precedence and the full sync would be paused until the release was completed.

**Comment by 2opremio** [comment]
@aackerman why is waiting for the sync inconvenient/not an option?

**Comment by aackerman** [comment]
It's inconvenient because I'm using `fluxctl release` essentially for scripting and it's unreliable when it will get done and whether it will get done within a time limit. 

The question is bound to come to me, "why is it taking so long" and the answer will almost always be, "flux must be in the middle of a full sync 🤷‍♂". I would love to avoid those types of questions and I would be happy to help, but I imagine this might not be an easy to implement feature.

**Comment by kingdonb** [comment]
Thank you for the suggestion! In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

Flux v2 has announced feature parity and we are encouraging users to migrate ahead of 2.0 if possible, so that any surprising use cases can be fleshed out and resolved as early as possible, ahead of "1.0" and/or in advance of a GA release.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

Thanks for using Flux!
