### ISSUE TITLE
Let Flux fetch dynamic codecommit credentials

### ISSUE THREAD

**Issue by T00mm** [fluxcd/flux#2895]
**Describe the feature**
At the moment you need to give Flux GIT credentials to access your repository. With rolling keys this isn't possible. It would be a nice feature to have if you can setup Flux to use the attached instance role. This way you can use Flux with Codecommit without the need of having an IAM users.

**What would the new user story look like?**
1. User defines through a parameter to use the IAM role of an instance, user can also define the cache time of these credentials
2. Flux will use these credentials to execute `[aws codecommit credential-helper get !@](https://docs.aws.amazon.com/cli/latest/reference/codecommit/credential-helper/get.html)` and get a temporary access key.
3. Flux uses these keys to write/read from the codecommit repository.

**Expected behavior**
Flux will be able to completely use codecommit repositories alongside other providers.

**Comment by mattwillsher** [comment]
I figured as flux is calling the git CLI that this could be done directly in a image built off the official flux container.

I created a new container:

```
FROM fluxcd/flux:1.20.0

ARG PY3PIP_VERSION=20.1.1-r0
ARG AWSCLI_VERSION=1.18.55-r0
ARG GITREMOTECODECOMMIT_VERSION=1.13

RUN /sbin/apk add --no-cache py3-pip="$PY3PIP_VERSION" aws-cli="$AWSCLI_VERSION"
RUN pip3 install git-remote-codecommit=="$GITREMOTECODECOMMIT_VERSION"
RUN git config --global credential.helper '!aws codecommit credential-helper $@' \
    && git config --global credential.UseHttpPath true
```

The git repo URL is passed in as a plain CodeCommit HTTPS url. 

Once flux is running, execing into the container and running the following clones the repo:

`git clone --mirror <my-codecommit-repo-url> /tmp/flux-gitclone60635773`

I can see fluxd fork git,  git fork the credential helper, as expected, but the clone fails with a 403.

I _think_ this is due to https://github.com/fluxcd/flux/blob/e3b1876377aad78a021ca69ac9517fac674a97ca/pkg/git/operations.go#L30 - AWS_WEB_IDENTITY_TOKEN_FILE (and maybe AWS_ROLE_ARN) are needed by the `aws codecommit credential-helper` call to actually get the credentials.

**Comment by mattwillsher** [comment]
An additional bit here is that the AWS cli is very heavy and needed the mem & cpu limit increasing to avoid timeouts spawning aws cli. It would be much better if this could be incorporated into the code natively.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
