### ISSUE TITLE
Failed to update manifest automatically without namespace: manifest not found

### ISSUE THREAD

**Issue by hoatle** [fluxcd/flux#2900]
**Describe the bug**

I deployed a helm release without specifying the namespace, so that it will be deployed on the flux default namespace by default. Its deployment was OK, but the auto-update was not.

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions
I set up multi-tenant gitops:
- flux-system namespace with flux  and helm-operator (helm v3) installed
- teracy namespace with flux installed
2. Provide a GitHub repository with Kubernetes manifests
https://github.com/hoatle/teracy-flux-dev/blob/bugs/auto-update/default/hr-teracy-dev-docs-develop.yaml

**Expected behavior**
- With namespace specified on the manifest: auto-update works.
- Without namespace specified on the manifest: auto-update did not work.

It's expected that without specified namespace, auto-update should just work.

**Logs**

ts=2020-03-09T17:51:30.284326883Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-03-09T17:51:30.352851155Z caller=images.go:111 component=sync-loop workload=teracy:helmrelease/teracy-dev-docs-develop container=chart-image repo=hoatle/teracy-dev-docs pattern=glob:develop-* current=hoatle/teracy-dev-docs:develop-8656ff5 info="added update to automation run" new=hoatle/teracy-dev-docs:develop-5f6aabb reason="latest develop-5f6aabb (2020-03-09 16:25:37.982104078 +0000 UTC) > current develop-8656ff5 (2020-03-09 16:07:22.758323065 +0000 UTC)"
ts=2020-03-09T17:51:30.352939997Z caller=loop.go:141 component=sync-loop jobID=3e6df7d3-e585-c8d3-b619-23b2593f83cf state=in-progress
ts=2020-03-09T17:51:30.460550812Z caller=releaser.go:59 component=sync-loop jobID=3e6df7d3-e585-c8d3-b619-23b2593f83cf type=release updates=1
ts=2020-03-09T17:51:30.643203275Z caller=loop.go:151 component=sync-loop jobID=3e6df7d3-e585-c8d3-b619-23b2593f83cf state=done success=false err="applying changes: updating resource teracy:helmrelease/teracy-dev-docs-develop in default/hr-teracy-dev-docs-develop.yaml: manifest not found"

**Additional context**

- Flux version: flux-1.2.0
- Kubernetes version: v1.16.7
- Git provider: github
- Container registry provider: docker hub

**Comment by wmiller112** [comment]
Hitting this as well and can't think of a great workaround. Having to specify a namespace in the manifest makes branch based deployment in a multi-tenant cluster very difficult (ie. single helmrelease being deployed into their own namespace, via their own flux deployments and include-image filter). Would require modifying/creating new helmrelease

**Comment by kingdonb** [comment]
Flux v1 does not have a great multi-tenancy story, and fixing this was a primary goal for Flux v2, which is a total rewrite from scratch.

If you've already followed the Flux v2 Getting Started Guide, you might have found this section at the end: https://toolkit.fluxcd.io/get-started/#multi-cluster-setup

There are guides with specific advice about how to approach multi-cluster or multi-tenancy.

For your requested use case I'm afraid the tendency is towards preferring explicit over implicit configuration, since Flux v2 is not meant to run a separate instance of Flux inside of each user's namespace, there is no concept of a default namespace. So it seems to me that users will need to include a namespace in their manifests.

The link provided no longer resolves to a file so I am not able to see exactly what the file in the original report was like.

Closing. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/
