### ISSUE TITLE
Flux automatic release: it wants to re-release the "old" one

### ISSUE THREAD

**Issue by emas80** [fluxcd/flux#2901]
We have a setup where we re-tag a _specific_ tag of a docker image (that we call `master`) every time we run a certain build.
Basically we take the tag `master` and we retag the image to be `somestring-{timestamp}`.
We end up having a docker image tagged as `master` and as `somestring-{timestamp}`.

Now, it can happen that we run another build, and the tag master did not move from the previous docker image, and we end up having the same docker image, tagged this time with `master`, `somestring-{timestamp}` and `somestring-{timestamp-new}`.

The relative deployment if fully automated, and it is instructed to release `regexp:^somestring-`.
The idea behind it is to automatically release everytime a new tag `somestring-{new-timestamp}` is pushed.

Now, we let's imagine we are into the situation where we have a docker image named `my-application` with the following tags: `master`, `ops-1-20200303112732` and `ops-1-20200309123553`. (the first one is the 3rd of March, the second one is the 9th of March)

Flux applies a yaml like this one - we want to apply the 9th of March:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
     fluxcd.io/automated: "true"
     fluxcd.io/tag.addons-api: regexp:^ops-1-
  name: my-application
spec:
  template:
    spec:
      containers:
      - image: MY-GCR/my-application:ops-1-20200309123553
```
and everything seems correct.
But after a few minutes, during the first run of a job, I see in the logs:

```
ts=2020-03-10T11:07:41.800183359Z caller=images.go:111 component=sync-loop workload=ops-1:deployment/my-application container=my-application repo=MY-GCR/my-application pattern=regexp:^ops-1- current=MY-GCR/my-application:ops-1-20200309123553 info="added update to automation run" new=MY-GCR/my-application/my-application:ops-1-20200303112732 reason="latest ops-1-20200303112732 (2020-01-30 12:08:34.04048594 +0000 UTC) > current ops-1-20200309123553 (2020-01-30 12:08:34.04048594 +0000 UTC)"
```
Basically the image is just ONE, tagged 3 times, but Flux checks the date, and it thinks that the date of the running image (the 9th of March one) is in the past if compared to the date of the image found with another tag starting with `ops-1-` (the 3rd of March one), which is not as it's the same date.

This is not a problem if we had just one workload with this issue (even if I wonder what would happen when it finds the running image to be `ops-1-2020030311273`, the comparison would still find the same date for the images `ops-1-2020030311273` and `ops-1-20200309123553`).
It becomes an issue when we have like 50 manifests with different workloads that Flux wants to update all together and it then tries to git commit but the operation takes too much time and it times out.

Our use case, briefly:
We want to automatically generated a test environment, by providing a list of applications. 
Every time we build an environment, we take the stable version (`master`) and we re-tag it with a unique tag. 
We apply a set of automatically generated yaml with the same unique docker tag.
We want to be able to automatically release a new version of the application from our CI/CD, so we have added the automatic release based on the tag, and when we push a docker image tagged as "envname-XX" then Flux should update the running application.

We would prefer to avoid "forcing" Flux with fluxctl release as it seems more clean that way, but we are going to use that for the time being until a better solution (if any) is discovered. 

I am happy to hear any suggestion on how to achieve the same thing even in a different way.

**To Reproduce**
Tag the same docker image with ops-1-20200303112732 and then with ops-1-20200309123553 (or you can add any tag you like, ideally the same image re-tagged based on the timestamp) and enable the automatic release.
Let Flux apply a yaml stating to use the "latest" one and see Flux trying to auto-release the "oldest" tag.

**Expected behavior**

We would expect Flux not to do anything.

**Logs**
```
ts=2020-03-10T11:07:41.800183359Z caller=images.go:111 component=sync-loop workload=ops-1:deployment/my-application container=my-application repo=MY-GCR/my-application pattern=regexp:^ops-1- current=MY-GCR/my-application:ops-1-20200309123553 info="added update to automation run" new=MY-GCR/my-application/my-application:ops-1-20200303112732 reason="latest ops-1-20200303112732 (2020-01-30 12:08:34.04048594 +0000 UTC) > current ops-1-20200309123553 (2020-01-30 12:08:34.04048594 +0000 UTC)"
```
**Additional context**

- Flux version:  1.18.0
- Git provider: GitHub
- Container registry provider: Google Container Registry

**Comment by emas80** [comment]
Using `fluxctl release` is not optimal because if Flux did not refresh the docker image registry between the time we pushed the docker image and the time we run `fluxctl release`, then the command fails because the docker image is not found by Flux.

Maybe there is a better pattern we can use here?

**Comment by derrickburns** [comment]
I am also having this issue.

**Comment by kingdonb** [comment]
Flux v1 has many limitations and this is a good example. You've provided image tags with timestamps in them, and you want the newest timestamped image to be deployed. But Flux is looking at the image layers' build timestamp and finding not very helpful information that you'd rather it ignore.

Good news! In Flux v2, especially due to the recent development of image registries applying rate limits to pulls, but also generally because image metadata requires a pull, and pulling all the tags in the registry to find out their time stamps, so they can be precisely ordered, is unreliable and unscalable... the developers chose to use a different strategy to automate image updates when they are tagged with a strategy other than semver.

The strategy relies on image tags which are sortable based on a string (calver/alphabetic or numeric) sort order, either the whole image tag or a regex-selected substring from the image tag.

https://toolkit.fluxcd.io/guides/sortable-image-tags/

The strategy is called Sortable Image Tags and it looks exactly like what you've described.

I hope this information is not too late! Please upgrade to Flux v2 and feel free to let us know if there are still gaps in your use case where our solutions or documentation could do better.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
