### ISSUE TITLE
Consider Supporting git-crypt

### ISSUE THREAD

**Issue by ekristen** [fluxcd/flux#2904]
**Describe the feature**

git-crypt is simple and straightforward pgp encryption of files in a git repo.

SOPS while powerful is overly complicated for a small team and git-secret doesn't support diff-ing.

git-crypt is a better version of git-secret with diff support.

**Comment by xUnholy** [comment]
This indeed would be an ideal feature to support - I've been looking into how viable this might be for my own setup.

https://github.com/raspbernetes/k8s-gitops/issues/57

**Comment by ekristen** [comment]
After taking more time to review SOPS and to use it a bunch it is very powerful and useful for teams of any size. It's definitely designed for configuration data and secrets only, while it can handle random data it's not the best. I do find diff-ing is also not ideal, but the fact that you can encrypt with different keys, including KMS makes it worth it in my opinion.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
