### ISSUE TITLE
New error - Sync clones correctly to Flux Pod but does not apply changes

### ISSUE THREAD

**Issue by sccoe** [fluxcd/flux#2910]
C:\Users\sesa82231\Desktop\Ant\SCCoE\Requirements Management\DevOps\Rancher\EKS\Global-Dev>fluxctl sync --k8s-fwd-ns flux
Synchronizing with ssh://git@github.com/sccoe/rancher-sbx.git
Failed to complete sync job (ID "e7d8cc3c-ba1f-42a0-97bb-3dbd048fa7ea")
== Error ==
Error: checking revisions for status: git repo not ready: git repo has been cloned but not yet checked for write access
We don't have a specific help message for the error above.
It would help us remedy this if you log an issue at
    https://github.com/fluxcd/flux/issues
saying what you were doing when you saw this, and quoting the message
at the top.

**Comment by sccoe** [comment]
New development - fluxctl sync --k8s-fwd-ns flux
Synchronizing with ssh://git@github.com/sccoe/rancher-sbx.git
Revision of master to apply is 66284ea
Waiting for 66284ea to be applied ...
Done.

The changes are not being applied on K8s. What is the problem?

**Comment by kingdonb** [comment]
Hi, there is not enough information to reproduce the issue.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
