### ISSUE TITLE
Is there a way I can listen to flux event?

### ISSUE THREAD

**Issue by Zest-nikunj** [fluxcd/flux#2913]
We have a requirement to do "something" when flux sync completes. We will need to trigger a job as soon as flux is done syncing. Is there a way we can capture the event and chain that activity to it?

**Comment by LWJ** [comment]
Take a look at this project: https://github.com/justinbarrick/fluxcloud

**Comment by kingdonb** [comment]
There is now a first-class answer to this in Flux itself, Flux v2 has added the Notification Controller with Provider API:

https://toolkit.fluxcd.io/components/notification/provider/#notifications
https://toolkit.fluxcd.io/guides/notifications/

Hopefully this will meet your needs and you can upgrade with us, to the next major release of Flux which is a total rewrite!

Since the 0.8 release, we are at the Feature Parity milestone, which means that Flux v2 now supports all use cases of Flux v1 at a standard that is at-least-as-good and in most cases hopefully better than before. Flux v1 is in maintenance mode and does not accept any feature requests from now on; if your use cases are not met perfectly by Flux v2, please let us know.

As this issue is not directly related to supporting Flux v1 in maintenance mode, I will close it now. Thanks for using Flux!
