### ISSUE TITLE
Why are images sorted by image name in ascending order?

### ISSUE THREAD

**Issue by karlmuscat** [fluxcd/flux#2931]
If there are multiple images with the same creation date, Flux orders the images names in ascending order.

We use epoch 0 as our image creation date and rely on the tags which are in semver format to release the latest versions. However, due to the sorting being done in ascending order, the latest versions end up at the bottom of the list and never get deployed. 

Why does flux sort dates in descending order and names in ascending order? Is there a way to manipulate this?

**Expected behavior**

I expect that the images are ordered in descending order, same as what is being done for the creation date.

**Logs**

```> fluxctl list-images --k8s-fwd-ns flux
WORKLOAD                    CONTAINER       IMAGE                                        CREATED
deployment/test-deployment  test-container  xxx.dkr.ecr.eu-west-1.amazonaws.com/test/app
                                            '-> 0.0.1                                    01 Jan 70 00:00 UTC
                                                0.0.2                                    01 Jan 70 00:00 UTC
                                                0.0.3                                    01 Jan 70 00:00 UTC
```

**Additional context**

- Flux version: 1.15.0
- Kubernetes version: 1.14
- Git provider: Github
- Container registry provider: ECR

**Comment by squaremo** [comment]
> Why does flux sort dates in descending order and names in ascending order? Is there a way to manipulate this?

It sorts creation date in descending order because without other constraints, this puts the most recently created image first; and it sorts (when the date is the same) lexicographically so there's a stable result.

If you use the annotation `filter.fluxcd.io/test-container: semver:^0.0` then it'll sort by semver of the tag (and also filter out any tag that isn't in that range).

**Comment by karlmuscat** [comment]
Is the sorting only supported by the `semver` filter pattern? What if the images tags have labels, eg, `test-0.0.0` or `0.0.0-test`?

**Comment by kingdonb** [comment]
The modern implementation in Flux v2 has put a great deal of flexibility into the feature, and focuses on string sorting rather than image timestamps, which should make a big difference for your use case.

https://toolkit.fluxcd.io/components/image/imagepolicies/#examples the image policy examples show now how to use a named capture group to create an image with a sorted part, or a semver part. So if you want to build your automation on Flux v2 around some kind of nearly-semver tagging scheme, you will have much better luck with this capability in Flux v2.

I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now. Thanks for using Flux!
