### ISSUE TITLE
Hem Operator Document page not found

### ISSUE THREAD

**Issue by nikhilbalekundargi** [fluxcd/flux#2955]
https://docs.fluxcd.io/projects/helm-operator link does not work. In https://docs.fluxcd.io/en/1.18.0/index.html when I click on helm-operator documentation link its not working.

**Comment by dholbach** [comment]
The link "https://docs.fluxcd.io/projects/helm-operator/" (with added slash at the end) works.

**Comment by dholbach** [comment]
A quick update:
 - This was fixed in `master`: https://github.com/fluxcd/flux/pull/2919/files#diff-1a523bd9fa0dbf998008b37579210e12R41
- We are about to add more rigorous link checking: https://github.com/fluxcd/flux/pull/2948
- The next release will fix the links on https://docs.fluxcd.io/en/stable/
