### ISSUE TITLE
Flux events on "duplicate definition" errors

### ISSUE THREAD

**Issue by kaspernissen** [fluxcd/flux#2960]
**Describe the feature**
We are currently building and extending flux reporting in our https://github.com/lunarway/release-manager project to include reporting from flux. In this, we use `--connect` to receive messages from flux, parse them, and report them back to correct people. This works great for events on apply's, kube validation errors etc. One thing we are missing, would be reporting on the errors that flux see's, e.g. the "duplicate definition" error, which we have seen a couple of times. 

We do have alerting on this specific error, but it would be nice if this was an event on the same lines as the other events generated by flux.

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.

No drastic change to the user story. This is just an addition of the event reporting using `--connect`

**Expected behavior**
We have test cases in our project, where we apply 2 different configs in 2 different directories that flux listens for changes on. The expected output will be a flux event on websocket connected using `--connect`.

**Comment by kingdonb** [comment]
This is a good suggestion and I don't know how well this is handled in Flux v2, though I suspect the answer is "much better"

Duplicate definition is a specific case of failure where the error message quality can make or break your capability to resolve the issue in a timely fashion. I'd like to attach an example of how the error messaging has improved in Flux v2 before closing.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

**Comment by kingdonb** [comment]
There are newer validation routines included in https://github.com/fluxcd/flux2-kustomize-helm-example through the `.github/workflows/test.yaml` action, in `scripts/validate.sh`.

The Flux kustomization also bakes in validation that you can enable through `validation: client` or `validation: server`, as well as built-in validation performed by Kustomize itself, especially in some of the more recent releases of Flux v2 and Kustomize.

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
