### ISSUE TITLE
Flux: skip tls verify

### ISSUE THREAD

**Issue by dzirg44** [fluxcd/flux#2962]
**Describe the bug**

when i try to connect via http proxy to the my kubernetes cluster
```
fluxctl --k8s-fwd-ns=flux list-workloads
```
 i receive an error 
```
proxyconnect tcp: x509: certificate signed by unknown authority
```
but i don't see any options to skip this check.

**Additional context**

- Flux version: 1.14.2
- Kubernetes version: 1.15

**Comment by dzirg44** [comment]
i can add 
`"insecure-skip-tls-verify": true`
into my kubeconfig file, but maybe somebody knows a better solution....

**Comment by gnanderson** [comment]
I am receiving a similar error trying to grab the SSH pubkey with `fluxctl identity --k8s-fwd-ns flux`

    Error: Could not create a dialer: Could not get pod name: Listing pods in kubernetes: Get https://10.152.183.1/api/v1/namespaces/flux/pods?fieldSelector=status.phase%3DRunning&labelSelector=app%3Dflux: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "10.152.183.1")

Adding `insecure-skip-tls-verify` doesn't seem to be an option as a workaround for now:

    Error: Could not create kubernetes client: specifying a root certificates file with the insecure flag is not allowed

Flux: 1.19.0
Kubernetes: 1.17.5

**Comment by dzirg44** [comment]
@gnanderson you can temporary fix it , just remove  `certificate-authority-data` from your kubeconfig, but I agree with you - it isn't a solution.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
