### ISSUE TITLE
Support monitoring of container registry changes without actual deployment

### ISSUE THREAD

**Issue by ntx-ben** [fluxcd/flux#3012]
While waiting for the new gitops-engine initiative, would it be possible to have the best of both worlds between Argocd and fluxcd: use Argocd to manage cluster deployments, and use fluxd to manage monitoring of new docker images only (updating the k8s manifests in a git repo, but not deploying them to a cluster).

Thanks

**Comment by kingdonb** [comment]
In Flux v2, this could be possible now. ImageUpdateAutomation is a separate resource and doesn't (as far as I know) have any dependency on the YAML resources in any path which it automates for, actually being deployed by a Flux Kustomization.

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
