### ISSUE TITLE
Respecting security scans for registry like Harbor

### ISSUE THREAD

**Issue by yogeek** [fluxcd/flux#3020]
**Describe the feature**

Flux could respect security scans of docker registries like Harbor to avoid triggering the deployments for non-secure images.

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
1. User has installed and configured Flux to watch a Docker registry like Harbor (which was itself been configured to do a vulnerability scan on docker images)
3. New commits in git branch happen : the CI pushes a new tag for a docker image
4. The image is pushed into Harbor, Harbor launches a security scan via its configured tool (Clair, Trivy...)
4. Flux detects the new tag but waits for the security scan to be OK 
4.a. if the security scan is ok : Flux continue the workflow (git commit the tag + resources deployment)
4.b if not, Flux does not continue the workflow as the image is not ready to be deployed

**Expected behavior**
Flux will commit in GIT only if the docker tag has successfully passed the security scanner (like Clair or Trivy for Harbor registry)

**Addiotionnal notes**
The question has already been asked in the [slack channel](https://weave-community.slack.com/archives/C4U5ATZ9S/p1587628466416300) and [this answer](https://weave-community.slack.com/archives/C4U5ATZ9S/p1587628972417700) has lead to this demand.

**Comment by circa10a** [comment]
I think it's much more reasonable to scan the newly built image then push the tag if no vulnerabilities detected, but even then, new vulnerabilities would be introduced overtime and flux would constantly have to be aware of scheduled scannings. This would couple the tools too much and isn't a job for flux to manage IMO.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

To my knowledge, there is no similar feature (or feature request) that has been added for Flux v2 at this time. If you are still interested in this requirement, you might consider opening a discussion in the Discussion feature on the fluxcd/flux2 repo, as a feature request, or check out fluxcd/image-automation-controller issue history for any sign that someone is working on this.

I do not see this as a feature currently, I would expect there are other tools you can implement this behavior with such as policy controllers and admission webhooks that might have this handled already.

Of course, even with such a workflow implemented, I can see why you would want this, and why it might be desirable to avoid even sending an image to the cluster for deployment that would be rejected by the admission webhooks.

Please consider reopening this against Flux v2 if you are still interested in seeing it implemented.

Thanks for using Flux!
