### ISSUE TITLE
GetKey requests failing

### ISSUE THREAD

**Issue by bcbrockway** [fluxcd/flux#3025]
Possibly not a bug but we started getting alerts about an ever-increasing count of failed GetKey calls from Prometheus (`flux_cache_request_duration_seconds_count{job="flux",success="false"}`). I turned on logging for memcached (`-vv`) and restarted it; still getting the issue. I saw that the counter incremented after the following log messages so I suspected one of those registries but we have a number of other clusters all accessing the same registries and they don't seem to have issues.

```
flux-apps-7d6c6b7bb6-pww8d flux ts=2020-04-24T10:54:44.635621587Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
flux-apps-memcached-c55955595-flh5x memcached <30 gets registryrepov4|index.docker.io/trustpilot/beat-exporter
flux-apps-memcached-c55955595-flh5x memcached >30 END
flux-apps-memcached-c55955595-flh5x memcached <30 gets registryrepov4|registry.gitlab.com/mintel/portal/portal/master
flux-apps-memcached-c55955595-flh5x memcached >30 sending key registryrepov4|registry.gitlab.com/mintel/portal/portal/master
flux-apps-memcached-c55955595-flh5x memcached >30 END
flux-apps-memcached-c55955595-flh5x memcached <30 gets registryrepov4|gcr.io/cloudsql-docker/gce-proxy
flux-apps-memcached-c55955595-flh5x memcached >30 END
flux-apps-memcached-c55955595-flh5x memcached <30 gets registryrepov4|docker.elastic.co/beats/filebeat
flux-apps-memcached-c55955595-flh5x memcached >30 END
flux-apps-memcached-c55955595-flh5x memcached <30 gets registryrepov4|registry.gitlab.com/mintel/image-service/image-service/master
flux-apps-memcached-c55955595-flh5x memcached >30 sending key registryrepov4|registry.gitlab.com/mintel/image-service/image-service/master
flux-apps-memcached-c55955595-flh5x memcached >30 END
flux-apps-memcached-c55955595-flh5x memcached <30 gets registryrepov4|index.docker.io/banzaicloud/vault-env
flux-apps-memcached-c55955595-flh5x memcached >30 END
```

I've tried restarting flux and setting `--registry-trace=true` but the counter is still increasing and I still can't see anything obvious in the logs. Any ideas how I can troubleshoot this further?

**Additional context**

* Flux version: 1.19.0
* Kubernetes version: 1.14.10-gke.27
* Git provider: GitLab
* Container registry provider: various

**Comment by nabadger** [comment]
Related to https://github.com/fluxcd/flux/issues/3026

**Comment by primeroz** [comment]
I can see that the error rate is increased by 4 every time.

Looking at the memcached logs every 1m when the registry cache loop runs we have no issues, only images from the  `--registry-include-image=registry.gitlab.com/<our-org>/*` are checked and we get no errors.

When the registry cache loop happen at the 5m mark (at the same time of the full sync ) instead, 4 extra images are checked in the memcached 
```
gets registryrepov4|index.docker.io/banzaicloud/vault-env
END
gets registryrepov4|gcr.io/cloudsql-docker/gce-proxy
END
gets registryrepov4|docker.elastic.co/beats/filebeat
END
gets registryrepov4|index.docker.io/trustpilot/beat-exporter
END
```
* Those images are not in memcached ( since their registry does not match the include image whitelisting )
* Those images are part of `automated workloads` in which other containers in the pod are correctly automated and are part of the whitelisted registry

**Comment by kingdonb** [comment]
The most current version of Flux is Flux v2, but this report is also against an older version of Flux v1. Please reopen if you are still seeing this issue, I am closing it for staleness and considering it seems unlikely you are still waiting for a response.

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
