### ISSUE TITLE
`--registry-include-image` making requests for excluded registries

### ISSUE THREAD

**Issue by nabadger** [fluxcd/flux#3026]
**Describe the bug**

I'm not sure if this is a bug, or my mis-understanding of what this feature is meant to provide.

My understanding from the docs is that all requests to image registries matching the value in the flag are skipped.

However, I'm not sure this is working for automated workloads, as we see memcache requests for images outside of our intended registry (we only allow `gitlab/<our-org>.*`)

**To Reproduce**

Add 

```
--registry-include-image gitlab.com/<our-org/
```

---

Automate some workloads. In our case, we have workloads that run multiple containers - some of which will be in the included-registry path, but others upstream (say on dockerhub).

---

Note via memcache debug requests to non `gitlab/<our-org>/` registries, for example:

```
flux-apps-7d6c6b7bb6-pww8d flux ts=2020-04-24T10:54:44.635621587Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
flux-apps-memcached-c55955595-flh5x memcached <30 gets registryrepov4|index.docker.io/trustpilot/beat-exporter
```

**Expected behavior**

Flux makes no requests to registries not matching `--registry-include-image`

----

From looking at the code, it looks like there's 2 flows / use-cases around this...

1 - requests to the k8s cluster-api (where the flag is used), to get image-credentials + registries
2 - requests to `pollForNewAutomatedWorkloadImages` (not sure if it's used here, but this is where we're seeing messages in our logs about dockerhub images, which I wasn't expecting).

**Additional context**

- Flux version: v1.19.0
- Kubernetes version: 1.14
- Git provider: gitlab
- Container registry provider: gitlab/dockerhub/quay

**Comment by kingdonb** [comment]
This issue has gone stale, and is reported against an older release of Flux v1.

I cannot follow up every issue unless there is an active report. Also, please note that Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux! If you are still using Flux v1 and have issues, you're welcome to open them again.
