### ISSUE TITLE
Add repo annotation to flux deploy secret

### ISSUE THREAD

**Issue by marcosnils** [fluxcd/flux#3031]
**Describe the feature**
I'd like to automate the way deploy keys are configured in the VCS and for such purpose I was thinking to create a custom controller that looks for flux secrets and then calls the corresponding platform (Github, Gitlab, etc) to configure the deploy keys in the corresponding application repository. The only limitation I have to implement this is that I couldn't find the repository URL in any of the flux annotations.

My proposal here is to add a `fluxcd.io/repository` annotation to the deploy secret that gets created in the namespace so this controller (and any other feature that requires the repo) can be implemented

Thoughts?

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
1. Users configures a flux controller to watch a repo
2. Some other controller in k8s sees that the deploy key secret has been configured and configures the external VCS repo with the specified key accordingly

**Comment by marcosnils** [comment]
I've managed to do this by changing the flux helm template and taking the repo configuration form there. If this is something that could be interesting for someone else I'm open to contribute it there. 

Since I didn't get any answers, I'll leave this open here in case someone is interested in this approach. I've also coded the flux-gitlab-controller which takes cares of this.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
