### ISSUE TITLE
Reflect only mode cluster state change of unmanaged resources

### ISSUE THREAD

**Issue by blaggacao** [fluxcd/flux#3081]
**Describe the feature**

When an operator produces state changes within a cluster, I still want them to be reflected-only in my cluster state repository.

**What would the new user story look like?**

1. flux daemon introduces a reflect-only mode
2. fuxd informs reflection based on well known labels (`fluxcd.io/reflect=true`)
3. fluxd exibits an opt-in default on mode `--reflect-by-default` (switched off by `fluxcd.io/reflect=false`)
4. Upon appropriate apievents, fluxd commit those changes into it's repository
    - As it doesn't know into which folder,
    - use special meaning folder `reflect-only-state` 
    - use at least namespace-based folder hierarchy
5. Additional repo-side configuration through `.fluxcd.yaml` at root folder can be provided (different folder name, etc.)

**Expected behavior**
The repo keeps being single source of truth for cluster state, commit hooks, such as chat-ops integration transparently push those automatic changes to the relevant audience.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

Many of the concerns you described here may be addressed already in Flux v2.

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
