### ISSUE TITLE
Add registry image in flux_registry_fetch_duration_seconds_count metric

### ISSUE THREAD

**Issue by bzon** [fluxcd/flux#3090]
**Describe the feature**

I want to build an alert from the metric `flux_registry_fetch_duration_seconds_count` and I want to know the actual image that is failing to be fetched.

This can be accomplished by adding a `repo` or `image` label. The tags should not be added to prevent high cardinality in the metric.

**Expected behavior**

With this new metric label, we can build an alert or graphs with the following query:

```
sum(increase(flux_registry_fetch_duration_seconds_count{success="false"}) by (image)
```

**Comment by kingdonb** [comment]
In Flux v2, you can have granular control over image repos and their associated image policies and automations, as well as observability around those events.

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
