### ISSUE TITLE
No deployment at the end of a sync

### ISSUE THREAD

**Issue by sccoe** [fluxcd/flux#3093]
Hi,

I am using a private git repo, I have the repo cloned successfully to the flux pod, but then nothing is deployed. I tested the YAML, it is a simple POD manifest.
apiVersion: v1
kind: Pod
metadata:
  name: test-pd2
  namespace: flux
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container

Here are the Flux pod logs from when I run a sync
ts=2020-05-29T22:54:35.512650602Z caller=loop.go:141 component=sync-loop jobID=39a8db4b-e17a-b7f6-4d00-8d3cfa29235b state=in-progress
ts=2020-05-29T22:54:37.385918562Z caller=loop.go:153 component=sync-loop jobID=39a8db4b-e17a-b7f6-4d00-8d3cfa29235b state=done success=true
ts=2020-05-29T22:54:39.134074569Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@github.schneider-electric.com/CloudArchitecture/us-sbx-down.git branch=master HEAD=47c4fd9e367f8aaf6b808ac9ad16a5167461d5f1
ts=2020-05-29T22:54:39.149891425Z caller=loop.go:107 component=sync-loop err="loading resources from repo: walking \"/tmp/flux-working313896384/namespaces\" for yamels: lstat /tmp/flux-working313896384/namespaces: no such file or directory"

Can anyone offer an idea as to why I don't get a pod deployed?

Thanks

**Comment by kingdonb** [comment]
Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
