### ISSUE TITLE
GitHub Package Registry 500 Internal Server Error

### ISSUE THREAD

**Issue by eerichmond** [fluxcd/flux#3098]
We have been using Flux for a year now and recently moved from AWS ECR to GitHub Packages as our Docker registry. Since we moved we are see the following error during every image sync for a couple of the packages.

```
fetching image metadata for docker.pkg.github.com/{org}/{repo}/{repo}: item not in cache, last error: received unexpected HTTP status: 500 Internal Server Error
```

The [Fluxcd troubleshooting guide](https://docs.fluxcd.io/en/1.17.0/troubleshooting.html#fluxctl-returns-a-500-internal-server-error) suggests that we file an issue.

**Comment by kingdonb** [comment]
In the issue #2516 I think I learned that GitHub Package Registry has fundamental issues that will not be addressed outside of the GHCR solution that followed it. This could have been related to your issue.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.
