### ISSUE TITLE
fluxctl returns error with no reason

### ISSUE THREAD

**Issue by seizadi** [fluxcd/flux#3107]
**Describe the feature**
Display better errors for fluxctl release command when flux returns error:
Error: no changes made in repo

**What would the new user story look like?**

Show cause error like only image tags matching semver:~3.1 are allowed

I was using the the getting started with flux project turned off automation and tried
to use the release command:
❯ fluxctl --k8s-fwd-ns flux release --workload=demo:deployment/podinfo --update-image=stefanprodan/podinfo:3.3.1
Submitting release ...
Error: no changes made in repo
Run 'fluxctl release --help' for usage.

The part about geting help about usage makes it seem like a syntax problem and the log files in flux are not helpful either:
ts=2020-06-03T17:50:27.492408653Z caller=loop.go:141 component=sync-loop jobID=14e43089-31c9-56ac-faf9-445aae30ae94 state=in-progress
ts=2020-06-03T17:50:27.545911394Z caller=releaser.go:59 component=sync-loop jobID=14e43089-31c9-56ac-faf9-445aae30ae94 type=release updates=0
ts=2020-06-03T17:50:27.550206142Z caller=releaser.go:61 component=sync-loop jobID=14e43089-31c9-56ac-faf9-445aae30ae94 type=release exit="no images to update for services given"
ts=2020-06-03T17:50:27.563776984Z caller=loop.go:151 component=sync-loop jobID=14e43089-31c9-56ac-faf9-445aae30ae94 state=done success=false err="no changes made in repo"

The cause of the problem I found, looking at the deployment, is this label:
    fluxcd.io/tag.podinfod: semver:~3.1

Which limits the choices that are valid so following command works:
fluxctl --k8s-fwd-ns flux release --workload=demo:deployment/podinfo --update-image=stefanprodan/podinfo:3.1.4

Once you know how this works you could imagine more failure scenarios like setting:
fluxctl --k8s-fwd-ns flux lock --workload=demo:deployment/podinfo

Now even the release command is locked out and the command returns the same error message:
Error: no changes made in repo

**Expected behavior**
Display proper error that only releases that match ~3.1 are allowed due to 
    fluxcd.io/tag.podinfod: semver:~3.1

**Comment by kingdonb** [comment]
This is a great suggestion, but unfortunately would require architectural changes to implement.

Fortunately the rewrite happened, and now we have Flux v2 at declared feature parity with Flux v1, which means it should provide for every use case at least as good if not better user experience! Please upgrade.

Sync has a limited context and it can only tell that sync has failed. In the rewritten version of Flux, any failure should come with all the information that was provided by the error output upstream. This increased observability for failures and status is a core feature of the redesigned architecture and major release goal of Flux v2.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/
