### ISSUE TITLE
Metrics for kustomize or other errors

### ISSUE THREAD

**Issue by runningman84** [fluxcd/flux#3147]
**Describe the feature**
Right now you cannot monitor if kustomize works with flux. In my cluster I got an error message like this:
```
ts=2020-06-22T11:21:48.016157778Z caller=loop.go:107 component=sync-loop err="loading resources from repo: error executing generator command \"kustomize build .\" from file \"../../.flux.yaml\": exit status 1\nerror output:\nError: no matches for OriginalId helm.fluxcd.io_v1_HelmRelease|external-auth-server|external-auth-server; no matches for CurrentId helm.fluxcd.io_v1_HelmRelease|external-auth-server|external-auth-server; failed to find unique target for patch helm.fluxcd.io_v1_HelmRelease|external-auth-server\n\ngenerated output:\nError: no matches for OriginalId helm.fluxcd.io_v1_HelmRelease|external-auth-server|external-auth-server; no matches for CurrentId helm.fluxcd.io_v1_HelmRelease|external-auth-server|external-auth-server; failed to find unique target for patch helm.fluxcd.io_v1_HelmRelease|external-auth-server\n"
ts=2020-06-22T11:21:48.017898464Z caller=loop.go:133 component=sync-loop event=refreshed url=ssh://git@github.com/xxx/flux-repo-yyy-digital-products.git branch=immediate-deployment HEAD=dbcd4530af95b02472d0fa567cf3de8352a5efbe
```

**What would the new user story look like?**

I can monitor the whole flux sync process using prometheus...

**Expected behavior**
A clear and concise description of what you expect to happen.

Either fail this metrics:
```
flux_daemon_sync_manifests{success="false"} > 0
```
or create some new metric where kustomize or other sync errors are reported...

**Comment by kingdonb** [comment]
Flux v2 has a number of improvements in this direction. Have you seen it / are you able to upgrade?

The v0.8 release marks 100% feature parity with Flux v1, so we are recommending all users to migrate as early as possible in order to help flesh out any remaining breaking changes that could be necessary before GA is declared and 1.0 (well, 2.0) fixes any interface changes in place for a while.

If you cannot migrate and this feature is important for you in Flux v1, we can consider including it. #3302 is a similar request that is in the form of a pull request. If it requires any breaking change, then it cannot be included as Flux v1 is in maintenance mode, but for new metrics I would consider they could be included pretty safely without breaking changes. So then the only question is who does implement this, and as Flux v2 has made great inroads in this direction, I can safely say the Flux core developer team will not be likely to implement this feature. It would have to be a PR from an outside contributor.

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
