### ISSUE TITLE
Make git commit sha information available

### ISSUE THREAD

**Issue by edtan** [fluxcd/flux#3163]
**Describe the feature**
It could be useful to make available the git commit sha that a resource was based off of.  For example, this could be exposed as an annotation on that resource.

My use case is as follows: I have written something that monitors the status of deployments and notifies me when it succeeds or fails - it basically runs the equivalent of `kubectl rollout status`.  My notifications include a link to the resource's manifest file in the repo (e.g. in Github), but because I don't have the commit sha, I just point it to the HEAD of the repo.  This has been working great, but it doesn't work when looking through my old notifications - those links all now point to the HEAD of the repo instead of the original commits.  I could workaround this by pointing to the current commit of the repo instead of HEAD, but if there are many commits to the repo happening around the same time, it may end up pointing to a different commit.

I've also browsed through a few different issues, and these seem related:
* #2173 requests that some metadata is made available in the kubernetes.io/change-cause annotation.  One of the suggestions in that thread is to add the git sha in that annotation.
* #854 and #2221 relate to rollbacks.  In my use case, I have also added logic to my monitoring process so that if a deployment fails, it will look up the previous manifest file and generate a new commit to restore the contents of that file, effectively rolling back the deployment.  If Flux was able to maintain the previous git sha as well (e.g. in a second annotation), it could possibly simplify these rollbacks

**What would the new user story look like?**
1. User commits a new change with commit sha `abc123`.
2. When Flux applies the changes, it adds an annotation to the resource with the commit sha (e.g. `fluxcd.io/abc123`)

**Expected behavior**
The `fluxcd.io/commit-sha` would correspond to the git commit that most recently updated the resource.  For resources defined in `--` multidoc files, they would all have the same `fluxcd.io/commit-sha`.

**Comment by kingdonb** [comment]
This is a very interesting suggestion, and so I hate to close it without any discussion!

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

This is tricky to implement, since Flux will not parse every commit, and some commits might have been written between pushes. While I will not go so far as to suggest this makes it impossible to implement your request, I think it is not likely to be implemented in Flux v1, which is in maintenance mode. You can suggest this as an enhancement in the discussions page of Flux v2, https://github.com/fluxcd/flux2/discussions/

Closing for now. Thanks for using Flux!
