### ISSUE TITLE
manually apply flux patch to a kubernetes cluster

### ISSUE THREAD

**Issue by MichaelKissling** [fluxcd/flux#3168]
Hello

We have a usecase where we want to manually apply a flux patch to a cluster with a different namespace. I know that flux uses kubectl patch, but i have difficulties recreating the kubectl patch command. Currently we use a shell script to apply the patch:

```sh
# we need yq in order to parse the flux-patch.yaml
snap install yq
# replace the namespace of flux-patch.yaml and save the result into a variable
patch=$(yq w -d'*' flux-patch.yaml metadata.namespace my-local-namespace)

# apply the patch
index=0
for i in $(echo $patch | yq r -d'*' - metadata.name)
do
    kubectl patch deployment $i --patch "$(echo $patch | yq r -d$index -)" --namespace=my-local-namespace
    ((index++))
done
```

As you can see, the flux-patch.yaml has to be divided into single documents in order to be applied to the cluster. Is there a simpler way to apply the flux patch without having to parse the deployment name and apply each subdocument separately?

regards
Michael

**Comment by kingdonb** [comment]
I don't understand the question or the origin of `flux-patch.yaml` in this issue report.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
