### ISSUE TITLE
Flux doesnt deploy subchart

### ISSUE THREAD

**Issue by rajivchirania** [fluxcd/flux#3180]
@stefanprodan I also have the same problem where the sub chart doesn't get deployed.

So i have a subchart for prometheus rules and that subchart is defined in requirement of the main chart of the application with values of the subchart also defined in the helm release of the main chart  however the subchart doesnt get deployed.

dependencies:
    - name: alert-rules-subchart
      version: 2.0.0
      repository: file://../alert-rules-subchart
      alias: alertRules

cart-fragment
├── Chart.yaml
├── charts
│   └── alert-rules-subchart-2.0.0.tgz
├── requirements.lock
├── requirements.yaml
└── templates
    ├── _environment_variables.tpl
    ├── _helpers.tpl
    ├── deployment.yaml
    ├── grafana-dashboard.yaml
    ├── service.yaml
    └── virtual-service.yaml

2 directories, 10 files

Please let me know if i am missing something..

**Comment by kingdonb** [comment]
If your full chart and subchart is published somewhere, I can perhaps take a look at it and tell you what is wrong.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

Issue reports can be used for bugs or generally feature requests, but this is more like a support request. A more appropriate venue for support can be selected if this issue is still something that you are struggling with.

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, (and respecting you may have moved on already) I will go ahead and close out this issue for now.
