### ISSUE TITLE
Persistent error when list-images

### ISSUE THREAD

**Issue by graywolf-at-work** [fluxcd/flux#3196]
**Describe the bug**

Every time I do list-images on one of the workloads, I get an error mixed into the output:

```
$ fluxctl list-images --namespace pf --workload=deployment/bar
WORKLOAD            CONTAINER  IMAGE                                                  CREATED
foo:deployment/bar  E0716 13:29:26.248371  403936 portforward.go:385] error copying from local connection to remote stream: read tcp4 127.0.0.1:38797->127.0.0.1:47156: read: connection reset by peer
bar       baz/app/bar
                               '-> 24abb3f383802ad5aa72d8920af4dd50f9cd3cbb           16 Jul 20 10:52 UTC
                                   b51294508de14592503a6b284cccda2c5448364c           16 Jul 20 10:25 UTC
```

However, it happens only for the bar workload. rab one works fine:

```
$ fluxctl list-images --namespace pf --workload=deployment/rab
WORKLOAD            CONTAINER  IMAGE                                                  CREATED
foo:deployment/rab  rab       baz/app/rab
                               '-> 24abb3f383802ad5aa72d8920af4dd50f9cd3cbb           16 Jul 20 10:54 UTC
                                   e9587877f8e0a055abea98fab87bf5e6cd4ea07f           16 Jul 20 10:10 UTC
```

The behavior is same across all our kubernetes clusters. bar errors in all the
clusters, rab works in all the clusters.

**Expected behavior**

No error.

**Logs**

Log of flux does not show any errors.

**Additional context**

- Flux version: server 1.18.0, client 1.19.0
- Kubernetes version: 1.16.8
- Container registry provider: AWS

**Comment by kingdonb** [comment]
That's an extremely bewildering report. Without more information on what makes up bar and rab, I can't possibly trace this down and reproduce it, unfortunately.

I can think of no possible reason why calling `list-images` selecting one deployment would cause a port-forward error and selecting the other deploy would cause no such message.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
