### ISSUE TITLE
Sync command should wait for initialization

### ISSUE THREAD

**Issue by joshuaspence** [fluxcd/flux#3200]
I am using `kind` to create a K8s cluster for development purposes and have a bootstrap script that runs the following commands:

```
helm install ... helm-operator
helm install ... flux
fluxctl --k8s-fwd-ns flux sync
```

The `fluxctl sync` command usually fails with the following error:

```
Error: git repository ssh://git@github.com/joshuaspence/homelab.git is not ready to sync

Full error message: git repo has been cloned but not yet checked for write access
Run 'fluxctl sync --help' for usage.
```

I can just retry the command myself, but it would be useful if `fluxctl sync` had some sort of `--retry` or `--wait` flag that could do this for me.

**Comment by kingdonb** [comment]
`helm upgrade` and `helm install` themselves have a `--wait` command, although that will not guarantee Flux is ready to sync by the time your next script line runs...

In Kubernetes-style reconciliation, it is incredibly common for interconnected services to start in a random order and some of them to simply fail, try again, restart until other services they depend on have started and are able to answer in a ready state.

In Flux v2, there are more interconnected parts and this issue is still present. It is possible for Helm Controller or Kustomize to try synchronizing a manifest from a (git) Source before the Source API is ready with a latest commit from an upstream source.

Though the issue is still present, it is much nicer and the new design encourages breaking things up into smaller pieces so that scaling large collections of manifests does not need to be a bottleneck anymore. You can also set up webhooks so that polling is only used as a fallback in case of lost hook deliveries, and manual synchronizations are mostly not needed anymore; 

Please check out the new Flux v2 at https://toolkit.fluxcd.io

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

Respecting you may have moved on already, I will go ahead and close out this issue for now.
