### ISSUE TITLE
Flux does not start with service accounts 

### ISSUE THREAD

**Issue by linuxbsdfreak** [fluxcd/flux#3203]
**Describe the bug**

Flux does not start after implementing https://itnext.io/restricting-flux-permissions-1f79372c77b5

**To Reproduce**

After adding the following for the flux helm charts

```
rbac:
  create: false
  
serviceAccount:
  create: false
  name: flux-engineering
```

**Expected behavior**

It does not start 

**Logs**

```
k logs -n flux flux-54b5c5944f-666rl 
Flag --git-verify-signatures has been deprecated, changed to --git-verify-signatures-mode, use that instead
ts=2020-07-17T18:03:05.394117532Z caller=main.go:259 version=1.20.0
ts=2020-07-17T18:03:05.394175551Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-07-17T18:03:05.394920931Z caller=main.go:421 err="invalid configuration: no configuration has been provided"
```

**Additional context**   

- Flux version: 1.4.0

- App version: 1.20.0

- Kubernetes version: 1.18.4

-  Git provider: github enterprise

**Comment by swade1987** [comment]
You have to restart the pod manually after you change the service account.

**Comment by linuxbsdfreak** [comment]
@swade1987 as discussed restart of the pod is not necessary, since the resources are created before flux installed via helm . As mentioned I have a single flux for the whole cluster. Do you think I am missing something in the RBAC to be setup for flux to work without giving cluster admin privileges?

**Comment by kingdonb** [comment]
Did you also assign the clusterrole with a clusterrolebinding?

It sounds like you're trying to do this without a clusterrole, that leads me to believe you didn't follow this doc exactly. I will need more information to be able to help you resolve this.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
