### ISSUE TITLE
Kustomize: Istio installation error

### ISSUE THREAD

**Issue by Pradeepadtricon** [fluxcd/flux#3214]
```
├── base
│ ├── kustomization.yaml
│ └── istio.yaml
└── Dev
| └── kustomization.yaml
├── Prod
|── kustomization.yaml
```

This is my Kustomise folder structure, i have kept the istio in base. base.kustomisation yaml has istio.yaml reference.

When i try to build in dev or prod ( kustomise build . ) in locally ,I get the below error

this is giving below error -
webhooks.clientConfig.service ignored in mutation attempt

When i remove the istio.yaml file and run command kustomise build . in local it works fine.
Note: we are applying Kustomize cluster via flux-cd. 

istio.yaml.txt
[istio.yaml.txt](https://github.com/fluxcd/flux/files/4975815/istio.yaml.txt)

**Comment by kingdonb** [comment]
Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
