### ISSUE TITLE
How to notify developer after successfull deployment. Is It Possible.?

### ISSUE THREAD

**Issue by prathapar** [fluxcd/flux#3215]
**Describe the bug**
**How to notifiy a developer after deployment is done.**
**Would like to run Test Automation after successful deployment. in case if there is any issue with updated deployment would like to notify to roll back since it is failed. if it is successful, would like to run all  the Test automation against it.** 

**To Reproduce**
DEveloepr PR is merged. CI happend and new build is available. FluxCD sync and applying the changes.
Deployment is updated successfully. however Developver does not know his changes are applied or not. 
He has to accees the setup manually and need to figure out it.
Steps to reproduce the behaviour:

1. Provide Flux install instructions
2. Provide a GitHub repository with Kubernetes manifests

**Expected behavior**
**Developer should get notification after successful/failure of updated deployment by FluxCD.**

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version: 
1.20.0
- Kubernetes version:
- Git provider:
- Container registry provider:

**Comment by kingdonb** [comment]
The redesigned Flux v2 has got something just for you:

https://toolkit.fluxcd.io/components/notification/controller/

> The Notification Controller is a Kubernetes operator, specialized in handling inbound and outbound events.
>
> The controller handles events coming from external systems (GitHub, GitLab, Bitbucket, Harbor, Jenkins, etc) and notifies the GitOps toolkit controllers about source changes.
> 
> The controller handles events emitted by the GitOps toolkit controllers (source, kustomize, helm) and dispatches them to external systems (Slack, Microsoft Teams, Discord, Rocker) based on event severity and involved objects.

Flux v1 is in maintenance mode and will not receive new feature development anymore. We hope you can upgrade to Flux v2 and see if it meets your use case!

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

I will go ahead and close out this issue for now.
