### ISSUE TITLE
Fails to synchronize HelmRelease files

### ISSUE THREAD

**Issue by devsentient** [fluxcd/flux#3261]
After the initial install of both Flux and HelmOperator, pushing regular deployment yamls to the repo triggers a sync and the resources get deployed. However, HelmRelease resources do not get deployed and do not show up in the HelmOperator logs.

Using `kubectl apply -f` to directly deploy the HelmRelease works.

Any idea what could be the issue?

**Comment by kingdonb** [comment]
Without more repro information to reproduce your issue, I will not be able to tell what has gone wrong.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
