### ISSUE TITLE
Flux - Resource Hooks

### ISSUE THREAD

**Issue by dmourao** [fluxcd/flux#3264]
**Describe the feature**
It would be nice to add Resource Hooks - PreSync & PostSync hooks - to Flux v2. 

Since Flux v2 will not integrate GitOps Engine, it would be nice to have resource hooks in a future release of FluxCD.
Helm provides this hooks for each application but it would be nice to generalize as FluxCD feature to have a uniform way to PreSync / PostSync all applications.

**Expected behavior**
Add the possibility to specify a job to be executed before an application deployment and/or update. For example, create a database or migrate current database schema.

**Comment by mathnogueira** [comment]
Any updates on this?

**Comment by yebyen** [comment]
@kingdonb

**Comment by kingdonb** [comment]
This is the repository for Flux v1, if you meant to file this for `flux2` the right place is probably Discussions/Proposal:

> A feature is too limited for my `<use-case>` | Discussion ([General](https://github.com/fluxcd/flux2/discussions/categories/general))
> I want Flux to be able to do `<x>` | Discussion ([Proposal](https://github.com/fluxcd/flux2/discussions/categories/proposals))

I don't mean to send you away, ...

Since I am more active here and might not read your proposal for a while there, I will respond here... I have some feedback and questions. Is this meant to be a parallel feature to Helm's hooks, such that one can use it without involving Helm? Or are they meant to be used alongside Helm hooks to provide some functionality that Helm does not already have built in?

I am a big fan of Helm's hooks, and have found many uses for them. I understand that Argo provides some resource hooks which unfortunately don't exactly line up with Helm hooks. PostSync is effectively PostReady, so when your application fails to become ready because a migration doesn't run, and it won't run the migration because PostSync isn't reached until the application is ready, you have a chicken and the egg problem. The root issue as I see it here is two different models of hooks that are not a perfect mapping are mapped in a way that is actually destructive to the original intent of the hooks operating.

Helm is very popular and I don't think we want to be in the business of managing a competing/parallel hooks operation. There are some other options available that might meet your needs. Is this something that could possibly be achieved through the use of Health Assessment and Dependency Ordering instead?

https://toolkit.fluxcd.io/components/kustomize/kustomization/#health-assessment

https://toolkit.fluxcd.io/components/kustomize/kustomization/#kustomization-dependencies

Please see if the existing ideas can meet your needs, and if you're not sure how to implement a strategy with these features, open an inquiry. I want to avoid sending you to write a feature proposal that will be rejected because it overlaps significantly with existing features.

If Helm Controller already supports a perfect mapping to Helm hooks (since Helm's implementation is actually used under the hood, there is no imperfect mapping, it is actually doing what Helm does, and it should hopefully align neatly in every way,) and Kustomize Controller already supports an alternative strategy that can be used for same purpose, I think the core maintainers' disposition toward this will be "no, sorry, we already provide enough different ways to achieve the same thing."

**Comment by kingdonb** [comment]
I think I've answered as well as I can, I'm going to close this now. Please feel free to respond again, or open up a new discussion in Flux v2 repository where it will likely get more attention.

As this is not a maintenance issue for Flux v1, I'm closing this one out. Thanks for using Flux!
