### ISSUE TITLE
flux trying to get a tag that never existed.

### ISSUE THREAD

**Issue by VarroReve** [fluxcd/flux#3265]
**Describe the bug**

flux says: "manifest for tag v2 missing in repository sakyavarro/blog" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"

but my question is:  the repository [sakyavarro/blog](https://hub.docker.com/repository/docker/sakyavarro/blog) doesn't have a tag named "v2", wonder where does the "v2" tag coming out.

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions

```
helm upgrade -i flux fluxcd/flux --wait \
--namespace devops \
--set git.url=git@github.com:VarroReve/gitops

helm upgrade -i helm-operator fluxcd/helm-operator --wait \
--namespace devops \
--set git.ssh.secretName=flux-git-deploy \
--set helm.versions=v3
```

2. Provide a GitHub repository with Kubernetes manifests

repository for helmrelease: https://github.com/VarroReve/gitops
repository for my project: https://github.com/VarroReve/drone-demo

**Expected behavior**

when I rebuild and push docker image for an demo project, flux should update the image (this image has an immortal tag: "staging-latest")

but flux keep saying "manifest for tag v2 missing in repository sakyavarro/blog" so flux can't update the image

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

```
ts=2020-08-22T16:04:49.196578418Z caller=warming.go:198 component=warmer info="refreshing image" image=sakyavarro/blog tag_count=5 to_update=3 of_which_refresh=0 of_which_missing=3
ts=2020-08-22T16:04:49.276501095Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/sakyavarro/blog auth={map[]} warn="manifest for tag v2 missing in repository sakyavarro/blog" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-08-22T16:04:49.355992537Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/sakyavarro/blog auth={map[]} warn="manifest for tag v2 missing in repository sakyavarro/blog" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-08-22T16:04:49.418130569Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/sakyavarro/blog auth={map[]} warn="manifest for tag v2 missing in repository sakyavarro/blog" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-08-22T16:04:49.418195351Z caller=warming.go:206 component=warmer updated=sakyavarro/blog successful=0 attempted=3
```

Also these two commands have no outputs:
```
$ fluxctl list-images  --k8s-fwd-ns devops

WORKLOAD  CONTAINER  IMAGE  CREATED
```
```
$ fluxctl list-workloads  --k8s-fwd-ns devops

WORKLOAD  CONTAINER  IMAGE  RELEASE  POLICY
```

**Additional context**

- Flux version: 
- Kubernetes version: 1.17
- Git provider: GitHub
- Container registry provider: Docker Hub

Can somebody help me? I'm new to flux and I'm so confused now

**Comment by kingdonb** [comment]
I hope you were able to figure this out.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
