### ISSUE TITLE
Debugging Documentation or Better Errors

### ISSUE THREAD

**Issue by fearoffish** [fluxcd/flux#3267]
**Describe the feature**
I've become so frustrated trying to figure out why flux gives errors for some things, that I'm at the "throw my toys out of the pram" stage. Debugging flux is a nightmare. Logs say something like:

```
flux-79bc54c54-qrxd2:ts=2020-08-26T16:57:11.112646992Z caller=sync.go:606 method=Sync cmd="kubectl apply -f -" took=282.232808ms err="running kubectl: exit status 1, stderr: error:  │
│ error validating \"STDIN\": error validating data: [ValidationError(Deployment.spec): missing required field \"selector\" in io.k8s.api.apps.v1.DeploymentSpec, ValidationError(Deplo │
│ yment.spec): missing required field \"template\" in io.k8s.api.apps.v1.DeploymentSpec]; if you choose to ignore these errors, turn validation off with --validate=false" output=      │
│ flux-79bc54c54-qrxd2:ts=2020-08-26T16:57:11.113227579Z caller=sync.go:231 component=daemon err="default:deployment/example-deploy: running kubectl: exit status 1, stderr: error: err │
│ or validating \"STDIN\": error validating data: [ValidationError(Deployment.spec): missing required field \"selector\" in io.k8s.api.apps.v1.DeploymentSpec, ValidationError(Deployme │
│ nt.spec): missing required field \"template\" in io.k8s.api.apps.v1.DeploymentSpec]; if you choose to ignore these errors, turn validation off with --validate=false"
```

Okay, so there's a problem generating the manifest somewhere. When I run `kustomize` locally against the same path I gave flux, I get a fully usable manifest with selectors et al. So, it would be nice to see what exactly flux did and/or received to get this error. Why is it saying the selector is empty? No idea. Where can I look to figure this out? Nowhere.

**What would the new user story look like?**

1. An error appears in the log as it currently does
2. I get a debug file on the container, maybe? Somewhere I can go and get more details. Contents may be:
  - Command that ran
  - Output from the command
  - Manifest that was generated

**Comment by fearoffish** [comment]
Update: In this case, I hadn't enabled manifest generation (which explains it, right?!!). I do still think maybe adding some more error logging or output would be useful though. Even if just to help out idiots like me with a pointer or two.

**Comment by kingdonb** [comment]
Thanks for the report, sorry for your frustration.

We know that Flux v1 did not live up to the modern standards for observability, and this was taken into account heavily to develop the next generation of Flux v2, the GitOps Toolkit.

Flux v2 has separated out a number of concerns that were effectively conflated in Flux v1 and made debugging less painful. There is no direct analog to manifest generation in Flux v2, though there are some efforts coming underway to provide additional support for users that depend on this feature in a way that can work with their particular CI configurations, I started a discussion about it in #3433.

There are also some new features like `envsubst` that are more constrained, which some users are able to use to simplify their old manifest generation techniques and provide less cumbersome solutions that provide fewer knobs and overall present less obstacles to providing support.

It sounds like your issue was resolved, and I appreciate you posting about it. Thanks for using Flux. Closing!
