### ISSUE TITLE
ClusterRoleBinding values overwrite each other between separately namespaced flux instances

### ISSUE THREAD

**Issue by Magnitus-** [fluxcd/flux#3268]
**Describe the bug**

If you apply the manifest generated by "fluxctl install" for separate namespaces, the last instance of flux that is booted will have access to the cluster and the others won't.

**To Reproduce**

- Generate the manifests for two separate flux instances on the same cluster as follows:

```
docker run --rm fluxcd/fluxctl:1.20.2 fluxctl install --git-user=ferlab-automation \
                                                      --git-email=automation@ferlab.bio \
                                                      --git-url=git@github.com:Ferlab-Ste-Justine/cqdg-environments.git \
                                                      --git-path=qa \
                                                      --git-branch=master \
                                                      --manifest-generation=true \
                                                      --namespace=flux-cqdg-qa > cqdg-flux.yml
```

```
docker run --rm fluxcd/fluxctl:1.20.2 fluxctl install --git-user=ferlab-automation \
                                                      --git-email=automation@ferlab.bio \
                                                      --git-url=git@github.com:Ferlab-Ste-Justine/clin-environments.git \
                                                      --git-path=qa \
                                                      --git-branch=master \
                                                      --manifest-generation=true \
                                                      --namespace=flux-clin-qa > clin-flux.yml
```

- Kubectl apply the first one
- Kubectl apply the second one
- Run kubectl diff on the first one and you'll see something like this:

```
diff -u -N /tmp/LIVE-457743875/rbac.authorization.k8s.io.v1beta1.ClusterRoleBinding..flux /tmp/MERGED-234095494/rbac.authorization.k8s.io.v1beta1.ClusterRoleBinding..flux
--- /tmp/LIVE-457743875/rbac.authorization.k8s.io.v1beta1.ClusterRoleBinding..flux	2020-08-27 17:06:20.099016423 -0400
+++ /tmp/MERGED-234095494/rbac.authorization.k8s.io.v1beta1.ClusterRoleBinding..flux	2020-08-27 17:06:20.131016635 -0400
@@ -18,4 +18,4 @@
 subjects:
 - kind: ServiceAccount
   name: flux
-  namespace: flux-clin-qa
+  namespace: flux-cqdg-qa
exit status 1
```
And sure enough, run "fluxctl list-workloads --k8s-fwd-ns flux-cqdg-qa" and you will see a blank list (should probably be some kind of error), most likely become flux can't access the api anymore to monitor the cluster.

**Expected behavior**

Put something like "flux-{the namespace}" as the name of the role binding instead of "flux". Or otherwise, document the behavior and add a parameter to "fluxctl install" to change its default value.

Its not the end of the world, I manually changed its names in the generated files, but it will trip people up I think.

If I'm missing something, please let me know :). I feel like this is wrong, but I've just started using Flux this week.

**Comment by wojmaz** [comment]
We evaluate flux and flagger and just been affected by this. Pretty annoying as we have two flux installed by two devs, and they keep to pull the rug from under the other one :-)

**Comment by kingdonb** [comment]
Thanks for reporting this. I understand your frustration and I think this is handled better in Flux v2, which has recently reached the Feature Parity milestone release 0.8.

There are examples for multi-tenancy as well as [multi-cluster configuration](https://github.com/fluxcd/flux2-kustomize-helm-example).

If there is a simple PR that can resolve this without breaking, I will be happy to review it and try to merge it, but I don't think that's possible without breaking. Since Flux v1 is in maintenance mode, the only changes that can be accepted are non-breaking changes. There might be a way to rewrite the helm chart such that it can be opt-in for multi-cluster convenience, since you all seem to have solved it. But in general the disposition has been to keep away from adding more knobs to the `fluxctl install` command, to prefer those things are handled by the chart instead.

And though this isn't strictly a knob, it is a convenience for the multi-cluster use case, I think it's clear where this is going...

With the rewrite in Flux v2, a lot of things that Flux v1 has not quite solved became out of scope, and multi-cluster is top of that list. Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help.

If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

Respecting you may have moved on already, I will go ahead and close out this issue for now.
