### ISSUE TITLE
Flux automation for N-1 build

### ISSUE THREAD

**Issue by cloudengineers** [fluxcd/flux#3270]
Hi All, 
Can you please help me on the below query?
I have 2 environments, 1 is QA and 2nd is a QA(N-1) environment. 
For QA I am using flux in automation mode, whenever we get a new build my flux will always pick up the latest image from the registry and deploy those in my QA environment, but I have an issue with QA(N-1)environment,  is there any way my flux will always pick up (N-1) image from the registry in automation mode and deploy it on my QA(N-1)environment.
Thank you

**Comment by cloudengineers** [comment]
Hi All, any suggestions on this

**Comment by cloudengineers** [comment]
Hi Team, 

Can some one please suggest ?

Thank you

**Comment by kingdonb** [comment]
This is a specialized ask, since Flux fundamentally assumes its job is to deploy the latest build, deploying the next-to-latest build is something out of the ordinary for Flux.

I have some hare-brained ideas about how we could support something like this in Flux v2, but it will almost certainly have to be done outside of the tree as this goes against the grain, and could complicate the design of Flux v2 (and v1) to support like this idea directly as a garden-path use case.

Basically my idea was that you might want to track releases and integrating with Flagger somehow, keep weighted information about when deployment fails, or a canary analysis results in a rollback. Thinking being that there might be something more intelligent that Flux can do when a rollback happens, to leave the system in a less precarious state – the disposition of the team has been consistently in my view, when this type of failure happens, an (human) operator must be paged and they should make a decision about how to proceed.

Have you worked with Flagger before? What you're asking for is similar to the idea of a "manually gated canary" and might already be supported there, if you know how to implement it from the docs.

I'll also link back to #3433 although it is probably not obvious why this is related, it is a consequence of one pathological case of manifest generation that I considered, to support your use case. Can't explain in detail just now, hopefully enough to go on, I am collecting use cases that fit the manifest generation and yours does

Since a CI system that generates a manifest is in position to dictate past Flux about what commit it deploys, (you are not required to use Flux's specific guidance about how to automate images, any dang fool can just write whatever values they want into YAML manifests and Flux will deploy them, that is the default behavior of Flux in read-only mode.)

**Comment by kingdonb** [comment]
Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
