### ISSUE TITLE
Allow --git-readonly to be used together with registry scanning

### ISSUE THREAD

**Issue by Frederik-Baetens** [fluxcd/flux#3272]
**Describe the feature**
I would still like automated image tag updates, without writing back to the repo. I am aware that this makes the repo inconsistent with the cluster, but I value having a clean git history. I know it's not all that 'gitopsy' but I feel like this would be a nice feature for those transitioning to full gitops.

**What would the new user story look like?**
How would the new interaction with Flux look like? E.g.
1. User starts up Flux using the --git-readonly flag
2. User makes a deployment with fluxcd.io/automated: "true" annotations.
3. New versions of an image are pushed to the registry
4. Image updates still happen in the cluster, without writing back to the git repository.

Edit: After using flux for a while, I no longer have a desire for this feature, and agree that forcing users to keep the repo consistent is probably a good approach.

**Comment by kingdonb** [comment]
As you say in your edit, this would not be very gitops.

Flux's contract is to make Git as the single source of truth, and there is no room in the design for anything to come in at apply time and present something else for Flux to apply, besides the contents of the git repo; that would break Flux's contract.

In Flux v2 this is even stronger, where image automation has been separated out into a new controller whose only job is to watch sources and write back the changes to git, in order to keep image tag references fresh according to a policy.

Thanks for the suggestion, and thanks for using Flux! Closing.
