### ISSUE TITLE
Seperate fluxcd.io/ignore for flux and helm operator

### ISSUE THREAD

**Issue by farhank3389** [fluxcd/flux#3277]
I'm not sure where to create this issue as it refers to Flux and helm operator. Please let me know if this is not the right place.

**Describe the feature**
When I am troubleshooting something I use `kubectl edit helmrelease` to change stuff and test. But Flux keeps changing everything back in line with Github, so I add the `fluxcd.io/ignore: "true"` annotation to the helmrelease to stop flux from editing it. But then the helm operator also ignores the manifest and doesn't apply the changes.

I think there should be a way to make flux ignore changes but for the helm operator to continue working on helmreleases (there should also be a seperate annotation which makes helm operator ignore changes too). I'm not sure if there is already a way to do this or an easier way to troubleshoot stuff without having to commit everything to github every time.

**What would the new user story look like?**

1. A user has a problem with a helmrelease
2. The user adds the `fluxcd.io/ignore: "true"` annotation to the helmrelease to allow them to troubleshoot
3. The user makes a temporary change to the helmrelease to see if it fixes the problem
4. Flux does not change the helmrelease back to what it was before. But helm operator does apply the change
5. User fixes the problem and pushes the changes to github after removing the `fluxcd.io/ignore: "true"` annotation

**Comment by kingdonb** [comment]
I think what you're trying to do can be accomplished by adding the `fluxcd.io/ignore: true` annotation inside of the git repo instead of on the cluster.

If flux sees this annotation in git, it stops synchronizing changes. This also means that if an `fluxcd.io/ignore: false` annotation is present on the resource in the cluster (or even if no such annotation is present) then Helm Operator will not see the annotation, and it will go on synchronizing releases.

See fluxcd/helm-operator#450 - this person described the opposite of your mode of use, and they saw the opposite behavior.

Let me know if this doesn't help, I'll be happy to talk it through with you and try to figure out what I'm wrong about if anything.
