### ISSUE TITLE
Question: Why does flux store the high-water mark as a git tag?

### ISSUE THREAD

**Issue by al-the-x** [fluxcd/flux#3284]
Please pardon my ignorance, as I'm just getting acquainted with flux et al from adoption at The Day Job ™️ and ran into the `flux-sync` tag clobbering my local `git pull`, as I have `fetch.prune` and `fetch.pruneTags` enabled (moving a fetched tag causes `fetch` to exit with non-zero unless `--force` is applied, which bombs the `pull`). I've been poking about in the commits and mailing list to understand the WHY behind using a tag in this manner, as it feels quite unusual... in `git`, tags are not meant to be altered, once published, correct? Is there a discussion or other documentation of this decision vs the alternatives?

**Comment by kingdonb** [comment]
Tags are source refs and there is no law that says tags cannot be altered, or even git commits, although some sensibilities should prevail with respect to writing history. It is a rule that **semver tags** should be immutable and ought not be altered once written, that is correct. But not all tags need be immutable, (nor all published git commits for that matter) I understand this may be a point of religious conviction for some folks but I don't agree.

In fact a common pattern is to use tags to designate the working state of an environment, like a `stage` tag or `prod` tag, left as reference for other developers that clone the repo, to know what state is in the production environment. If you keep an environment branch, then you have an awkward semantics of "what does it mean when two environment branches merge with each other" and even worse "what happens if there is a merge conflict" that can be avoided by using a tag to represent environment state instead.

Tags don't really represent history by themselves. They point to a commit somewhere on a branch. It is a reference to a point in time, not a HEAD ref, and perhaps especially valuable, tags do not merge into one another.

This is an FAQ, maybe you found it already since you use the expression high water mark: https://docs.fluxcd.io/en/stable/troubleshooting/#what-is-the-sync-tag-or-why-do-i-see-a-flux-sync-tag-in-my-git-repo

It can be disabled:
https://docs.fluxcd.io/en/1.21.2/faq/#can-i-run-flux-with-readonly-git-access

I suppose the reason why this was chosen is that Flux has as its unique feature which other gitops solutions do not currently match, that it can write changes to the git repository in order to fulfill the job of image update automation. So Flux already "requires" write access to the git repository, and being honest for someone who doesn't know Flux or what it's about, that's probably a stretch request, to allow some piece of automation to write to my git repository. Sounds like a bad decision, right?

Wrong, it is GitOps. It's a very good decision, for reasons you can research and understand, including auditability and security but also others that are out of scope to answer the question at hand. In Flux v2, the default was reversed and writing back to the git repository is no longer part of the default configuration, which is in read-only mode. It was not this way in Flux v1, as you can see. But once you have write access to the repository, why not use it as the place to store the high-water mark?

**Comment by kingdonb** [comment]
I'm happy to engage this discussion further, but also trying to reduce the number of open issues in `fluxcd/flux` which is now in maintenance mode. Hope you will be able to upgrade to Flux v2. Welcome to respond and I'm glad to answer your question.
