### ISSUE TITLE
Enable sync-state annotation marker on non-secret objects

### ISSUE THREAD

**Issue by goober** [fluxcd/flux#3297]
**Describe the feature**
Today we are using flux in `--read-only` mode and `--sync-state=git`. However, we would like to tighten the security further and only using a readonly access-token to the git repository. That could be done by changing the sync-state to `secret`, but we are managing all our secrets through [SealedSecret](https://github.com/bitnami-labs/sealed-secrets) so all secret-objects are managed by the sealed-secret-controller. This will have the consequence that flux can set the sync marker annotation without any problems on the secret object, but it will then be overwritten by the sealed-secret-controller on its next loop.

We are looking for an opportunity to let flux add its sync-marker annotation on the sealed-secret object instead. 

**What would the new user story look like?**
Add a flag or a new sync-state option to specify another object type (other than secret) for flux to add its sync-marker.

E.g. `--sync-state=sealedsecret`

**Expected behavior**
When flux is started with `--sync-state=sealedsecret` and `--k8s-secret-name=flux-secret` it will add the sync-marker annotation to the sealed-secret named flux-secret

**Comment by kingdonb** [comment]
Do you absolutely have to put all secrets in SealedSecret?

This seems like a very specialized use case to meet an elaborate policy requirement that maybe sounds good on paper but in practice falls over or turns out to be impractical. Kubernetes also generates a default token for the Kubernetes default service account in each namespace. Is your sealed secret controller also managing those secrets? (I doubt this...)

Certain objects in modern Kubernetes clusters live under management by some cluster manager or "operator", like the sync-state object that is managed by flux, and they are best left managed by that specific operator or controller who is responsible for creating them and managing their lifecycle, directly.

Flux was not made to sync state in a sealed secret, and since the sync state secret isn't stored in git, I'm not sure what else is gained by making the secret for sync-state also be stored in sealed secret resources. Moreover, Flux v1 is in maintenance mode and new features are generally not being accepted at this point, unless they have a strong necessity or resolve some security issue or critical bug.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
