### ISSUE TITLE
Flux is unable to clone from Gitlab

### ISSUE THREAD

**Issue by dilipk8** [fluxcd/flux#3301]
I have a Kubernetes cluster on AWS. I have flux and gitlab installed. Flux and gitlab are in different namespaces.Gitlab is running as a node port and is behind Nginx ( so it is accessible via a url like - https://aa82ee1b284b0464bb1353bd2fbccdd2-1957414567.ca-central-1.elb.amazonaws.com/gitlab externally)
In the flux logs i see this:
```
ts=2020-09-22T11:48:16.396057979Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-09-22T11:48:16.396109955Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2020-09-22T11:48:42.995779454Z caller=loop.go:101 component=sync-loop err="git repo not ready: git clone --mirror: fatal: Could not read from remote repository., full output:\n Cloning into bare repository '/tmp/flux-gitclone802701812'...\nssh: Could not resolve hostname aa82ee1b284b0464bb1353bd2fbccdd2-1957424567.ca-central-1.elb.amazonaws.com:root: Name does not resolve\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"

```
I have uploaded my public key to Gitlab. And i have my private key.
When i run this - git clone git@aa82ee1b284b0464bb1353bd2fbccdd2-1957424567.ca-central-1.elb.amazonaws.com:root/automation.git, nothing happens. I am able to clone with https.
What could be the reason for this error ?

**Comment by kingdonb** [comment]
It could be most likely a NetworkPolicy blocking the communication between one namespace and another.

I am not sure how AWS provisions clusters by default, but check your cluster for network policies first with `kubectl get netpol --all-namespaces` to see if any network policies are in place that could be blocking communication from one `ns` to another.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
