### ISSUE TITLE
Flux on specific branch deployement.

### ISSUE THREAD

**Issue by prasadambasaveswar** [fluxcd/flux#3308]
Hi Team,

I'm new to this Flux and trying to use deploy using flux to k8s. I have configured the flux and deployed using the flux to k8s and everythig working fine on master branch. But i did changes on my repo and pushed to "feature" branch for testing but the changes are not picking. Every time i have to raise PR and merge to master branch. Is there any way that i can apply the changes from any branch and verify the code changes on k8s using flux.. 

Please provide the steps or links that has worked.

Thanks,
Satya

**Comment by stealthybox** [comment]
Fluxd is installed as a Deployment in the cluster.
It's configured via flags.

Fluxd syncs to 1 path in a git repo on a specific branch.
This defaults to master.

See the config docs to set your own branch:
https://docs.fluxcd.io/en/1.20.2/references/daemon/#setup-and-configuration


It seems like your main use-case is to deploy feature branches to a single, mutable environment.
You'll want to think about your requirements for your development flow, but in your case, modifying the fluxd Deployment to point to a different branch is one way to accomplish this.

**Comment by stealthybox** [comment]
If you'd like to have a single installation of flux syncing multiple branches from one or more repos, you can try out our work towards Flux v2 /w toolkit.fluxcd.io

Please keep in mind that the gitops-toolkit is still in alpha and is undergoing constant iteration.

We hope you are having fun trying out Flux and that it is valuable for you!

**Comment by kingdonb** [comment]
I'll close this report as the behavior of Flux v1 in maintenance mode is fixed and cannot be changed in this way at this time.

The GitOps Toolkit has matured significantly in the past 3 months, and now boasts feature parity at or above the usability of Flux v1 for most use cases. Manifest generation is one feature that currently lacks, as it could not be implemented securely within the design of Flux while still retaining the desired flexibility. I have shared this use case in the past, and I consider that one use for manifest generation is, to have CI consolidating and delivering the latest manifests commit from any arbitrary branch or tag into eg. the "deploy" branch, where a gitops-friendly record of your deployment history is maintained in a way that can be traced and understood in a straightforward, linear manner, showing what deploy was replaced by what next after every upgrade, and in a way that can be understood without resorting to hacks like sort by timestamp.

As it was explained, flux deploys commits from a branch, and in Flux v2, similarly, manifests are deployed from a source, with branch semantics. If you want to deploy "just any commit, the latest from whatever branch" then currently, the design assumes you will have a CI tool that you want to use to build the commit from each branch, and it should remain agnostic about which CI tool. The CI system runs builds in order, and this can lead to some strange semantics around deploy order (like for example, what happens when two concurrent builds are executing and they finish out of order) it is a commonly accepted concession, developers following a trunk based style will often have a dev or staging environment that simply deploys "the latest commit from whatever branch it is."

Follow me in #3433 for updates on this use case and how it can be solved in Flux v2 (or, ostensibly, with Flux v1.)

Hope you are able to upgrade with us to Flux v2!
