### ISSUE TITLE
On Demand Delivery

### ISSUE THREAD

**Issue by arobert-delfingen** [fluxcd/flux#3310]
Hello every one, 

We have about 40 on premise clusters, all hosting a different instance of the same application. 
In our delivery process, we used to schedule the deployment of an update on only one cluster at time, and at an hour of low traffic.
In fact, we are doing something that we can called "On Demand Delivery" (in reference to "Continuous Delivery").
To achieve this with FluxCD & HelmOperator, it would be wonderful if we can :
- Disable automated synchronisation with git repository (by allowing a `--git.pollInterval=-1` for example)
- Disable automated checking for new images in container registry (by allowing a `--registry.automationInterval=-1` for example)
- Manually trigger a synchronisation with git repository (already possible with `fluxctl sync` :) )
- Manually trigger a check for new images in registry (by running a `fluxctl imagesSync` for example)

And the same of the side of HelmOperator : 
- Disable the fetches the upstream of mirrored Git repositories (by allowing `--git-poll-interval=-1` for example)
- Manually notifying the Helm Operator about Git changes (already possible with `curl -XPOST http://localhost:3030/api/v1/sync-git`  :) )

Could this kind of features be interesting for the community ?

**Comment by arobert-delfingen** [comment]
The workarround we plan to use is to shutdown FluxCD & HelmOperator, and only start them the day at the hour we want for a periode of 10 min to achieve the update (by playing with `spec.replicas=0 or 1`). But this seems to be quite dirty.

**Comment by stefanprodan** [comment]
In Flux v2 there is `suspend` property for each Git reconciliation, so you can suspend/resume the delivery without having to scale up/down the controller: https://toolkit.fluxcd.io/components/kustomize/kustomization/#reconciliation

**Comment by kingdonb** [comment]
If you're building any kind of fleet of tenants operation, multi-tenancy is approached and solved in Flux v2. Since you are running Flux v1 in what sounds like a multi-tenant configuration already, we hope that Flux v2 better meets your needs and you can consider upgrading. Since Flux 0.8 was released four days ago, we now believe that all known use cases of Flux v1 are better met by Flux v2, and many people are using it in production already now.

Have you already been able to move to Flux v2 @arobert-delfingen or are you considering it?

**Comment by kingdonb** [comment]
This kind of workflow is particularly clunky in Flux v1, due to issues that are now covered in the Flux v1 FAQ:

[Flux v1 runtime behavior doesn’t scale well](https://fluxcd.io/legacy/flux/faq/#flux-v1-runtime-behavior-doesnt-scale-well)

At this point, Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
