### ISSUE TITLE
Flux v1 is in maintenance mode

### ISSUE THREAD

**Issue by dholbach** [fluxcd/flux#3320]
Flux v1 (and the Helm Operator v1) are in maintenance mode and effectively have been for a while.

This means we

* are focusing all of our attention on [v2](https://toolkit.fluxcd.io) and
* will only be working on Flux (and the Helm Operator v1) for security fixes

If you are considering helping out with maintenance, please talk to us. We want to make this transition work for everyone.

### Why is this important?

We as a community decided we will invest into the future of GitOps by re-architecting our tooling from the ground up, resulting in

* Easier code
* Better observability
* Ease of integrating
* Composability and extensibility

The effort is well-underway and v2 is already on feature-parity in terms of Flux read-only mode and Helm Operator functionality. (And there’s already loads more in terms of functionality that Flux v1 and friends couldn't do, such as multiple repository support, health assessment of the deployed workloads, structured logging, events and alerts.)

Check out the guide on https://toolkit.fluxcd.io/get-started/ to find out how to get started with the GitOps Toolkit.

### Timeline

Please take a look at [the roadmap for Flux v2](https://toolkit.fluxcd.io/roadmap/). Once we have reached feature-parity across all current feature sets (➊ read-only mode, ➋ helm-operator, ➌ write operations), we will continue to support Flux v1 and Helm Operator v1 for 6 more months.

### I need help with an issue now

Flux is still being maintained and supported, it will just take a bit longer until we get around to issues and PRs. Critical bug fixes have our priority, we are going to be hesitant and look very careful at anything that will extend functionality.

First and foremost, you can help by checking out https://docs.fluxcd.io/en/stable/troubleshooting/ and https://docs.fluxcd.io/en/stable/faq/ very closely and asking for help on `#flux` on [CNCF Slack](https://slack.cncf.io) if necessary.

This is a very important transition period for us as a community, and we firmly believe that we'll come out stronger together on the other side. :rocket:

**Comment by benyanke** [comment]
Can this be renamed to "Flux v1 is in maintenance mode"? The title is a bit deceptive as is.

**Comment by staceypotter** [comment]
Can we add Leigh's upcoming talk for the Flux / GOTK Guide walk-through? 

**Upcoming Talk:** 
[GitOps Toolkit Guide Walk-through](https://www.meetup.com/GitOps-Community/events/273640196/)
Join us October 19 (10am PT / 18:00 BST) for to this special walk-through of the GitOps Toolkit! 
Through this talk you'll be able to see how the upcoming Flux v2 and GitOps Toolkit will bring
great improvements to the Flux that you love! Watch or follow along as Leigh Capili shares some
highlights and then goes through Getting Started with GitOps Toolkit.

**Comment by farhank3389** [comment]
Will current enhancment requests be moved to the new repo for v2? Or should we raise a new one?
Thanks

**Comment by dholbach** [comment]
> Will current enhancment requests be moved to the new repo for v2? Or should we raise a new one?

New proposals for v2 are discussed over here: https://github.com/fluxcd/toolkit/discussions

**Comment by jonassteinberg1** [comment]
@dholbach my sense is that effectively teams that are fairly invested in flux will _have_ to upgrade to v2?

**Comment by dholbach** [comment]
> @dholbach my sense is that effectively teams that are fairly invested in flux will _have_ to upgrade to v2?

Correct. At some stage the Flux team simply won't be able to maintain two sets of Flux releases. Flux v2 already offers more functionality and flexibility than Flux v1 did, so there'll be lots of benefits for switching.

We already provide good documentation, but there will be more migration information once Flux gets closer to full feature parity (image updates are still WIP).

So there's a lot of good news here - also: if you made your infrastructure ready for GitOps, most of your work is done and the transition over to v2 won't be a lot of work.

**Comment by fernandocamargoti** [comment]
I understand that FluxCD v1 is in maintenance mode and will only receive bug fixes and so on. But I feel that it's been completely abandoned right now. I've posted a critical issue about the update not working and got no attention. I've looked at the list of issues and seen other people reporting the same problem and none of them got any attention. I decided to use FluxCD v1 because the image update is critical for me and the v2 doesn't have it yet and I intend to upgrade when it does. But I'm fairly disappointed with this "maintenance mode".

**Comment by kingdonb** [comment]
I have been a Flux v1 user for a long time now, on the stable v1 flux which I found many interesting use cases for, and I have now been starting my migration to Flux v2. I am in a position to give extra attention to this migration and supporting the community's efforts to help bring everyone along, and I have found through testing on my own that very few use cases still remain underserved in the new Flux. Existing documentation provides support for important features like eg. [multi tenancy](https://github.com/fluxcd/flux2-multi-tenancy) and [helm releases](https://github.com/fluxcd/flux2-kustomize-helm-example), with now added [image automation](https://toolkit.fluxcd.io/guides/image-update/) and finally [a Flux v1 migration guide](https://toolkit.fluxcd.io/guides/flux-v1-migration/).

Flux v2 Development proceeds rapidly and is rapidly approaching 100% feature parity today. It's getting hard to name a facet of the GitOps machinery that is not already made better by Flux v2 at this point.

@fernandocamargoti I understand your frustration as it has taken me a while to get around to wrapping my head around the new architecture and applying it successfully in ways that I am already used to setting up my deployments. I'm not familiar with the specific issue you mentioned and hope it got attended to.

I've recently completed a comprehensive review of all open PRs in [fluxcd/flux](https://github.com/fluxcd/flux/pull-requests) and if your issue has not seen attention yet, I hope to finish or make substantial progress this week on a further review of every open issue in the Flux v1 git repository issues list. If your PR or issue did not get responded to, I'm sorry about that and would like to help. You can @ me directly from the issue, @kingdonb – I am watching for updates of any kind in fluxcd/flux, helm-operator, and flagger repos. I will see your note and prioritize following up your issue from now.

I am still using Flux v1 in some places and though I have started to put my focus on Flux v2, I am committed to supporting Flux v1 users and keeping the lights on and quality of experience high for everyone, at least until Flux v2 has completed feature parity and goes "v1.0" as stable, or otherwise until transition is declared over and to honor the declared maintenance period.

**Comment by dholbach** [comment]
Thanks a lot @kingdonb ! <3

Everyone who's interested in the Flux 2 migration journey, you can sort of track the general progress in this discussion <https://github.com/fluxcd/flux2/discussions/413>.
