### ISSUE TITLE
Correct typo in the Makefile source code tar.gz 1.21.0.tar.gz causing build to fail

### ISSUE THREAD

**Issue by csou812** [fluxcd/flux#3344]
**Describe the bug**

Might happen not just on Arm64 not sure

building with make on source code 1.21.0.tar.gz 

Error occurs

`
docker build -t docker.io/fluxcd/flux -t docker.io/fluxcd/flux: \
        --build-arg VCS_REF="" \
        --build-arg BUILD_DATE="2020-10-26T00:57:20Z" \
        -f build/docker/flux/Dockerfile.flux ./build/docker/flux
invalid argument "docker.io/fluxcd/flux:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [Makefile:86: build/.flux.done] Error 125
`

**To Reproduce**

Use make to build 

1. Obtain source code tar.gz 1.21.0.tar.gz
2. make for arm64
3. error happens

Expected behavior

Build to complete successfully

**Logs**

**Additional context**

**Solution to fix**

Fix typo in the MakeFile
`
build/.%.done: docker/Dockerfile.%
        mkdir -p ./build/docker/$*
        cp $^ ./build/docker/$*/
        $(SUDO) docker build -t docker.io/fluxcd/$* -t docker.io/fluxcd/$*:$(IMAGE_TAG) \
                --build-arg VCS_REF="$(VCS_REF)" \
                --build-arg BUILD_DATE="$(BUILD_DATE)" \
                -f build/docker/$*/Dockerfile.$* ./build/docker/$*
        touch $@
`

Remove the : causing the failure in the line below
From this
`
 $(SUDO) docker build -t docker.io/fluxcd/$* -t docker.io/fluxcd/$*:$(IMAGE_TAG) \ 
'

To this:
`
 $(SUDO) docker build -t docker.io/fluxcd/$* -t docker.io/fluxcd/$*$(IMAGE_TAG) \

`

**Comment by kingdonb** [comment]
I don't think the suggested fix is correct, the colon should separate the string `docker.io/fluxcd/flux` from the image tag.

It looks like you may have encountered an error because the build is meant to run in a clone (not in the bare source copy provided by extracting a zip.) Thank you for providing enough detail in your report to make it clearer what has gone wrong.

A script ./docker/image-tag is supposed to read commit information from your checkout and tag the image appropriately depending on whether you have (1) an unmodified checkout/clone of the source at a particular commit, (2) a modified checkout (WIP) at a particular commit, or (3) an unmodified checkout of a commit which has been tagged for a release.

If the directory `.git` is not present, the script fails and empty output is apparently captured there, when Make continues as if everything is fine, ...until it reaches the place where you found Docker has errored out, since the tag cannot be empty.

You can short-circuit the image tag script and build without a `.git` directory from your zip copy, by passing in `IMAGE_TAG` as an environment variable at build time, pre-empting the script that failed.

Try this instead:
```
make IMAGE_TAG=armhf-canary
```

(Closing)
