### ISSUE TITLE
Docker CIS benchmarking for Flux container image

### ISSUE THREAD

**Issue by infa-ssaurabh** [fluxcd/flux#3370]
When flux image is scanned for Docker CIS benchmarking, it reports below levels:
1. CIS-DI-0009: Use COPY instead of ADD in Dockerfile(Critical)
2. CIS-DI-0001: Create a user for the container(Warning)

Can we fix these in upcoming release?

**Comment by kingdonb** [comment]
I am not sure about the use of COPY instead of ADD, thank you for this information. I will look it up and try to understand why this is marked Critical.

As for running the container as a non-root user, I think this was complicated and deferred due to the planned re-architecture and rewrite. It is unlikely to change in Flux v1, as it would break too many use cases and breaking changes are not accepted into Flux v1. The good news is, Flux 2 has taken heed of this and the controllers in Flux 2 no longer run with the root user.

**Comment by yebyen** [comment]
https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#cis-di-0009

CIS-DI-0009 is about a risk that you will insecurely include files from the internet, because ADD can have a remote source and COPY only works with local sources.

```
# Add git hosts to known hosts file so we can use
# StrickHostKeyChecking with git+ssh
ADD ./known_hosts.sh /home/flux/known_hosts.sh
```
This is the line that I think triggered the warning.

In known_hosts.sh, when this script is run, network access are actually happening (to retrieve and validate `hosts` public keys)

While this would not be prevented by using COPY instead of ADD and it would make the scan result clear its warning, I don't think there's any risk here and the warned-about network access is real. Validation checks are run against a stored, known good copy of the scanned hosts public keys. This is perfectly OK.

As for creating a user for the container, it is known that Flux v1 has as vulnerability the fact of running as root. This is not easily fixable, and it is addressed by Flux v2 as mentioned earlier.

I do not think either of these warnings should need to be addressed in Flux v1. There is already a better story regarding both of these issues in Flux v2.
