### ISSUE TITLE
Why does Flux list CRDs outside of a deploy?

### ISSUE THREAD

**Issue by roy-work** [fluxcd/flux#3380]
(This is just a question about how flux operates.)

Occaisonally, we'll see errors like,
```
pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1beta1.CustomResourceDefinition: Get https://10.100.128.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?limit=500&resourceVersion=0: dial tcp 10.100.128.1:443: connect: connection refused
```

This is outside of any deployment / push to our git repository. Why is Flux attempting to list CRDs?

(Note: I'm not worried about the _error_, per se; that just seems to be that our API server was having availability issues. The question is not "why did this fail?", but rather, "why is Flux making this query?")

**Expected behavior:** I don't expect Flux to be doing anything when it isn't acting on a new git commit / updating k8s resources to match what is in git.

**Additional context**

- Flux version: 1.20.0
- Kubernetes version: 1.16.?
- Git provider: GitHub
- Container registry provider: ACR

**Comment by kingdonb** [comment]
It's hard for me to see the answer at once, https://github.com/kubernetes/client-go/blob/9927afa2880713c4332723b7f0865adee5e63a7b/tools/cache/reflector.go#L105

This is the line where the error was raised out of, where `GetNameFromCallsite` is called out of `k8s.io/apimachinery/pkg/util/naming`, and the result is passed through `NewNamedReflector`, I'm not adept enough at Go to know how to trace from Flux v1 code through the client-go package and understand exactly which ways there are to wind up at this line.

In general I can speculate that Flux is calling into the reflection API in order to determine what resource APIs are present on the cluster, that can potentially be accessed for management.

If anyone has a better idea how this happens, I'm interested to hear how you found out, or learn more about Flux myself too!

**Comment by kingdonb** [comment]
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!
