### ISSUE TITLE
Flux deploying old releases

### ISSUE THREAD

**Issue by moka88** [fluxcd/flux#3404]
**Describe the bug**

I have a flux repository with multiple folders denoting environments. When I deploy flux, and use the --set git.path=dev \ parameter which points to the dev directory which currently contains no files, what I expect to happen is flux will not deploy anything but what actually happens is it will start deploying older releases that used to be on the cluster. Flux sync is also timing out. Does flux/k8s cache older releases? If so, where does it store this cache? Can it be removed? I have no idea where Flux is getting the instruction to deploy these releases.

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions
2. Provide a GitHub repository with Kubernetes manifests

**Expected behavior**

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

**Additional context**

- Flux version:
- Kubernetes version: 1.17.11
- Git provider: Azure DevOps
- Container registry provider: ACR

**Comment by kingdonb** [comment]
Flux caches some information in memcached, related only to image tags observed from scanning image repositories.

Flux v1 stores a clone and checkout of git in ephemeral storage inside of the "flux" pod, it also stores a "high-water-mark" in the flux-sync tag, or a tag that you can rename, inside of the git repository. You can check the flux logs to see what revision it synced and what it is applying from, this will depend on the specific configuration of Flux.

There is no persistent caching of git, and you should be able to clear any temporary cache by deleting the flux pod so that deployment/flux automatically recreates it.

**Comment by kingdonb** [comment]
It will be difficult to reproduce the issue without clearer steps and an example repo that triggers the issue.

Without adding some more of the requested details from the issue template, I cannot help solve this issue. Please post more information or if possible perhaps you can let us know if the issue was resolved within the interceding time.

Closing for now, with not enough information to reproduce.
