### ISSUE TITLE
gitrepository error: reference delta not found

### ISSUE THREAD

**Issue by harshadhulipala5** [fluxcd/flux#3431]
```
flux create source git samplerepo --url=https://git-codecommit.ap-southeast-2.amazonaws
.com/v1/repos/helmrelease- --branch=master --namespace=operations --interval=1m --secret-ref=code-commit-secret
✔ authentication configured
✚ generating GitRepository source
► applying GitRepository source
✔ GitRepository source created
◎ waiting for GitRepository source reconciliation
✗ unable to clone 'https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/maas-helmrelease', error: reference delta not found
```

**Comment by harshadhulipala5** [comment]
not sure why i'm unable to clone the repo

**Comment by kingdonb** [comment]
This is the Flux v1 repository. Since your report is about Flux v2, and I don't know the answer, but there is a discussion I can point you to I found about AWS Codecommit on the fluxcd/flux2 repo: https://github.com/fluxcd/flux2/discussions/808

If there are special steps needed for AWS Codecommit to work with Flux, they are not yet documented. You may be the first AWS user on Codecommit to have reported this issue who has actually tried and had an error message to report a problem.

Please file this as an issue on [fluxcd/flux2](/fluxcd/flux2/issues) (I unfortunately not empowered to move it for you, or I would just do that now). You can also try following up with the discussion linked above, or open up another discussion in [fluxcd/flux2 under Q&A](https://github.com/fluxcd/flux2/discussions/categories/q-a).

**Comment by kingdonb** [comment]
Closing as apparently misfiled. Thank you for your report, please do refile this under `fluxcd/flux2`. And thanks for using Flux!
