### ISSUE TITLE
Unable to get fish (v3.1.2) completions to work (WSL Ubuntu)

### ISSUE THREAD

**Issue by tvories** [fluxcd/flux#3434]
**Describe the bug**

According to the command `flux completion fish`, I should be able to enable fish completions by

non-permanent on-demand: `. <(flux completion fish)`

or permanently: `flux completion fish > ~/.config/fish/completions/flux`

Neither option is working.  When I run the on-demand completion, I get an error:

```
. <(flux completion fish)
fish: Invalid redirection target:
. <(flux completion fish)
```

I don't get any errors when adding the flux completions to `~/.config/fish/completions`, but it also does not work.

**To Reproduce**

Steps to reproduce the behaviour:

flux installed via homebrew and curl (same result either way)

With fish v3.1.2: `. <(flux completion fish)`

**Expected behavior**

I expect completions to work similarly to bash completions: using bash: `. <(flux completion bash)`

**Additional context**

- Flux version: 0.8.2
- OS: WSL Ubuntu 18.04.5 LTS

**Comment by kingdonb** [comment]
Greetings, the `flux` binary is for [fluxcd/flux2](/fluxcd/flux2)

So this issue is apparently misfiled, (I would help you if I could, but I don't use fish, and this is the Flux v1 maintenance repository.)

I don't see [any issue report open there](https://github.com/fluxcd/flux2/issues?q=is%3Aissue+is%3Aopen+fish) about fish completion on the Flux v2 repo, if you are still experiencing this issue please report it there.
