### ISSUE TITLE
Source controller needs to be more verbose about errors from invalid manifests

### ISSUE THREAD

**Issue by juliohm1978** [fluxcd/flux#3441]
**Describe the bug**

Not so much of a bug, but I feel this is a necessary feature.

Currently, the source controller fails with absolute silence when the GitRepository contains invalid Yaml manifests. Syntax erros and misplaced files are quite common, and the controller fails to indicate what exactly is wrong when the reconciliation process does not go through.

I lost a few good hours trying to understand why my HelmRelease was not being synced. Turns out, there was nothing wrong with it, and a syntax error in another manifest in the root directory of my git repo was preventing the controller from reaching it.

There are no errors, no warnings, nothing. Even using the `--log-level=debug` parameter, the controller does not show anything relevant.

**To Reproduce**

1. Create git repo source with valid manifests.
2. Watch the source controller fetch and reconcile successfully.
3. Commit an **invalid** Yaml manifest called `001.yaml`.
4. Watch the controller fetch the new commit and silently stop the reconciliation.
5. Commit a new **valid** manifest called `002.yaml`.
6. Watch the controller fetch the new commit and silently stop the reconciliation before reaching `002.yaml`.

**Expected behavior**

At minimum, the controller should be spitting out error messages indicating which manifest file caused the reconciliation to stop, and details about the error.

Arguably, it should also continue processing all other manifests.

**Additional context**

- Flux version: 0.9.1
- Kubernetes version: 1.20.4
- Git provider: Gitlab.com

**Comment by yebyen** [comment]
I don't think the error you're looking for would have been in source controller because it isn't parsing the manifests, it is just making the source available to Kustomization.

Run `flux get kustomization` to see if your source is applied or not. The fact that there are multiple different places where something could have gone wrong is something we need to handle better. I'm not sure how. Possibly through log aggregation from all relevant controllers, or possibly through a UI that bubbles the errors up to the top so you don't have to do as much probing to find out what is wrong when something fails.

(PS, this is the repo for Flux v1 - this probably should go on the Flux2 discussion board.)

**Comment by juliohm1978** [comment]
You are absolutely right. The kustomize controller does show the exact error.

```
{"level":"error","ts":"2021-03-09T03:40:34.767Z","logger":"controller.kustomization","msg":"Reconciliation failed after 22.969919ms, next try in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"flux-system","namespace":"flux-system","revision":"master/8ee2da79efd5fbba7d8e8b70fb08054985ed2ebe","error":"kustomize create failed: failed to decode Kubernetes YAML from /tmp/flux-system559510108/asdf.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}"}
```

Thank you for clarifying!

**Comment by kingdonb** [comment]
There were logging accessibility enhancements in Flux v2 0.10.0 which may have made this case easier to diagnose. 👍
