### ISSUE TITLE
Multiple tags flux-write-check

### ISSUE THREAD

**Issue by gerardgorrion** [fluxcd/flux#3444]
**Describe the bug**

We are using a flux into 4 clusters of kubernetes: dev. stage 1, stage 2 and pro. Also, repo is configured into jenkins CI pipeline, and his last pipeline commit show these 4 tags into our bitbucket repo (a tag to every environment). 

The problem was the last manual commit was tagged with 4 tags like: _flux-write-check-983462b._ Now we have last commit made by CI tagged as cluster env and last manually commit tagged with 4 errors, both same time.

When flux create these write check tags and why have 2 differents commits with 4 and 4 different tags? Can we delete it?

Thanks,

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions

```
    export GPASS="<OUR_GIT_PASS>"

    fluxctl install \
    --git-user=user \
    --git-email=email@domain.com \
    --git-url=https://user:$GPASS@bitbucketrepo/ourrepo.git \
    --git-path=path \
    --git-label=flux-dev \
    --namespace=flux | kubectl apply -f -
```

2. Provide a GitHub repository with Kubernetes manifests

Kubernetes EKS 1.15
Bitbucket

**Expected behavior**

Have only 4 tags into last commit, regardless of whether it was manual or by CI pipeline.

**Additional context**

- Flux version:  1.20.1
- Kubernetes version: 1.15.12
- Git provider: bitbucket
- Jenkins version : 2.249.1

**Comment by kingdonb** [comment]
Might be duplicate of #3424, #3075 - please take a look at these recent issues that resemble your question and see if they have the answers

Yes, the extra write check tags are perfectly safe to delete. If you are having any problem caused by this please restate, I wasn't clear. Sometimes the extra duplicated random tags can be written because a timeout is reached, you can resolve this by increasing the timeout (or usually also by slimming down your repository.)

**Comment by gerardgorrion** [comment]
Thanks a lot, now we understand what happens. I will close the issue.
