### ISSUE TITLE
Bump to gnutls 3.6.15-r1 or later in docker build and base image

### ISSUE THREAD

**Issue by bleech1** [fluxcd/flux#3453]
**Describe the bug**
There is a security vulnerability in the `gnutls` library that has been resolved in the 3.6.15-r1 release.  `gnutls` is used in the alpine base image as well as the [flux dockerfile](https://github.com/fluxcd/flux/blob/21debdeec3012371937348b12434543b196925aa/docker/Dockerfile.flux#L5).  The issue was reported to alpine [here](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12543) and was resolved [before the 3.12.5 release](https://gitlab.alpinelinux.org/alpine/aports/-/commits/3.12-stable) was created.

**Expected behavior**

We should be using reducing security vulnerabilities as much as possible, including bumping to newer versions of packages and newer versions of base images when possible.  We should bump the apline image constraint in the dockerfile to 3.12.5 as well as the version constraint for `gnutls` to `>3.6.15-r1`.

**Additional context**

- Flux version: 1.22.0
- Kubernetes version:
- Git provider:
- Container registry provider:

**Comment by kingdonb** [comment]
There is no PR which addresses this specifically, because the upstream is lazily referred to as `alpine:3.12` in `Dockerfile.flux`, we just have to trigger CI again to build an image from the fresh upstream, and roll a new release from this.

```
docker pull fluxcd/flux-prerelease:master-ea7736c5
```

I scanned the latest image that was generated by merging #3452 with `snyk` locally and it appears to have resolved this. I can push a new release shortly, so you can upgrade your production systems and mitigate the CVE.

Thanks again for contributing this notice

**Comment by kingdonb** [comment]
The 1.22.1 release is out, the chart update is forthcoming.

This issue will close when #3456 is merged and the chart update comes out.

**Comment by bleech1** [comment]
Thanks for such a quick response.  I just tested the 1.22.1 release and our scanning infrastructure marked the vulnerabilities mentioned in this ticket as resolved.
