### ISSUE TITLE
Update kustomize to v3.8.7

### ISSUE THREAD

**Issue by ahached** [fluxcd/flux#3457]
Currently Flux v1 is using kustomize v.3.8.4.
It would be nice to upgrade the kustomize to at least v3.8.5 or above to leverage the var ref in deployment template annotations.
https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v3.8.5/api/konfig/builtinpluginconsts/varreference.go

**Comment by kingdonb** [comment]
Hi! Thanks for the suggestion!

Flux v1 is currently in maintenance mode, I wonder if you've tried the new Kustomize Controller? We are being very conservative about upgrading things in Flux v1 because of the new development work that is taking place in Flux v2.

If there is something stopping you from moving to Flux v2, we'd much rather address that and make the investment where the new development is going.

I see you've submitted this as a PR, I'm not sure it can be merged if it adds new features. Can you make the case for this in a way that it helps as a transitionary feature, that will make it easier to move to Flux v2?

Broadly, we are not trying to attract new users to Flux v1 if they can be onboarded with the new architecture instead because so many scaling and support issues are already solved there. I would be more likely to consider this for merge if it was accompanied by a piece of documentation explaining the new functionality. What do you think about this?

**Comment by kingdonb** [comment]
There is `fluxcd/flux-prerelease:master-9beb95eb` which you can pull now, if you wish to confirm before 1.22.2 is released that the update addresses your concerns from this issue.

I will hold this issue open until 1.23.0 simply for tracking that, whenever the next minor release 1.23.0 is out, we actually pick the same version of Kustomize that is in use in Flux v2 at that time.

The release should be ready not much later today, assuming I can find approvers as I need them. 👍

**Comment by kingdonb** [comment]
According to #3500, we might be inclined to downgrade the Kustomize version back to... I hope you are ready for this... Kustomize of no higher than `<v3.8.8` 🤦 

Thanks again for your initial submission, which suggested the most conservative upgrade. I think it will cause too much chaos to upgrade Kustomize any further, and based on experience in Flux v2, the Kustomize v4 upgrade certainly has enough breaking changes that it will definitely not be possible.

Upgrading to v3.10.0 seems quite unlikely too at this point. I'm going to leave this issue open for visibility, but for the record I just wanted to tie it to the new issue report.
