### ISSUE TITLE
Document default NetworkPolicy behaviour

### ISSUE THREAD

**Issue by br0ziliy** [fluxcd/flux#3486]
**Describe the bug**

Flux creates a set of NetworkPolicies that limit access to controller Pods - which is a good thing.
Issue is that currently NetworkPolicies that are created during installation do allow ingress traffic to the notification controller from within the same cluster only.
I suggest the documentation in https://fluxcd.io/docs/guides/webhook-receivers/ and https://fluxcd.io/docs/components/notification/receiver/ updated with the note that in order to access a webhook from the outside networks one would need to create additional NetworkPolicy to explicitly allow it.  

**Additional context**

- Flux version: v0.13.3

**Comment by kingdonb** [comment]
I have noticed this too, the receiver guides suggest creating a loadbalancer, but the default network policy provided seems to block the communication of the loadbalancer with the service (at least on my DOK8s cluster, with cilium, this was the case)

If you create an ingress for your receiver, the networkpolicy is (I think) configured to allow the ingress traffic to reach the notification-controller.

It would make sense for our examples to show both: [a webhook ingress (my example)](https://github.com/kingdonb/csh-flux/blob/4aa0fd91fb3a37a07a2d82062270ff46757a0799/clusters/yebyen-okd4/yebyen-okd4/gitno-hephy-rocks-ingress.yaml#L1-L16) for Notification Controller domain, and also an explanation of how to patch or modify the NetworkPolicy such that it permits loadbalancer communication with the notification controller.

Do you have the NetworkPolicy additions required to make a LoadBalancer work, can you provide here as an example?

**Comment by kingdonb** [comment]
(I completely did not notice that this issue report was submitted to the wrong location)

This is a Flux 2 report. This is the Flux v1 issue repo. #3320 Flux v1 is in maintenance mode.

This should most likely be reported in [fluxcd/flux2 Issues](/fluxcd/flux2/issues) instead. Please include enough detail to clearly understand what issue is being reported, (I think I understood your report because I've seen this issue before, but I'm not at all confident the issue is that well-known to be immediately understood by anyone else without more info as context.)

**Comment by br0ziliy** [comment]
Oh, apologies; https://github.com/fluxcd/flux2/issues/1448 created. I rephrased it a bit and provided a bit more context, along with an example NetworkPolicy.
