### ISSUE TITLE
flux 1.23.0 many too timeout in index.docker.io

### ISSUE THREAD

**Issue by ndj888** [fluxcd/flux#3506]
-07-21T08:00:05.757361031Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="Get \"https://index.docker.io/v2/feiyu563/prometheus-alert/manifests/release-1.2\": rate limited: rate: Wait(n=1) would exceed context deadline" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:00:05.757435991Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="Get \"https://index.docker.io/v2/feiyu563/prometheus-alert/manifests/v-4.3.3\": rate limited: rate: Wait(n=1) would exceed context deadline" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:00:05.757972713Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="Get \"https://index.docker.io/v2/feiyu563/prometheus-alert/manifests/v-4.3.4\": rate limited: rate: Wait(n=1) would exceed context deadline" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:00:05.758159238Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="Get \"https://index.docker.io/v2/feiyu563/prometheus-alert/manifests/v-4.4.0\": rate limited: rate: Wait(n=1) would exceed context deadline" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:00:15.745326168Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:00:25.783353736Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:00:35.73394183Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:00:45.719047207Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:00:55.704407449Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:01:05.702478086Z caller=repocachemanager.go:226 component=warmer canonical_name=index.docker.io/feiyu563/prometheus-alert auth={map[]} err="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" ref=feiyu563/prometheus-alert:v-4.4.0
ts=2021-07-21T08:01:05.702537147Z caller=warming.go:206 component=warmer updated=feiyu563/prometheus-alert successful=0 

- Flux version:  1.23.0
- Kubernetes version: 1.19

**Comment by ndj888** [comment]
Affects normal project updates

**Comment by kingdonb** [comment]
@ndj888 Thanks for the report. This is not something that Flux v1 can work around, and it has been noted in the FAQ that rate limiting is an issue which will affect Flux v1, this is the most urgent reason for users to upgrade to Flux v2 which does not scan images via the pull method, that is rate limited.

https://fluxcd.io/legacy/flux/faq/#flux-v1-runtime-behavior-doesnt-scale-well

You can increase the rate limit as it says by using an ImagePullSecret that has an authenticated access, but unless you are paying Docker Hub, that's only likely to get you a marginal increase in the number of pulls you can do. If this is production and you are working around this like a disaster, then that's what I would suggest for now, but the long term solution is to stop doing the rate-limited behavior so much, which is what the FAQ entry in the link attempts to explain.

**Comment by kingdonb** [comment]
Just a secondary note, if you are restarting Flux and the Flux services in an effort to resolve this issue, don't do that, it will only make matters worse...

Each time memcache is restarted, it dumps the entire cache of information that it has collected about which images have published which tags, and what order they should be considered to have for automated upgrades that select the latest image.

That means when memcached is restarted, Flux has to start the entire scan over from scratch, (it's scanning the registry of every image on the entire cluster, except any which have been excluded from scanning... Flux will have to pull every image header to retrieve the metadata and learn the build timestamp, so they can be precisely ordered for the image automation.)

**Comment by kingdonb** [comment]
I want to add a note, that I was doing some testing with a by-hand manually operated Docker Registry client and I did get 429 Too Many Requests response very quickly, without Flux. I don't do this every day but I haven't seen that before.

I don't think I had any other registry clients making pulls, and the next attempt a few seconds later succeeded, but it is possible that if you noticed something changed, it was a change at Docker Hub. Now I don't normally operate a registry v2 client by hand like this, but this morning I was for debugging, and it did get the rate limiting error on the very first attempt.

If you leave your Flux v1 installation running for a long enough time, it will (usually? should?) eventually clear the backlog and pull every image manifest down, such that it can mostly stop scanning after a while. If you have just upgraded and only saw this error for the first time, it is expected, since upgrading will have likely taken down and restarted the memcached.

But if your cluster is temporary and you are restarting memcached all the time, this is going to be tremendously wasteful for you and it will be slow and painful, as described in the FAQ entry, the more published image tags that exist and match your Image Update filters, for each different image that you have hosted and running in your cluster, the longer this will take. No image upgrades will be processed until this is finished, because the images have to be strictly ordered by build time.

This is fixed in Flux v2 via a slightly breaking change that is described in more detail here: https://fluxcd.io/docs/guides/sortable-image-tags/

I'm going to close this issue but you are welcome to respond if you have more questions, and I'll be happy to answer.

**Comment by ndj888** [comment]
I had to give up updating docker.io altogether, and it solved my problem.
[2411](https://github.com/fluxcd/flux/issues/2411#issuecomment-525774385)

**Comment by ndj888** [comment]
@kingdonb

**Comment by kingdonb** [comment]
Thanks for the update!
