### ISSUE TITLE
deautomated/locked services feel broken if they used to be automated.

### ISSUE THREAD

**Issue by foot** [fluxcd/flux#512]
Things feel broken, which is bad. When I merge a PR I hop over to my build channel and wait for a notification that its been deployed. If a service is locked/deautomated nothing happens leaving me scratching my head and frustrated.

Maybe solutions: Have slack notifications for 
 - anything deautomated: "we just saw a new version for this!, but this service wasn't automated (also maybe its locked)"
 - locked + automated: "we wanted to update this but its locked: ('lock reason')"

**Comment by foot** [comment]
> anything deautomated: "we just saw a new version for this!, but this service wasn't automated (also maybe its locked)"

Could get a bit spammy though? I'm not sure how frequently stuff gets released... probably not that often really.

**Comment by squaremo** [comment]
Off the cuff idea: have an integration with GitHub in the same way CircleCI does, saying what happened with the PR.

**Comment by kingdonb** [comment]
I think this is better addressed in Flux v2, where suspend is in the spec for each CRD.

I imagine you would want an alert to be firing whenever anything is in a suspend state, and with that alert firing, you would have enough context on your notification channel to see that eg. kustomization-controller is not syncing your manifests because such and such kustomization is still in suspended state. (It would be harder to notify "a kustomization should have just been applied, but it was suspended" – noting that it sounds like a really nice experience, I'm not sure how much more it would cost or how much better it would be in practice than simply firing alerts periodically as any CRD remains suspended.)

I don't know the story well enough in Flux v2 to say if this is really closed, and it's an interesting question so I think I'll leave it open until I can recommend a specific strategy. I think we may need to produce a piece of documentation or best-practices guide to alerting that includes a configuration such as this (and if that already exists, I'd greatly appreciate a pointer.)

Flux v2 is now at 100% feature parity, and we are ushering users toward the new version. Flux v1 is in maintenance mode. Please consider upgrading!
