### ISSUE TITLE
automation without the config repo

### ISSUE THREAD

**Issue by rade** [fluxcd/flux#551]
The config repo is central to the current flux model, and for good reasons. However, it also represents an opinion about How To Do Things, and therefore can be a barrier to adoption. So I was wondering whether flux could provide some useful functionality even when no config repo is specified...

Could flux determine what images/repos are used by inspecting the currently running k8s? And all the automation/locking/manual controls would operate directly on the k8s config.

This would basically re-position the config repo as an optional add-on, providing more functionality.

**Comment by squaremo** [comment]
It is not always a simplification to remove an ingredient. In this case, it would mean having two modes, with git and without git, which the user must understand and internalise, because they will work differently. And more code and user interface, of course.

I would much rather understand why using a git repo is considered a barrier*, and help people get past it.

(*If it's just because it's one more thing you need to have set up, we can do a lot to alleviate that, like making a repo with github integration and populating it from the cluster; and in general, helping people bootstrap both cluster and repo.)

**Comment by rade** [comment]
The "extra config needed" is but a small piece. I reckon operating w/o a config repo would be easier for people to grok - there's a lot less going on (and yes, less functionality too), and there's less buy-in into "the right way to do things" and changes to existing working practices required.

Introducing this mode of operation does not get us off the hook for simplifying and better explaining the git-repo-backed operations mode, but it lowers the initial barrier to adoption.

**Comment by rade** [comment]
btw, I get the concern about "two completely different modes". I am rather hoping that the gitfull mode can be positioned/explained as a progression from the gitless mode; the user shouldn't have to unlearn/undo anything.

**Comment by errordeveloper** [comment]
Instead gitless mode, I'd consider having a shadow repo that we'd create for the user behind the scenes and populate with manifests for apps that are found in their cluster and, perhaps, only the ones that user desires to manage (e.g. when they make a release).
At a later stage, users would probably like to reclaim their repo. There are a few options here that we could offer. Let's suppose we would use Github for keeping our shadow repo, and as the user may choose to transfer the repo to their Github account. Alternatively, they could provide a URL of an existing repo, and we'd clone that and try doing something like subtree merge and push (on failure we could provide instruction for manual merge (although that may be an extremely rare case if we are to attempt merging into a new subdirectory).

**Comment by kingdonb** [comment]
This is against the direction of what has been done in Flux v2, although it is interesting to consider a "gitless" mode or "shadow-git" that imports and tracks your workloads from the cluster rather than the opposite, it is not something that Flux now supports or has any sort of near or far future plans to support.

What has been done recently is to add an adapter for Source and an API which can apply from an upstream of GitRepository, HelmRepository, and Bucket (eg an S3 bucket) - https://toolkit.fluxcd.io/components/source/controller/ the new source API solidifies the design of Flux as a tool that takes a manifest from a Source (probably one that lives outside of the cluster) and applies it to a cluster, at present either through a `Kustomization` or a `HelmRelease`. Flux affects changes to the cluster state with automation, always by changing the `Source`, which has whatever downstream effects flow naturally from that change, but always treating a `Source` as some form of authority for the truth of what should be deployed on the system.

There is certainly merit to the idea that Flux's other components could be used in some future configuration without the involvement of a source, but as Flux v1 is in maintenance mode and Flux v2 has just crossed 100% feature parity with the 0.8 release, it is safe to say the radically different idea about this feature will not be built on Flux v1.

Please join us in Flux v2 and help us crossing the gap to make sure all use cases from Flux v1 are at least as good, or of course hopefully better, in the next version of Flux which has been redesigned and rewritten from scratch.

Thanks for the discussion, now closing this issue.
