### ISSUE TITLE
Defer automated deploys when alerts are pending

### ISSUE THREAD

**Issue by awh** [fluxcd/flux#627]
Similar to the way kured can defer reboots if the cluster is in a degraded state, fluxd could talk to the Prometheus alert manager (or equivalent) and block deployments under certain alert conditions.

**Comment by awh** [comment]
weaveworks/flux#627

**Comment by kingdonb** [comment]
I'm going to suggest this is not actually how you want your system to respond in an emergency, especially for gitops-only setups as we prefer. You don't want Flux to block deployments during an alert; if something is wrong with the workloads, a change may be needed, and thus doing a deployment may then be the way out of the production incident situation.

In any case, the Flux v2 docs describe at least two new major development efforts that may help with this use case:

https://toolkit.fluxcd.io/components/notification/alert/ - the Alert CRD which can be used with the new Health Assessment feature, to escalate incidents through your desired alert channel to notify an on-call person who can respond and take a look,

and a section in the Image Update Automation docs on **Incident Management** - https://toolkit.fluxcd.io/guides/image-update/#incident-management - with guidance about how image automation can be suspended or manipulated during any escalation-class incident. You can imagine an automated responder which does something when Alert is firing, like for example suspending *any other* image updates, and quickly get to see how complicated and brittle this could be. I say any other image updates, because that makes sense to me as a possibly reasonable way for the system to respond, but I am not recommending that.

Posit how this can go wrong: I have just pushed a bad update through git, now the system is in Alert condition, and **oops** I see what's wrong. I push another git commit, but **oh no** deployment is suspended. Now I have to wait for an adult (Ops person / on-call responder with admin access) because I have made a mistake, and the system will not let me fix it. This is a sub-optimal outcome I foresee from pursuing this strategy of incident management. A viable GitOps implementation should hopefully not require this special class of ops person to get out of bed and intervene with a `kubectl` admin access, as it should be fixed the same way that it was broken, with another git commit. With Flux's health assessment and canary analysis through Flagger, it could have been stopped from impacting end-users even sooner, so no human operator is in the hot seat.

If the news hasn't already reached your corner of the Flux-o-sphere, Flux v2 is now at 100% feature parity and we are recommending users of Flux v1 migrate to Flux v2 when they are able. Lots of production users are already migrated, and with the 0.8 release, we hope that everyone's use cases are at least at parity, with most use cases seeing some improvements!

Flux v1 is still in maintenance mode, and receives only bug fixes and security releases. Since this represents an enhancement, I'm going to close the issue and suggest if you think there's something Flux v2 could be doing better, to raise it again on [the GH Discussions page](https://github.com/fluxcd/flux2/discussions). Thanks for using Flux!
