### ISSUE TITLE
unable to fast-forward after force-push to config repo

### ISSUE THREAD

**Issue by errordeveloper** [fluxcd/flux#696]
I've just amended a commit and force-pushed it, this is what I got in the flux log:
```
ts=2017-08-09T15:59:15Z caller=loop.go:47 component=sync-loop operation=pull err="git pull --ff-only git@github.com:errordeveloper/istio-gitops.git master: fatal: Not possible to fast-forward, aborting."
```
It sounds like we would face the same issue in any other case of history being re-written, most notably a rebase.

As a user, I'd like flux to trust whatever I've pushed to the repo, I'd be okay with it doing something like `git fetch <upstream> && git reset --hard <upstream>/<branch>`.

**Comment by squaremo** [comment]
> As a user, I'd like flux to trust whatever I've pushed to the repo,

Yes that seems a fair principle. Ultimately we are syncing with some files in a directory -- the fact they have a chequered history is irrelevant.

I would be a little worried about how other bits of the system behave in the case of rewritten git commits, so I'd want to look into where assumptions are made. But it's not this bug's fault that people rewrite git history :)

**Comment by varac** [comment]
I think I just stepped into the same bug after force-pushing a rebased branch:

```
ts=2020-05-29T20:51:23.72285586Z caller=loop.go:133 component=sync-loop event=refreshed url=https://@.../varac/... branch=varac HEAD=6c45cd95974ce4f61f27dd316885534750eb9ae3
ts=2020-05-29T20:51:24.006651359Z caller=loop.go:107 component=sync-loop err="fatal: Invalid revision range ef372acd585c5850a5c8de6291957b7fc6bc9d3e..6c45cd95974ce4f61f27dd316885534750eb9ae3, full output:\n fatal: Invalid revision range ef372acd585c5850a5c8de6291957b7fc6bc9d3e..6c45cd95974ce4f61f27dd316885534750eb9ae3\n"
```

Please make flux be able to deal with rewritten git history.
Until then, how would I manually recover from this ?

**Comment by varac** [comment]
Btw, this happend with flux 1.19.0

**Comment by avgalani** [comment]
just happened to me as well; sigh

**Comment by kingdonb** [comment]
Would it do to simply restart flux daemon when this error occurs?

This seems like a longstanding error that has survived several rewrites of related infra-code. Can we be sure it won't recur in Flux v2? I hope so, I can't say for sure, I don't understand it (source-controller) quite well enough yet.

I think the answer is no, it won't do to simply restart the flux daemon, but I think it is yes, it will be resolved in v2 since Sync and Apply concerns never intersect, they are in separate APIs now. Will source-controller be able to recover from a force push?

I certainly hope so, it only has one job now so it should be much easier to see that it gets handled well by rain, sleet, snow, etc. If it gets into unrecoverable state where fast forward is impossible, even if this is fatal, then it can simply suicide and let the next replacement pod take over. 👍  for the redesign, this makes things a lot simpler.

There are scaling reasons why Flux daemon restarts are expensive (the same reason that memcached was added is a great example), and Flux 2 has addressed those issues as well. Smaller controllers with single-purpose jobs can be restarted with a smaller blast radius, and cache volumes can be repopulated easier when the process of filling them with data is less intensive.

As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to reopen and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already, I will go ahead and close out this issue for now.
