### ISSUE TITLE
Automate only some images in a PodSpec

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#717]
In our prod environment we want to selectively automate images, rather than services (or what they are a proxy to, podspecs). In other words, for one deployment that uses two images, A and B, we want to automate deployments of new A images but leave B to be deployed manually or not at all.

**Comment by rade** [comment]
Interesting. A typical use of multi-image pods is to provide "infrastructure" functionality, such as logging, so one could image that all these should be updated automatically, across all services, while leaving the user-functionality providing images alone.

**Comment by kingdonb** [comment]
This idea is better accommodated in the redesigned Flux v2, where ImagePolicy markers can be applied to invoke image automation on each specific reference to an image or tag, with policies that are explicitly named per-reference:

https://toolkit.fluxcd.io/guides/image-update/#configure-image-update-for-custom-resources

As Flux v1 is in maintenance mode and this issue is addressed well in the architecture of Flux v2, which is nearing 100% feature parity and thus will soon after be upgraded to GA release, I think this report can be closed.

**Comment by kingdonb** [comment]
This request is very old, and as explained is addressed much better by the redesigned Flux v2. Closing.
