### ISSUE TITLE
flux.NewGitRemoteConfig() could validate some of the values

### ISSUE THREAD

**Issue by errordeveloper** [fluxcd/flux#722]
I've recently encountered that when I supplied syntactically invalid `--git-url` I got a very ambigous error message:

```
caller=main.go:335 component=git err="git clone: fatal: Could not read from remote repository."
```

When I've fixed the URL syntax but supplied a URL that was unaccesible I've also got the same error.

In my case, invalid syntax issue was to do with qoutes, and while it may be plausible to consider stripping paired quotes from all sting flag values, I think more generally we should validate git URLs as we have certain expectations about that. The constructor function, `flux.NewGitRemoteConfig()` already validates `path` argument and returns an error that causes the `fluxd` process to exit, so it seems rather quite plausible to validate the `url`.

I'm happy to open a PR, but wanted to double check what people think about this first. Also, I am pretty sure we make the assumption about read-write transport, but I wonder whether we consider HTTPS transport to be supported in some way or SSH is the only transport we currently care to support?

**Comment by tamarakaufler** [comment]
I looked into this and here are my thoughts.

error message
===========
The error received after supplying an incorrect repo is ambiguous because the failure could be caused by multiple issues.

- fatal: Could not read from ... (when requested repository does not exist, or no permission to access it)

[  These error messages are clearer:
- Connection timed out fatal: Could not read from ...
- Connection reset by peer fatal: Could not read from ...
- others?
]

I shall see if it is possible to isolate the problem. If not possible, then if the word "fatal" is not preceded by the problem description, we could add "requested repo does not exist, or no permission to access it" to the message to make it clearer what needs checking. 

git url check
==========
flux.NewGitRemoteConfig() validates the path in a very simple way: if the path is not empty, check that it starts with a slash. To supply the leading slash in the path is a plausible and easily checkable mistake. While we can check the git url to a point (we can strip double and single quotes, though supplying quotes to the other flags has a similar effect in that it would also be an error to do so), it is a question whether there is any point in doing that because even if the overall url format is correct, we still will not know if there was a typo until we actually try to clone it.

**Comment by tamarakaufler** [comment]
The more descriptive message about what could have gone wrong during a repo cloning is already implemented. Eg in case of missing deploy key, the UI message shows:
--------------------------------------------------------------------------------------------------------------
git clone: fatal: Could not read from remote repository.
Please check

    - The URL to your repository
    - That your repository allows read/write access to Weave Deploy's public ssh key.
--------------------------------------------------------------------------------------------------------------

As for the git url check, please see my comment above.

**Comment by mig4** [comment]
Could this be closed? It seems like there's nothing else to be done for this, no?
