### ISSUE TITLE
LogEvent uses a `context.TODO()`

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux#775]
The upstream API method `LogEvent` accepts a context, but when we use it we pass `context..TODO()`. I left it like this because it was not trivial, and not in the critical path of #759.

At some point it ought to be changed so that a context is passed through -- the main impediment is that the method also forms part of the EventWriter interface, where it doesn't make as much sense to include a context. It may turn out that interface isn't really necessary though.

**Comment by kingdonb** [comment]
I found the code in question: https://github.com/fluxcd/flux/blob/2fd24cc5d909930c7745ec884d9060f1239b7291/pkg/http/daemon/upstream.go#L182-L184

It may not be in scope for maintenance to resolve this, but I thought it wouldn't do to close it without at least locating the specific code in question.

**Comment by kingdonb** [comment]
I've added more `context.TODO()` in #3515 – I'd love to understand the purpose of context, I haven't really worked with this before.

I found http://p.agnihotry.com/post/understanding_the_context_package_in_golang/ which does a decent job explaining.

I think that any new context-driven features would be necessarily new features, and since Flux v1 in maintenance mode won't add new features, I'm not sure it's necessary to go any further down this road for now. I had to add TODO contexts in a few places in order to satisfy the requirements of the Kubernetes 1.21 client upgrade, but I won't use them for anything.

With all that in mind I think we can close this issue.
