### ISSUE TITLE
Duplicate resource definitions in git repository generates confusing error message

### ISSUE THREAD

**Issue by jacobsee** [fluxcd/flux#867]
I had the same deployment resource defined in two different files in my git repository (trying out different ideas). When attempting to start the flux container connected to this repository, it fails with the error message: `fatal: ambiguous argument 'flux-[org name]..HEAD': unknown revision or path not in the working tree.` This error message does not lead someone to the actual problem of a duplicate resource definition existing in the repository.

**Comment by squaremo** [comment]
Hmm yes, the error that's surfaced is only tenuously related isn't it. For the record, the problem is that Flux fails to complete the synchronisation because of the duplicate resource; but in the meantime, we're asking it "where have you synced to?" and it can't answer. Much better would be that the failure to complete the sync is reported.

This is related to #756, but that deals only with individual resources failing to be applied rather than the whole sync failing.

**Comment by 2opremio** [comment]
I think the error is way more helpful now.
