### ISSUE TITLE
Internal error: git repo is not configured

### ISSUE THREAD

**Issue by aaron7** [fluxcd/flux#874]
Deploying WC to production, I came across the error: `Internal error: git repo is not configured`.

The deploy was, however, successful, with a git commit being made and it being synced correctly.

The error was a little confusing as it implied that the git repo was not set up, even though it outputted that a commit was pushed and everything else succedded.

```
❯❯❯ fluxctl --token $PROD_TOKEN release --update-all-images --all --exclude=<redacted>
Submitting release ...
CONTROLLER                                  STATUS   UPDATES
<redacted>  <redacted>  <redacted>
Commit pushed:  d3a78e1
== Error ==

Internal error: git repo is not configured

We don't have a specific help message for the error above.

It would help us remedy this if you log an issue at

    https://github.com/weaveworks/flux/issues

saying what you were doing when you saw this, and quoting the message
at the top.
```

**Comment by squaremo** [comment]
When flux restarts, there is a period of initialisation while it clones the git repo. During that time, it will respond to most API calls with variations on "git repo is not ready".

I suspect what has happened here is that fluxctl has seen that the job completed, and while waiting for the daemon to have synced the resulting commit, fluxd restarts and goes through its initialisation.

This ought not be a 500; if it were a "softer" error, fluxctl would keep asking, rather than bailing.

**Comment by marccarre** [comment]
How much effort do you think this is for a Flux n00b @squaremo?
I'd like to try to fix it this week.

**Comment by squaremo** [comment]
#942 downgraded "non-specific" errors from 500 to 422, and I think that included the git not configured error. I have not checked that specific case.

**Comment by 2opremio** [comment]
Related https://github.com/fluxcd/flux/issues/2657

**Comment by kingdonb** [comment]
I will close the issue for now as it is stale. Flux v1 remains in maintenance mode.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, Flux v2, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.
