### ISSUE TITLE
Policy update Status and StatusString in conflict.

### ISSUE THREAD

**Issue by foot** [fluxcd/flux#931]
When updating policy on a resource not in the config repo:

```json
{
  "Result": {
    "spec": {
      "type": "policy",
      "cause": {
        "Message": "",
        "User": "simon <simon@weave.works>"
      },
      "spec": {
        "default:deployment/nginx": {
          "add": {
            "automated": "true"
          },
          "remove": null
        }
      }
    },
    "result": {
      "default:deployment/nginx": {
        "Status": "failed",
        "Error": "no resource file found for service",
        "PerContainer": null
      }
    }
  },
  "Err": "",
  "StatusString": "succeeded"
}
```

**Comment by squaremo** [comment]
Mm. Yes we could do a better job at that. The trickiness in general is that updates are often making changes to a number of resources, and some kinds of individual failure are tolerable; e.g., if it turns out one of the resources already has the policy being applied. (OK we don't currently do bulk policy updates, but you get what I mean.)

Having said that, this particular failure should not be tolerated, since it means the policy didn't stick and won't apply. It's difficult to see that as a success.

**Comment by kingdonb** [comment]
Sort of related: #3156 

General category of error: status information being kept incorrectly

**Comment by kingdonb** [comment]
At this time, we hope you have already begun migration away from Flux v1 / legacy over to the [current version of Flux](https://github.com/fluxcd/flux2).

We hope you've been able to upgrade to Flux v2, and note that Flux v1 remains in maintenance mode. Bugs with Flux v1 can be addressed as long as it remains in maintenance, according to the plan laid out in the [Flux Migration Timetable](https://fluxcd.io/docs/migration/timetable/). 👍 

Thanks for using Flux.
