### ISSUE TITLE
fluxctl release --exclude should support wildcards

### ISSUE THREAD

**Issue by marccarre** [fluxcd/flux#959]
Instead of having to do:
```
fluxctl --token $TOKEN release --update-all-images --all \
    --exclude=foo:deployment/bar \
    --exclude=foo:deployment/baz \
    --exclude=foo:deployment/cat \
    --exclude=foo:deployment/cow \
    --exclude=foo:deployment/dog \
    --exclude=foo:deployment/fly
```
I wish I could do:
```
fluxctl --token $TOKEN release --update-all-images --all \
    --exclude=foo:deployment/*
```

**Comment by rndstr** [comment]
Somewhat related to https://github.com/weaveworks/flux/issues/902 which I've mildly been looking into. I thought about `--controller=foo:deployment/*` instead of `--all --namespace=foo`but the problem with using 
The problem I see with `*` is it will be expanded by the shell, so you would need to quote it which is quite error-prone.
