### ISSUE TITLE
Daemon should use appropriate event type when logging events

### ISSUE THREAD

**Issue by lelenanam** [fluxcd/flux#965]
Daemon we should use appropriate event types when logging event: 
```
	EventAutomate     = "automate"
	EventDeautomate   = "deautomate"
	EventLock         = "lock"
	EventUnlock       = "unlock"
```
https://github.com/weaveworks/flux/blob/ca5faa4e64540646800f6a3dfe8c5715bad807fb/event/event.go#L22
Now there is a `commit` event type for automate/deautomate and lock/unlock.

**Comment by squaremo** [comment]
TBH the event stuff is rather tangled, after being adapted to three or four slightly different purposes. (Constructing commit messages; annotating commits; sending notifications; ...)

Lock/Automate are different to releases because they take effect when the change is made to the file and committed, rather than when the commit is synced. That's not to say we can't send events when we have pushed commits; it just needs to happen in a different bit of code.

**Comment by sambooo** [comment]
We almost certainly should change something here, but it's possibly not blocking [what you want to do](https://github.com/weaveworks/service/issues/1787) as we discussed earlier. `CommitEventMetadata` contains the information you're after, so let's see if that's sufficient for now.

In general we can't rely on users updating their flux as soon as we do a release, so it's unwise to depend on new behaviour until it's in the oldest version we choose to support.

**Comment by squaremo** [comment]
(backburnering)

**Comment by kingdonb** [comment]
Sounds like this was considered a breaking change, and cannot be followed through in Flux v1 maintenance.
